/**
 * Copyright (c) 2026 CARLOS Contributors. All Rights Reserved.
 *
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * CARLOS EMR Project
 * https://github.com/carlos-emr/carlos
 */

package io.github.carlos_emr.carlos.commn.dao;

import io.github.carlos_emr.carlos.commn.dao.utils.EntityDataGenerator;
import io.github.carlos_emr.carlos.commn.model.Demographic;
import io.github.carlos_emr.carlos.commn.model.Document;
import io.github.carlos_emr.carlos.commn.model.EmailConfig;
import io.github.carlos_emr.carlos.commn.model.EmailLog;
import io.github.carlos_emr.carlos.commn.model.OutboundEmailArchive;
import io.github.carlos_emr.carlos.commn.model.OutboundEmailArchiveAttachment;
import io.github.carlos_emr.carlos.commn.model.OutboundEmailArchiveDeletion;
import io.github.carlos_emr.carlos.test.base.CarlosTestBase;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration coverage for the outbound email archive mapping.
 *
 * <p><b>What this test is for.</b> The archive entities lean on JPA behaviour that
 * pure Mockito tests cannot reach: a {@code @MappedSuperclass} whose
 * {@code @PrePersist}/{@code @PreUpdate} callback mutates state, subclass callbacks
 * layered on top of it, cascade-persist of attachments, and lifecycle callbacks that
 * deliberately <em>throw</em> to block physical deletion. Whether Hibernate emits a
 * spurious UPDATE after INSERT — which would trip
 * {@code OutboundEmailArchiveDeletion.preventMutation()} at commit and break every
 * controlled deletion in production — is only observable against a real ORM.</p>
 *
 * <p><b>What this test is NOT.</b> The H2 schema here is generated by
 * {@code hibernate.hbm2ddl.auto=create} from the entities themselves, so agreement
 * between the entities and {@code V1.0.10__outbound_email_archive.sql} (column names,
 * NOT NULL, foreign keys, MariaDB column types) is <em>not</em> verified. That gap is
 * covered by the Flyway workflow plus a manual MariaDB pass, not here.</p>
 *
 * @since 2026-08-17
 * @see OutboundEmailArchiveDao
 */
@DisplayName("OutboundEmailArchive mapping integration tests")
@Tag("integration")
@Tag("dao")
@Transactional
class OutboundEmailArchiveDaoIntegrationTest extends CarlosTestBase {

    private static final String PROVIDER_NO = "999998";
    private static final String ARTIFACT_HASH = "a".repeat(64);
    private static final String ATTACHMENT_HASH = "b".repeat(64);

    @Autowired
    private OutboundEmailArchiveDao outboundEmailArchiveDao;

    @Autowired
    private OutboundEmailArchiveDeletionDao outboundEmailArchiveDeletionDao;

    @PersistenceContext(unitName = "entityManagerFactory")
    private EntityManager entityManager;

    private Demographic demographic;
    private EmailLog emailLog;
    private Document document;

    @BeforeEach
    void seedArchiveGraph() throws Exception {
        demographic = new Demographic();
        EntityDataGenerator.generateTestDataForModelClass(demographic);
        demographic.setDemographicNo(null);
        entityManager.persist(demographic);

        EmailConfig emailConfig = new EmailConfig(
                EmailConfig.EmailType.SMTP, EmailConfig.EmailProvider.GMAIL, "clinic@example.com");
        entityManager.persist(emailConfig);

        emailLog = new EmailLog(emailConfig, "clinic@example.com",
                new String[] {"patient@example.com"}, "Referral", "Body", EmailLog.EmailStatus.SUCCESS);
        emailLog.setDemographic(demographic);
        emailLog.setTimestamp(new Date());
        entityManager.persist(emailLog);

        document = new Document();
        document.setDocfilename("20260817120000_00001_outbound-email.eml");
        document.setDocdesc("Outbound email archive");
        document.setDoctype("email");
        document.setDoccreator(PROVIDER_NO);
        document.setResponsible(PROVIDER_NO);
        document.setContenttype("message/rfc822");
        document.setStatus(Document.STATUS_ACTIVE);
        document.setPublic1(0);
        document.setObservationdate(new Date());
        document.setContentdatetime(new Date());
        entityManager.persist(document);

        entityManager.flush();
    }

    private OutboundEmailArchive newArchive() {
        OutboundEmailArchive archive = new OutboundEmailArchive();
        archive.setEmailLog(emailLog);
        archive.setDemographic(demographic);
        archive.setDocument(document);
        archive.setArtifactType(OutboundEmailArchive.ARTIFACT_TYPE_SMTP_RFC822);
        archive.setTransportType("SMTP");
        archive.setProviderName("GMAIL");
        archive.setContentType("message/rfc822");
        archive.setFileName(document.getDocfilename());
        archive.setSha256Hash(ARTIFACT_HASH);
        archive.setByteSize(2048L);
        archive.setLastUpdateUser(PROVIDER_NO);
        return archive;
    }

    @Nested
    @DisplayName("Persistence and lifecycle callbacks")
    class PersistenceAndLifecycle {

        @Test
        @Tag("create")
        @DisplayName("should apply archive defaults from the PrePersist callback")
        void shouldApplyArchiveDefaults_whenPersistedWithoutExplicitValues() {
            OutboundEmailArchive archive = newArchive();

            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();
            entityManager.clear();

            OutboundEmailArchive reloaded = outboundEmailArchiveDao.find(archive.getId());
            assertThat(reloaded.getStorageType()).isEqualTo(OutboundEmailArchive.STORAGE_TYPE_EDOC);
            assertThat(reloaded.getRetentionPolicy()).isEqualTo(OutboundEmailArchive.RETENTION_POLICY_PERMANENT);
            assertThat(reloaded.getSendStatus()).isEqualTo(OutboundEmailArchive.SEND_STATUS_ARCHIVED);
            assertThat(reloaded.getArchivedAt()).isNotNull();
            assertThat(reloaded.getLastUpdateDate()).isNotNull();
            assertThat(reloaded.isLegalHold()).isFalse();
            assertThat(reloaded.isDeleted()).isFalse();
        }

        @Test
        @Tag("create")
        @DisplayName("should cascade-persist attachments with the owning archive")
        void shouldCascadePersistAttachments_withOwningArchive() {
            OutboundEmailArchive archive = newArchive();
            OutboundEmailArchiveAttachment attachment = new OutboundEmailArchiveAttachment();
            attachment.setFileName("referral.pdf");
            attachment.setContentType("application/pdf");
            attachment.setSha256Hash(ATTACHMENT_HASH);
            attachment.setByteSize(512L);
            attachment.setSourceDocumentType("DOCUMENT");
            attachment.setSourceDocumentId(document.getId());
            attachment.setDocument(document);
            attachment.setLastUpdateUser(PROVIDER_NO);
            archive.addAttachment(attachment);

            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();
            entityManager.clear();

            OutboundEmailArchive reloaded = outboundEmailArchiveDao.find(archive.getId());
            assertThat(reloaded.getAttachments()).hasSize(1);
            OutboundEmailArchiveAttachment reloadedAttachment = reloaded.getAttachments().get(0);
            assertThat(reloadedAttachment.getFileName()).isEqualTo("referral.pdf");
            assertThat(reloadedAttachment.getSha256Hash()).isEqualTo(ATTACHMENT_HASH);
            assertThat(reloadedAttachment.getByteSize()).isEqualTo(512L);
            assertThat(reloadedAttachment.getCreatedAt()).isNotNull();
        }

        @Test
        @Tag("delete")
        @DisplayName("should block physical removal of an archive")
        void shouldBlockPhysicalRemoval_forPersistedArchive() {
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();

            assertThatThrownBy(() -> {
                entityManager.remove(archive);
                entityManager.flush();
            }).isInstanceOf(UnsupportedOperationException.class)
                    .hasMessageContaining("controlled tombstone workflow");
        }
    }

    @Nested
    @DisplayName("Controlled deletion")
    class ControlledDeletion {

        /**
         * The load-bearing case. {@code OutboundEmailArchiveArtifact} carries a
         * {@code @PrePersist @PreUpdate} callback that mutates {@code lastUpdateDate},
         * while {@code OutboundEmailArchiveDeletion} adds a {@code @PreUpdate} that
         * throws. If Hibernate ever issued an UPDATE for a just-inserted tombstone,
         * every controlled deletion would fail at commit rather than at the call.
         */
        @Test
        @Tag("create")
        @DisplayName("should persist a tombstone without tripping the immutability callback")
        void shouldPersistTombstone_withoutTrippingImmutabilityCallback() {
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();

            archive.markDeleted(PROVIDER_NO, "Patient requested cleanup");
            OutboundEmailArchiveDeletion deletion =
                    OutboundEmailArchiveDeletion.fromArchive(archive, PROVIDER_NO, "Patient requested cleanup");

            outboundEmailArchiveDao.merge(archive);
            outboundEmailArchiveDeletionDao.persist(deletion);
            entityManager.flush();
            entityManager.clear();

            OutboundEmailArchive reloadedArchive = outboundEmailArchiveDao.find(archive.getId());
            assertThat(reloadedArchive.isDeleted()).isTrue();
            assertThat(reloadedArchive.getDeletedByProviderNo()).isEqualTo(PROVIDER_NO);
            assertThat(reloadedArchive.getDeleteReason()).isEqualTo("Patient requested cleanup");

            OutboundEmailArchiveDeletion reloadedDeletion = outboundEmailArchiveDeletionDao.find(deletion.getId());
            assertThat(reloadedDeletion.getSha256Hash()).isEqualTo(ARTIFACT_HASH);
            assertThat(reloadedDeletion.getByteSize()).isEqualTo(2048L);
            assertThat(reloadedDeletion.getDeletedAt()).isNotNull();
        }

        @Test
        @Tag("update")
        @DisplayName("should reject mutation of a persisted tombstone")
        void shouldRejectMutation_ofPersistedTombstone() {
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();

            archive.markDeleted(PROVIDER_NO, "Patient requested cleanup");
            OutboundEmailArchiveDeletion deletion =
                    OutboundEmailArchiveDeletion.fromArchive(archive, PROVIDER_NO, "Patient requested cleanup");
            outboundEmailArchiveDeletionDao.persist(deletion);
            entityManager.flush();

            deletion.setDeleteReason("Rewritten reason");

            assertThatThrownBy(() -> entityManager.flush())
                    .isInstanceOf(UnsupportedOperationException.class)
                    .hasMessageContaining("immutable");
        }
    }

    @Nested
    @DisplayName("Query methods")
    class QueryMethods {

        @Test
        @Tag("read")
        @DisplayName("should return archives for an email log newest first")
        void shouldReturnArchivesForEmailLog_newestFirst() {
            OutboundEmailArchive older = newArchive();
            older.setArchivedAt(new Date(1_700_000_000_000L));
            outboundEmailArchiveDao.persist(older);

            OutboundEmailArchive newer = newArchive();
            newer.setArchivedAt(new Date(1_800_000_000_000L));
            outboundEmailArchiveDao.persist(newer);
            entityManager.flush();

            List<OutboundEmailArchive> result = outboundEmailArchiveDao.findByEmailLogId(emailLog.getId());

            assertThat(result).extracting(OutboundEmailArchive::getId)
                    .containsExactly(newer.getId(), older.getId());
        }

        @Test
        @Tag("read")
        @DisplayName("should return archives for a demographic newest first")
        void shouldReturnArchivesForDemographic_newestFirst() {
            OutboundEmailArchive older = newArchive();
            older.setArchivedAt(new Date(1_700_000_000_000L));
            outboundEmailArchiveDao.persist(older);

            OutboundEmailArchive newer = newArchive();
            newer.setArchivedAt(new Date(1_800_000_000_000L));
            outboundEmailArchiveDao.persist(newer);
            entityManager.flush();

            List<OutboundEmailArchive> result =
                    outboundEmailArchiveDao.findByDemographicNo(demographic.getDemographicNo());

            assertThat(result).extracting(OutboundEmailArchive::getId)
                    .containsExactly(newer.getId(), older.getId());
        }
    }
}
