/**
 * Copyright (c) 2026 CARLOS Contributors. All Rights Reserved.
 *
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * CARLOS EMR Project
 * https://github.com/carlos-emr/carlos
 */

package io.github.carlos_emr.carlos.commn.dao;

import io.github.carlos_emr.carlos.commn.dao.utils.EntityDataGenerator;
import io.github.carlos_emr.carlos.commn.model.Demographic;
import io.github.carlos_emr.carlos.commn.model.Document;
import io.github.carlos_emr.carlos.commn.model.EmailConfig;
import io.github.carlos_emr.carlos.commn.model.EmailLog;
import io.github.carlos_emr.carlos.commn.model.OutboundEmailArchive;
import io.github.carlos_emr.carlos.commn.model.OutboundEmailArchiveAttachment;
import io.github.carlos_emr.carlos.commn.model.OutboundEmailArchiveDeletion;
import io.github.carlos_emr.carlos.commn.model.OutboundEmailArchiveLegalHoldEvent;
import io.github.carlos_emr.carlos.test.base.CarlosTestBase;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.hibernate.exception.ConstraintViolationException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration coverage for the outbound email archive mapping.
 *
 * <p><b>What this test is for.</b> The archive entities lean on JPA behaviour that
 * pure Mockito tests cannot reach: a {@code @MappedSuperclass} whose
 * {@code @PrePersist}/{@code @PreUpdate} callback mutates state, subclass callbacks
 * layered on top of it, cascade-persist of attachments, and lifecycle callbacks that
 * deliberately <em>throw</em> to block physical deletion. Whether Hibernate emits a
 * spurious UPDATE after INSERT — which would trip
 * {@code OutboundEmailArchiveDeletion.preventMutation()} at commit and break every
 * controlled deletion in production — is only observable against a real ORM.</p>
 *
 * <p><b>What this test is NOT.</b> The H2 schema here is generated by
 * {@code hibernate.hbm2ddl.auto=create} from the entities themselves, so agreement
 * between the entities and {@code V1.0.16__outbound_email_archive.sql} (column names,
 * NOT NULL, foreign keys, MariaDB column types) is <em>not</em> verified. That gap is
 * covered by the Flyway workflow plus a manual MariaDB pass, not here.</p>
 *
 * @since 2026-08-17
 * @see OutboundEmailArchiveDao
 */
@DisplayName("OutboundEmailArchive mapping integration tests")
@Tag("integration")
@Tag("dao")
@Transactional
class OutboundEmailArchiveDaoIntegrationTest extends CarlosTestBase {

    private static final String PROVIDER_NO = "999998";
    private static final String ARTIFACT_HASH = "a".repeat(64);
    private static final String ATTACHMENT_HASH = "b".repeat(64);

    @Autowired
    private OutboundEmailArchiveDao outboundEmailArchiveDao;

    @Autowired
    private DocumentDao documentDao;

    @Autowired
    private OutboundEmailArchiveDeletionDao outboundEmailArchiveDeletionDao;

    @Autowired
    private OutboundEmailArchiveLegalHoldEventDao outboundEmailArchiveLegalHoldEventDao;

    @PersistenceContext(unitName = "entityManagerFactory")
    private EntityManager entityManager;

    private Demographic demographic;
    private EmailLog emailLog;
    private Document document;

    @BeforeEach
    void seedArchiveGraph() throws Exception {
        demographic = new Demographic();
        EntityDataGenerator.generateTestDataForModelClass(demographic);
        demographic.setDemographicNo(null);
        entityManager.persist(demographic);

        EmailConfig emailConfig = new EmailConfig(
                EmailConfig.EmailType.SMTP, EmailConfig.EmailProvider.GMAIL, "clinic@example.com");
        entityManager.persist(emailConfig);

        emailLog = new EmailLog(emailConfig, "clinic@example.com",
                new String[] {"patient@example.com"}, "Referral", "Body", EmailLog.EmailStatus.SUCCESS);
        emailLog.setDemographic(demographic);
        emailLog.setTimestamp(new Date());
        entityManager.persist(emailLog);

        document = new Document();
        document.setDocfilename("20260817120000_00001_outbound-email.eml");
        document.setDocdesc("Outbound email archive");
        document.setDoctype("email");
        document.setDoccreator(PROVIDER_NO);
        document.setResponsible(PROVIDER_NO);
        document.setContenttype("message/rfc822");
        document.setStatus(Document.STATUS_ACTIVE);
        document.setPublic1(0);
        document.setObservationdate(new Date());
        document.setContentdatetime(new Date());
        entityManager.persist(document);

        entityManager.flush();
    }

    private OutboundEmailArchive newArchive() {
        OutboundEmailArchive archive = new OutboundEmailArchive();
        archive.setEmailLog(emailLog);
        archive.setDemographic(demographic);
        archive.setDocument(document);
        archive.setArtifactType(OutboundEmailArchive.ARTIFACT_TYPE_SMTP_RFC822);
        archive.setTransportType("SMTP");
        archive.setProviderName("GMAIL");
        archive.setContentType("message/rfc822");
        archive.setFileName(document.getDocfilename());
        archive.setSha256Hash(ARTIFACT_HASH);
        archive.setByteSize(2048L);
        archive.setLastUpdateUser(PROVIDER_NO);
        return archive;
    }

    @Nested
    @DisplayName("Persistence and lifecycle callbacks")
    class PersistenceAndLifecycle {

        @Test
        @Tag("create")
        @DisplayName("should apply archive defaults from the PrePersist callback")
        void shouldApplyArchiveDefaults_whenPersistedWithoutExplicitValues() {
            OutboundEmailArchive archive = newArchive();

            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();
            entityManager.clear();

            OutboundEmailArchive reloaded = outboundEmailArchiveDao.find(archive.getId());
            assertThat(reloaded.getStorageType()).isEqualTo(OutboundEmailArchive.STORAGE_TYPE_EDOC);
            assertThat(reloaded.getRetentionPolicy()).isEqualTo(OutboundEmailArchive.RETENTION_POLICY_PERMANENT);
            assertThat(reloaded.getSendStatus()).isEqualTo(OutboundEmailArchive.SEND_STATUS_ARCHIVED);
            assertThat(reloaded.getArchivedAt()).isNotNull();
            assertThat(reloaded.getLastUpdateDate()).isNotNull();
            // Legal hold is ON from creation: an archive is not deletable until an
            // admin releases it, and that release leaves its own event record.
            assertThat(reloaded.isLegalHold()).isTrue();
            assertThat(reloaded.isDeleted()).isFalse();
        }

        @Test
        @Tag("create")
        @DisplayName("should cascade-persist attachments with the owning archive")
        void shouldCascadePersistAttachments_withOwningArchive() {
            OutboundEmailArchive archive = newArchive();
            OutboundEmailArchiveAttachment attachment = new OutboundEmailArchiveAttachment();
            attachment.setFileName("referral.pdf");
            attachment.setContentType("application/pdf");
            attachment.setSha256Hash(ATTACHMENT_HASH);
            attachment.setByteSize(512L);
            attachment.setSourceDocumentType("DOCUMENT");
            attachment.setSourceDocumentId(document.getId());
            attachment.setDocument(document);
            attachment.setLastUpdateUser(PROVIDER_NO);
            archive.addAttachment(attachment);

            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();
            entityManager.clear();

            OutboundEmailArchive reloaded = outboundEmailArchiveDao.find(archive.getId());
            assertThat(reloaded.getAttachments()).hasSize(1);
            OutboundEmailArchiveAttachment reloadedAttachment = reloaded.getAttachments().get(0);
            assertThat(reloadedAttachment.getFileName()).isEqualTo("referral.pdf");
            assertThat(reloadedAttachment.getSha256Hash()).isEqualTo(ATTACHMENT_HASH);
            assertThat(reloadedAttachment.getByteSize()).isEqualTo(512L);
            assertThat(reloadedAttachment.getCreatedAt()).isNotNull();
        }

        @Test
        @Tag("read")
        @DisplayName("should recognize an archive attachment by its linked eDoc stored filename")
        void shouldRecognizeArchiveAttachment_byLinkedEdocStoredFilename() {
            Document attachmentDocument = new Document();
            attachmentDocument.setDocfilename("20260817120000_00002_referral.pdf");
            attachmentDocument.setDocdesc("Referral attachment");
            attachmentDocument.setDoctype("document");
            attachmentDocument.setDoccreator(PROVIDER_NO);
            attachmentDocument.setResponsible(PROVIDER_NO);
            attachmentDocument.setContenttype("application/pdf");
            attachmentDocument.setStatus(Document.STATUS_ACTIVE);
            attachmentDocument.setPublic1(0);
            attachmentDocument.setObservationdate(new Date());
            attachmentDocument.setContentdatetime(new Date());
            entityManager.persist(attachmentDocument);

            OutboundEmailArchive archive = newArchive();
            OutboundEmailArchiveAttachment attachment = new OutboundEmailArchiveAttachment();
            // The archive metadata retains the sender-facing filename, while document.docfilename
            // is the generated basename received by preview and raw-file routes.
            attachment.setFileName("referral.pdf");
            attachment.setContentType("application/pdf");
            attachment.setSha256Hash(ATTACHMENT_HASH);
            attachment.setByteSize(512L);
            attachment.setDocument(attachmentDocument);
            attachment.setLastUpdateUser(PROVIDER_NO);
            archive.addAttachment(attachment);

            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();
            entityManager.clear();

            assertThat(outboundEmailArchiveDao.existsByFileName("20260817120000_00002_referral.pdf"))
                    .isTrue();
            assertThat(outboundEmailArchiveDao.existsByFileName("referral.pdf"))
                    .as("a sender-facing attachment name is not a unique stored eDoc filename")
                    .isFalse();
        }

        @Test
        @Tag("delete")
        @DisplayName("should block physical removal of an archive")
        void shouldBlockPhysicalRemoval_forPersistedArchive() {
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();

            assertThatThrownBy(() -> {
                entityManager.remove(archive);
                entityManager.flush();
            }).isInstanceOf(UnsupportedOperationException.class)
                    .hasMessageContaining("controlled tombstone workflow");
        }
    }

    @Nested
    @DisplayName("Controlled deletion")
    class ControlledDeletion {

        /**
         * The load-bearing case. {@code OutboundEmailArchiveArtifact} carries a
         * {@code @PrePersist @PreUpdate} callback that mutates {@code lastUpdateDate},
         * while {@code OutboundEmailArchiveDeletion} adds a {@code @PreUpdate} that
         * throws. If Hibernate ever issued an UPDATE for a just-inserted tombstone,
         * every controlled deletion would fail at commit rather than at the call.
         */
        @Test
        @Tag("create")
        @DisplayName("should persist a tombstone without tripping the immutability callback")
        void shouldPersistTombstone_withoutTrippingImmutabilityCallback() {
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();

            archive.releaseLegalHold(PROVIDER_NO);
            archive.markDeleted(PROVIDER_NO, "Patient requested cleanup");
            OutboundEmailArchiveDeletion deletion =
                    OutboundEmailArchiveDeletion.fromArchive(archive, PROVIDER_NO, "Patient requested cleanup");

            outboundEmailArchiveDao.merge(archive);
            outboundEmailArchiveDeletionDao.persist(deletion);
            entityManager.flush();
            entityManager.clear();

            OutboundEmailArchive reloadedArchive = outboundEmailArchiveDao.find(archive.getId());
            assertThat(reloadedArchive.isDeleted()).isTrue();
            assertThat(reloadedArchive.getDeletedByProviderNo()).isEqualTo(PROVIDER_NO);
            assertThat(reloadedArchive.getDeleteReason()).isEqualTo("Patient requested cleanup");

            OutboundEmailArchiveDeletion reloadedDeletion = outboundEmailArchiveDeletionDao.find(deletion.getId());
            assertThat(reloadedDeletion.getSha256Hash()).isEqualTo(ARTIFACT_HASH);
            assertThat(reloadedDeletion.getByteSize()).isEqualTo(2048L);
            assertThat(reloadedDeletion.getDeletedAt()).isNotNull();
        }

        @Test
        @Tag("update")
        @DisplayName("should reject mutation of a persisted tombstone")
        void shouldRejectMutation_ofPersistedTombstone() {
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();

            archive.releaseLegalHold(PROVIDER_NO);
            archive.markDeleted(PROVIDER_NO, "Patient requested cleanup");
            OutboundEmailArchiveDeletion deletion =
                    OutboundEmailArchiveDeletion.fromArchive(archive, PROVIDER_NO, "Patient requested cleanup");
            outboundEmailArchiveDeletionDao.persist(deletion);
            entityManager.flush();

            deletion.setDeleteReason("Rewritten reason");

            assertThatThrownBy(() -> entityManager.flush())
                    .isInstanceOf(UnsupportedOperationException.class)
                    .hasMessageContaining("immutable");
        }
    }

    @Nested
    @DisplayName("Legal hold events")
    class LegalHoldEvents {

        @Test
        @Tag("create")
        @DisplayName("should record place and release events in reverse chronological order")
        void shouldRecordLegalHoldEvents_inReverseChronologicalOrder() {
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();

            archive.releaseLegalHold(PROVIDER_NO);
            outboundEmailArchiveLegalHoldEventDao.persist(OutboundEmailArchiveLegalHoldEvent.of(
                    archive, OutboundEmailArchiveLegalHoldEvent.ACTION_RELEASED, PROVIDER_NO, "Counsel authorised release"));

            archive.placeLegalHold(PROVIDER_NO);
            outboundEmailArchiveLegalHoldEventDao.persist(OutboundEmailArchiveLegalHoldEvent.of(
                    archive, OutboundEmailArchiveLegalHoldEvent.ACTION_PLACED, PROVIDER_NO, "Litigation reopened"));

            entityManager.flush();
            entityManager.clear();

            List<OutboundEmailArchiveLegalHoldEvent> events =
                    outboundEmailArchiveLegalHoldEventDao.findByArchiveId(archive.getId());

            assertThat(events).hasSize(2);
            // Secondary id ordering keeps the pair stable even though both rows land in
            // the same DATETIME second.
            assertThat(events).extracting(OutboundEmailArchiveLegalHoldEvent::getAction)
                    .containsExactly(
                            OutboundEmailArchiveLegalHoldEvent.ACTION_PLACED,
                            OutboundEmailArchiveLegalHoldEvent.ACTION_RELEASED);
            assertThat(events).allSatisfy(event -> {
                assertThat(event.getProviderNo()).isEqualTo(PROVIDER_NO);
                assertThat(event.getEventAt()).isNotNull();
            });
        }

        @Test
        @Tag("update")
        @DisplayName("should reject mutation of a persisted legal hold event")
        void shouldRejectMutation_ofPersistedLegalHoldEvent() {
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();

            archive.releaseLegalHold(PROVIDER_NO);
            OutboundEmailArchiveLegalHoldEvent event = OutboundEmailArchiveLegalHoldEvent.of(
                    archive, OutboundEmailArchiveLegalHoldEvent.ACTION_RELEASED, PROVIDER_NO, "Counsel authorised release");
            outboundEmailArchiveLegalHoldEventDao.persist(event);
            entityManager.flush();

            event.setReason("Rewritten justification");

            assertThatThrownBy(() -> entityManager.flush())
                    .isInstanceOf(UnsupportedOperationException.class)
                    .hasMessageContaining("immutable");
        }

        @Test
        @Tag("create")
        @DisplayName("should reject a legal hold event for an archive that does not exist")
        void shouldRejectLegalHoldEvent_whenArchiveDoesNotExist() {
            // Pins that the archive association is foreign-key constrained. The mapping
            // previously declared ConstraintMode.NO_CONSTRAINT, under which this orphaned
            // audit row inserted cleanly and only failed much later, on the first attempt
            // to dereference the missing archive.
            OutboundEmailArchive missing =
                    entityManager.getReference(OutboundEmailArchive.class, 999_999);
            OutboundEmailArchiveLegalHoldEvent orphan = OutboundEmailArchiveLegalHoldEvent.of(
                    missing, OutboundEmailArchiveLegalHoldEvent.ACTION_RELEASED, PROVIDER_NO, "orphan");

            assertThatThrownBy(() -> {
                outboundEmailArchiveLegalHoldEventDao.persist(orphan);
                entityManager.flush();
            })
                    .isInstanceOf(ConstraintViolationException.class)
                    // Named explicitly so a NOT NULL violation cannot pass this test by
                    // accident -- it is the archive foreign key that must reject the row.
                    .hasMessageContaining("FOREIGN KEY");
        }

        @Test
        @Tag("read")
        @DisplayName("should not refresh an already-managed archive when locking it for update")
        void shouldNotRefreshManagedArchive_whenLockedAfterAnEarlierRead() {
            // Pins the trap that findForUpdate's Javadoc warns about. A JPA query does not
            // refresh an entity that is already managed, so a plain find() earlier in the
            // same transaction makes the locked read hand back the pre-lock copy. The row
            // lock is still taken, but legalHold/deleted are read from before it -- which
            // would let two concurrent releases both see legalHold = true and both succeed.
            //
            // This is why the service's pre-lock authorization check uses the scalar
            // findDemographicNoById instead of loading the archive. If someone
            // "simplifies" that back to find(), this test still passes but
            // OutboundEmailArchiveServiceImpl silently loses its concurrency guard --
            // hence the explicit warning on both Javadocs.
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();
            Integer id = archive.getId();
            entityManager.clear();

            OutboundEmailArchive managed = outboundEmailArchiveDao.find(id);
            assertThat(managed.isLegalHold()).isTrue();

            // Change the row underneath, bypassing the persistence context entirely.
            entityManager.createNativeQuery(
                            "UPDATE outboundEmailArchive SET legalHold = FALSE WHERE id = :id")
                    .setParameter("id", id)
                    .executeUpdate();

            OutboundEmailArchive locked = outboundEmailArchiveDao.findForUpdate(id);

            assertThat(locked).isSameAs(managed);
            assertThat(locked.isLegalHold())
                    .as("findForUpdate returned refreshed state; the stale-read trap this "
                            + "test documents is gone and the scalar pre-lock read in "
                            + "OutboundEmailArchiveServiceImpl may no longer be necessary")
                    .isTrue();
        }

        @Test
        @Tag("read")
        @DisplayName("should read an archive demographic without hydrating the archive")
        void shouldReadDemographicNo_withoutHydratingTheArchive() {
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);
            entityManager.flush();
            Integer id = archive.getId();
            entityManager.clear();

            Integer demographicNo = outboundEmailArchiveDao.findDemographicNoById(id);

            assertThat(demographicNo).isEqualTo(demographic.getDemographicNo());
            // The point of the scalar projection: the archive stays out of the persistence
            // context, so a following findForUpdate still hydrates under its lock.
            assertThat(entityManager.contains(archive)).isFalse();
            assertThat(outboundEmailArchiveDao.findDemographicNoById(999_999)).isNull();
        }
    }

    @Nested
    @DisplayName("Query methods")
    class QueryMethods {

        @Test
        @Tag("read")
        @DisplayName("should exclude archives before applying the generic document sync limit")
        void shouldExcludeArchives_beforeApplyingGenericDocumentSyncLimit() {
            OutboundEmailArchive archive = newArchive();
            outboundEmailArchiveDao.persist(archive);

            Document ordinaryDocument = new Document();
            ordinaryDocument.setDocfilename("ordinary-sync-document.txt");
            ordinaryDocument.setDocdesc("Ordinary synchronization document");
            ordinaryDocument.setDoctype("document");
            ordinaryDocument.setDoccreator(PROVIDER_NO);
            ordinaryDocument.setResponsible(PROVIDER_NO);
            ordinaryDocument.setContenttype("text/plain");
            ordinaryDocument.setStatus(Document.STATUS_ACTIVE);
            ordinaryDocument.setPublic1(0);
            ordinaryDocument.setObservationdate(new Date());
            ordinaryDocument.setContentdatetime(new Date());
            entityManager.persist(ordinaryDocument);
            entityManager.flush();

            Date archiveUpdate = new Date(1_700_000_000_000L);
            Date ordinaryUpdate = new Date(1_700_000_001_000L);
            entityManager.createQuery("""
                            UPDATE Document document SET document.updatedatetime = :updatedAt
                            WHERE document.documentNo = :documentNo
                            """)
                    .setParameter("updatedAt", archiveUpdate)
                    .setParameter("documentNo", document.getDocumentNo())
                    .executeUpdate();
            entityManager.createQuery("""
                            UPDATE Document document SET document.updatedatetime = :updatedAt
                            WHERE document.documentNo = :documentNo
                            """)
                    .setParameter("updatedAt", ordinaryUpdate)
                    .setParameter("documentNo", ordinaryDocument.getDocumentNo())
                    .executeUpdate();
            entityManager.clear();

            List<Document> results = documentDao.findByUpdateDate(new Date(0), 1);

            assertThat(results).extracting(Document::getDocumentNo)
                    .containsExactly(ordinaryDocument.getDocumentNo());
        }

        @Test
        @Tag("read")
        @DisplayName("should return archives for an email log newest first")
        void shouldReturnArchivesForEmailLog_newestFirst() {
            OutboundEmailArchive older = newArchive();
            older.setArchivedAt(new Date(1_700_000_000_000L));
            outboundEmailArchiveDao.persist(older);

            OutboundEmailArchive newer = newArchive();
            newer.setArchivedAt(new Date(1_800_000_000_000L));
            outboundEmailArchiveDao.persist(newer);
            entityManager.flush();

            List<OutboundEmailArchive> result = outboundEmailArchiveDao.findByEmailLogId(emailLog.getId());

            assertThat(result).extracting(OutboundEmailArchive::getId)
                    .containsExactly(newer.getId(), older.getId());
        }

        @Test
        @Tag("read")
        @DisplayName("should return archives for a demographic newest first")
        void shouldReturnArchivesForDemographic_newestFirst() {
            OutboundEmailArchive older = newArchive();
            older.setArchivedAt(new Date(1_700_000_000_000L));
            outboundEmailArchiveDao.persist(older);

            OutboundEmailArchive newer = newArchive();
            newer.setArchivedAt(new Date(1_800_000_000_000L));
            outboundEmailArchiveDao.persist(newer);
            entityManager.flush();

            List<OutboundEmailArchive> result =
                    outboundEmailArchiveDao.findByDemographicNo(demographic.getDemographicNo());

            assertThat(result).extracting(OutboundEmailArchive::getId)
                    .containsExactly(newer.getId(), older.getId());
        }
    }
}
