-- Test lookup tables for reference data
-- These tables are referenced by formulas in HBM mappings but don't have entity classes

-- Gender lookup table (Hibernate may auto-create this due to formula in Demographic.hbm.xml)
CREATE TABLE IF NOT EXISTS lst_gender (
    code char(1) NOT NULL PRIMARY KEY,
    description varchar(80),
    isactive tinyint(1) DEFAULT 1,
    displayorder int(10)
);

-- Use MERGE for H2 to handle existing data gracefully
MERGE INTO lst_gender (code, description, isactive, displayorder) KEY(code) VALUES
('M', 'Male', 1, 1),
('F', 'Female', 1, 2),
('X', 'Non-binary', 1, 3),
('U', 'Unknown', 1, 4),
('O', 'Other', 1, 5);

-- Demographic merged table (for head record lookup)
CREATE TABLE IF NOT EXISTS demographic_merged (
    id int AUTO_INCREMENT PRIMARY KEY,
    demographic_no int NOT NULL,
    merged_to int,
    deleted tinyint(1) DEFAULT 0,
    created_date datetime DEFAULT CURRENT_TIMESTAMP
);

-- Health safety table (for alert count)
CREATE TABLE IF NOT EXISTS health_safety (
    id int AUTO_INCREMENT PRIMARY KEY,
    demographic_no int NOT NULL,
    description text,
    created_date datetime DEFAULT CURRENT_TIMESTAMP
);

-- Service restriction lookup table (for ProgramClientRestriction formula)
CREATE TABLE IF NOT EXISTS lst_service_restriction (
    id varchar(36) NOT NULL PRIMARY KEY,
    description varchar(255),
    isactive tinyint(1) DEFAULT 1
);

-- Joint admissions table (for ProgramQueue formula)
CREATE TABLE IF NOT EXISTS joint_admissions (
    id int AUTO_INCREMENT PRIMARY KEY,
    client_id int NOT NULL,
    head_client_id int,
    archived tinyint(1) DEFAULT 0,
    created_date datetime DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================================
-- Reference data for healthcare domain integration tests
-- =====================================================================

-- Appointment status reference data
-- Table name must match @Table(name = "appointment_status") in AppointmentStatus.java
-- CREATE TABLE IF NOT EXISTS as safety net in case entity scan doesn't auto-create
CREATE TABLE IF NOT EXISTS appointment_status (
    id int AUTO_INCREMENT PRIMARY KEY,
    status varchar(10),
    description varchar(80),
    active int DEFAULT 1,
    editable int DEFAULT 1,
    icon varchar(50) DEFAULT '',
    color varchar(20) DEFAULT '',
    short_letters varchar(10),
    short_letter_colour varchar(20)
);

MERGE INTO appointment_status (status, description, active, editable, icon, color) KEY(status) VALUES
('t', 'Confirmed', 1, 1, '', ''),
('N', 'No Show', 1, 1, '', ''),
('C', 'Cancelled', 1, 1, '', ''),
('H', 'Here', 1, 1, '', '');

-- Schedule template codes reference data
-- Table name matches @Table(name = "scheduletemplatecode") in ScheduleTemplateCode.java
CREATE TABLE IF NOT EXISTS scheduletemplatecode (
    id int AUTO_INCREMENT PRIMARY KEY,
    code char(1),
    description varchar(80),
    duration varchar(10),
    color varchar(20),
    confirm varchar(10) DEFAULT '',
    bookinglimit int DEFAULT 1
);

MERGE INTO scheduletemplatecode (id, code, description, duration, color, confirm, bookinglimit) KEY(id) VALUES
(1, 'A', 'Available', '15', '00FF00', '', 1),
(2, 'P', 'Primary Care', '15', '0000FF', '', 1),
(3, '-', 'Not Available', '15', 'FF0000', '', 0);

-- =====================================================================
-- Tables referenced by HBM formula columns
-- These tables are needed because formula subselects execute even when
-- the formula columns are not directly queried.
-- =====================================================================

-- casemgmt_note_ext table (used by CaseManagementNoteExt entity)
-- hbm2ddl may not auto-create this if the HBM mapping is only in persistence.xml
CREATE TABLE IF NOT EXISTS casemgmt_note_ext (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT,
    key_val VARCHAR(255),
    "value" VARCHAR(255),
    date_value TIMESTAMP
);

-- secRole table (referenced by casemgmt_note.hbm.xml formula:
-- "select r.role_name from secRole r where r.role_no = reporter_caisi_role")
CREATE TABLE IF NOT EXISTS secRole (
    role_no INT AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(100),
    description VARCHAR(255)
);

-- program table (referenced by casemgmt_note.hbm.xml formula:
-- "select p.name from program p where p.id = program_no")
CREATE TABLE IF NOT EXISTS program (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(50),
    facilityId INT,
    description VARCHAR(255)
);

-- lst_field_category table (referenced by LookupTableDefValue.hbm.xml formula:
-- "select t.description from lst_field_category t where t.id=moduleId")
CREATE TABLE IF NOT EXISTS lst_field_category (
    id VARCHAR(10) NOT NULL PRIMARY KEY,
    description VARCHAR(255)
);

-- app_lookuptable table (mapped by LookupTableDefValue.hbm.xml)
-- Created here instead of via hbm2ddl because the HBM uses generator class="native"
-- on a String-typed ID, which is incompatible with H2 DDL generation.
CREATE TABLE IF NOT EXISTS app_lookuptable (
    tableId VARCHAR(20) NOT NULL PRIMARY KEY,
    table_name VARCHAR(255),
    description VARCHAR(255),
    activeyn BOOLEAN DEFAULT TRUE,
    readonly BOOLEAN DEFAULT FALSE,
    istree BOOLEAN DEFAULT FALSE,
    treecode_length INT DEFAULT 0,
    moduleid VARCHAR(10)
);

-- app_lookuptable_fields table (mapped by FieldDefValue.hbm.xml)
CREATE TABLE IF NOT EXISTS app_lookuptable_fields (
    tableid VARCHAR(20) NOT NULL,
    fieldname VARCHAR(100) NOT NULL,
    fielddesc VARCHAR(255),
    fieldtype VARCHAR(10),
    edityn BOOLEAN DEFAULT TRUE,
    lookuptable VARCHAR(20),
    fieldsql VARCHAR(255),
    fieldindex INT,
    autoyn BOOLEAN DEFAULT FALSE,
    uniqueyn BOOLEAN DEFAULT FALSE,
    genericidx INT,
    fieldlength INT,
    PRIMARY KEY (tableid, fieldname)
);
