# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 CARLOS Contributors
# Distribution-specific JDBC defaults, intentionally empty in the ordinary WAR.
# Debian supplies its MariaDB metadata default in this lower-priority resource.
# Values in carlos.properties (including an explicit empty value) take precedence.
