# English fallback labels for the legacy REST UI endpoints.
# Copyright (c) 2026 CARLOS Contributors. GPL version 2 or later.
navbar.newOscarDemoMessages=Patient messages
navbar.newOscarMessages=Messages
navbar.menu.newPatient=New patient
navbar.menu.advancedSearch=Advanced search
navbar.menu.schedule=Schedule
navbar.menu.inbox=Inbox
navbar.menu.consults=Consultations
navbar.menu.consultRequests=Consultation requests
navbar.menu.consultResponses=Consultation responses
navbar.menu.billing=Billing
navbar.menu.tickler=Ticklers
navbar.menu.admin=Administration
navbar.menu.more=More
navbar.menu.reports=Reports
navbar.menu.documents=Documents
navbar.menu.settings=Settings
navbar.menu.support=Support
navbar.menu.help=Help
navbar.menu.dashboard=Dashboard
patientList.tab.appts=Appointments
patientList.tab.recent=Recent patients
patientList.tab.patientSets=Patient sets
prevention.currentrules.propertyfile=Configured prevention rules file
prevention.currentrules.resourceStorage=Stored prevention rules:
prevention.currentrules.default=Default prevention rules
lucodes.currentrules.propertyfile=Configured limited-use codes file
lucodes.currentrules.resourceStorage=Stored limited-use codes:
lucodes.currentrules.default=Default limited-use codes
