#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat Apr 04 04:16:49 UTC 2026
maven-metadata-local_repo.xml.error=
maven-metadata-central.xml.lastUpdated=1775276209221
maven-metadata-local_repo.xml.lastUpdated=1775276209220
maven-metadata-jitpack.io.xml/@default-jitpack.io-https\://jitpack.io/.lastUpdated=1775276209221
maven-metadata-jitpack.io.xml.error=Could not transfer metadata net.java.dev.jna\:jna/maven-metadata.xml from/to jitpack.io (https\://jitpack.io)\: jitpack.io\: No address associated with hostname
