--- .devcontainer/development/Dockerfile
+++ .devcontainer/development/Dockerfile
@@ -21,6 +21,7 @@
 ARG DOCS_PATH="/var/lib"
 ARG OSCAR_DOCUMENT="\${DOCS_PATH}/OscarDocument"

+RUN mkdir -p /var/lib/OscarDocument
 ARG DOCS_DEST="/var/lib/OscarDocument/oscar/document"
 ARG INCOMING_DOCS_DEST="/var/lib/OscarDocument/oscar/incomingdocs"
 ARG EFORM_IMAGES_DEST="/var/lib/OscarDocument/oscar/eform/images"
