CREATE TABLE IF NOT EXISTS sms_transaction (
  id BIGINT NOT NULL AUTO_INCREMENT,
  direction VARCHAR(16) NOT NULL,
  provider_type VARCHAR(16) NOT NULL,
  transaction_type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  demographic_no INT NULL,
  requested_by_provider_no VARCHAR(16) NULL,
  requested_by_security_no INT NULL,
  appointment_no INT NULL,
  from_phone_number VARCHAR(32) NULL,
  to_phone_number VARCHAR(32) NULL,
  provider_message_id VARCHAR(128) NULL,
  message_body TEXT NULL,
  message_body_sha256 CHAR(64) NOT NULL,
  message_body_length INT NOT NULL DEFAULT 0,
  consent_reason_code VARCHAR(64) NULL,
  error_code VARCHAR(64) NULL,
  error_message VARCHAR(1024) NULL,
  provider_metadata TEXT NULL,
  attempt_count INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  next_attempt_at DATETIME NULL,
  last_attempt_at DATETIME NULL,
  sent_at DATETIME NULL,
  delivered_at DATETIME NULL,
  received_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY sms_transaction_demographic_created_idx (demographic_no, created_at),
  KEY sms_transaction_provider_message_idx (provider_type, provider_message_id),
  KEY sms_transaction_queue_idx (status, provider_type, next_attempt_at),
  KEY sms_transaction_status_updated_idx (status, updated_at)
);
