-- V1.0.2 shipped the entire Ontario service catalogue inactive. '02' is also
-- the application's deliberate-disable value, so never reactivate arbitrary
-- inactive services. Repair only the exact untouched seed, and only before
-- clinical patients exist (the public FAKE demo dataset is also eligible).
-- Configured catalogues and databases holding real patients are left intact;
-- administrators can enable their intended services in consultation settings.
CREATE TEMPORARY TABLE carlos_on_service_seed_repair (
    serviceId INT PRIMARY KEY,
    serviceDesc VARCHAR(255) NOT NULL,
    active VARCHAR(2) NOT NULL
);
INSERT INTO carlos_on_service_seed_repair VALUES
(1,'Adolescent Medicine, Pediatrics','02'),
(2,'Anatomical Pathology','02'),
(3,'Anatomical Pathology, Forensic Pathology','02'),
(4,'Anatomical Pathology, General Pathology','02'),
(5,'Anatomical Pathology, General Pathology, Dermatology','02'),
(6,'Anatomical Pathology, Hematological Pathology','02'),
(7,'Anatomical Pathology, Neuropathology','02'),
(8,'Anesthesiology','02'),
(9,'Anesthesiology, Critical Care Medicine','02'),
(10,'Anesthesiology, Critical Care Medicine, Palliative Medicine','02'),
(11,'Anesthesiology, Internal Medicine','02'),
(12,'Anesthesiology, Pain Medicine','02'),
(13,'Cardiac Surgery','02'),
(14,'Cardiac Surgery, General Surgery','02'),
(15,'Cardiac Surgery, Thoracic Surgery','02'),
(16,'Cardiology','02'),
(17,'Cardiology, Internal Medicine','02'),
(18,'Cardiology, Pediatrics','02'),
(19,'Cardiothoracic Surgery','02'),
(20,'Cardiovascular and Thoracic Surgery','02'),
(21,'Cardiovascular and Thoracic Surgery, General Surgery','02'),
(22,'Child and Adolescent Psychiatry, Psychiatry','02'),
(23,'Clinical Immunology and Allergy, Internal Medicine','02'),
(24,'Clinician Investigator Program, Internal Medicine, Critical Care Medicine, Infectious Diseases','02'),
(25,'Clinician Investigator Program, Medical Biochemistry','02'),
(26,'Clinician Investigator Program, Pediatrics, Pediatric Hematology/Oncology','02'),
(27,'Clinician Investigator Program, Plastic Surgery','02'),
(28,'Clinician Investigator Program, Radiation Oncology','02'),
(29,'Colorectal Surgery, General Surgery','02'),
(30,'Community Medicine','02'),
(31,'Community Medicine, Public Health and Preventive Medicine','02'),
(32,'Critical Care Medicine, Anesthesiology','02'),
(33,'Critical Care Medicine, Cardiac Surgery','02'),
(34,'Critical Care Medicine, Emergency Medicine','02'),
(35,'Critical Care Medicine, General Surgery','02'),
(36,'Critical Care Medicine, Infectious Diseases, Internal Medicine','02'),
(37,'Critical Care Medicine, Internal Medicine','02'),
(38,'Critical Care Medicine, Internal Medicine, Cardiology','02'),
(39,'Critical Care Medicine, Internal Medicine, Respirology','02'),
(40,'Critical Care Medicine, Nephrology, Internal Medicine','02'),
(41,'Critical Care Medicine, Pediatric Emergency Medicine, Pediatrics','02'),
(42,'Critical Care Medicine, Pediatrics','02'),
(43,'Critical Care Medicine, Respirology, Internal Medicine','02'),
(44,'Dermatology','02'),
(45,'Dermatology, Internal Medicine, Rheumatology','02'),
(46,'Dermatology, Pediatrics, Clinical Immunology and Allergy','02'),
(47,'Developmental Pediatrics','02'),
(48,'Developmental Pediatrics, Pediatrics','02'),
(49,'Diagnostic Radiology','02'),
(50,'Diagnostic Radiology, Diagnostic Radiology','02'),
(51,'Diagnostic Radiology, Neuroradiology','02'),
(52,'Diagnostic Radiology, Nuclear Medicine','02'),
(53,'Diagnostic Radiology, Pediatric Radiology','02'),
(54,'Diagnostic Radiology, Pediatrics','02'),
(55,'Emergency Medicine','02'),
(56,'Emergency Medicine, Anesthesiology','02'),
(57,'Emergency Medicine, Critical Care Medicine','02'),
(58,'Emergency Medicine, Internal Medicine','02'),
(59,'Emergency Medicine, Pediatric Emergency Medicine','02'),
(60,'Endocrinology and Metabolism','02'),
(61,'Endocrinology and Metabolism, Critical Care Medicine, Internal Medicine','02'),
(62,'Endocrinology and Metabolism, Internal Medicine','02'),
(63,'Endocrinology and Metabolism, Pediatrics','02'),
(64,'Family Medicine','02'),
(65,'Forensic Pathology, Anatomical Pathology','02'),
(66,'Forensic Psychiatry','02'),
(67,'Forensic Psychiatry, Psychiatry','02'),
(68,'Gastroenterology, Internal Medicine','02'),
(69,'Gastroenterology, Pediatrics','02'),
(70,'General Internal Medicine, Internal Medicine','02'),
(71,'General Internal Medicine, Internal Medicine, Critical Care Medicine','02'),
(72,'General Pathology','02'),
(73,'General Pathology, Anatomical Pathology','02'),
(74,'General Pathology, Forensic Pathology','02'),
(75,'General Pathology, Hematological Pathology','02'),
(76,'General Pathology, Medical Biochemistry','02'),
(77,'General Surgery','02'),
(78,'General Surgery, Cardiac Surgery','02'),
(79,'General Surgery, Cardiothoracic Surgery','02'),
(80,'General Surgery, Cardiovascular and Thoracic Surgery','02'),
(81,'General Surgery, Cardiovascular and Thoracic Surgery, Thoracic Surgery','02'),
(82,'General Surgery, Colorectal Surgery','02'),
(83,'General Surgery, Critical Care Medicine','02'),
(84,'General Surgery, General Surgical Oncology','02'),
(85,'General Surgery, Pediatric Surgery','02'),
(86,'General Surgery, Thoracic Surgery','02'),
(87,'General Surgery, Vascular Surgery','02'),
(88,'General Surgical Oncology, General Surgery','02'),
(89,'Geriatric Medicine, Internal Medicine','02'),
(90,'Geriatric Psychiatry, Psychiatry','02'),
(91,'Geriatric Psychiatry, Psychiatry, Forensic Psychiatry','02'),
(92,'Gynecologic Oncology, Obstetrics and Gynecology','02'),
(93,'Gynecologic Reproductive Endocrinology and Infertility, Obstetrics and Gynecology','02'),
(94,'Hematological Pathology','02'),
(95,'Hematological Pathology, Anatomical Pathology','02'),
(96,'Hematological Pathology, Hematology, Internal Medicine','02'),
(97,'Hematological Pathology, Internal Medicine','02'),
(98,'Hematology','02'),
(99,'Hematology, Internal Medicine','02'),
(100,'Hematology, Internal Medicine, Medical Oncology','02'),
(101,'Hematology, Medical Oncology, Internal Medicine','02'),
(102,'Hematology, Pediatrics','02'),
(103,'Infectious Diseases, Critical Care Medicine, Internal Medicine','02'),
(104,'Infectious Diseases, Internal Medicine','02'),
(105,'Infectious Diseases, Internal Medicine, Medical Microbiology','02'),
(106,'Infectious Diseases, Medical Microbiology, Internal Medicine','02'),
(107,'Infectious Diseases, Pediatrics','02'),
(108,'Internal Medicine','02'),
(109,'Internal Medicine, Cardiology','02'),
(110,'Internal Medicine, Clinical Immunology and Allergy','02'),
(111,'Internal Medicine, Critical Care Medicine','02'),
(112,'Internal Medicine, Critical Care Medicine, Clinical Pharmacology and Toxicology','02'),
(113,'Internal Medicine, Critical Care Medicine, Respirology','02'),
(114,'Internal Medicine, Dermatology','02'),
(115,'Internal Medicine, Diagnostic Radiology','02'),
(116,'Internal Medicine, Emergency Medicine','02'),
(117,'Internal Medicine, Endocrinology and Metabolism','02'),
(118,'Internal Medicine, Gastroenterology','02'),
(119,'Internal Medicine, General Internal Medicine','02'),
(120,'Internal Medicine, Geriatric Medicine','02'),
(121,'Internal Medicine, Hematology','02'),
(122,'Internal Medicine, Hematology, Medical Oncology','02'),
(123,'Internal Medicine, Infectious Diseases','02'),
(124,'Internal Medicine, Infectious Diseases, Critical Care Medicine','02'),
(125,'Internal Medicine, Medical Biochemistry','02'),
(126,'Internal Medicine, Medical Genetics','02'),
(127,'Internal Medicine, Medical Microbiology','02'),
(128,'Internal Medicine, Medical Microbiology, Infectious Diseases','02'),
(129,'Internal Medicine, Medical Oncology','02'),
(130,'Internal Medicine, Medical Oncology, Hematology','02'),
(131,'Internal Medicine, Nephrology','02'),
(132,'Internal Medicine, Nephrology, Critical Care Medicine','02'),
(133,'Internal Medicine, Neurology','02'),
(134,'Internal Medicine, Nuclear Medicine','02'),
(135,'Internal Medicine, Occupational Medicine, Respirology','02'),
(136,'Internal Medicine, Ophthalmology','02'),
(137,'Internal Medicine, Pain Medicine','02'),
(138,'Internal Medicine, Palliative Medicine','02'),
(139,'Internal Medicine, Palliative Medicine, Nephrology','02'),
(140,'Internal Medicine, Public Health and Preventive Medicine','02'),
(141,'Internal Medicine, Radiation Oncology','02'),
(142,'Internal Medicine, Respirology','02'),
(143,'Internal Medicine, Respirology, Critical Care Medicine','02'),
(144,'Internal Medicine, Rheumatology','02'),
(145,'Internal Medicine, Rheumatology, Clinical Immunology and Allergy','02'),
(146,'Interventional Radiology, Diagnostic Radiology','02'),
(147,'Maternal','02'),
(148,'Medical Biochemistry','02'),
(149,'Medical Biochemistry, Internal Medicine','02'),
(150,'Medical Genetics','02'),
(151,'Medical Genetics and Genomics','02'),
(152,'Medical Genetics, Pediatrics','02'),
(153,'Medical Microbiology','02'),
(154,'Medical Microbiology, Internal Medicine, Infectious Diseases','02'),
(155,'Medical Oncology','02'),
(156,'Medical Oncology, Hematology, Internal Medicine','02'),
(157,'Medical Oncology, Internal Medicine','02'),
(158,'Medical Oncology, Internal Medicine, Hematology','02'),
(159,'Neonatal','02'),
(160,'Nephrology','02'),
(161,'Nephrology, Critical Care Medicine, Internal Medicine','02'),
(162,'Nephrology, Internal Medicine','02'),
(163,'Nephrology, Pediatrics','02'),
(164,'Neurology','02'),
(165,'Neurology, Clinician Investigator Program','02'),
(166,'Neurology, Critical Care Medicine','02'),
(167,'Neurology, Emergency Medicine','02'),
(168,'Neurology, Internal Medicine','02'),
(169,'Neurology, Neuropathology','02'),
(170,'Neurology, Pediatrics','02'),
(171,'Neurology, Psychiatry','02'),
(172,'Neuropathology','02'),
(173,'Neuropathology, Anatomical Pathology','02'),
(174,'Neuroradiology, Diagnostic Radiology','02'),
(175,'Neurosurgery','02'),
(176,'Nuclear Medicine','02'),
(177,'Nuclear Medicine, Diagnostic Radiology','02'),
(178,'Nuclear Medicine, Radiation Oncology','02'),
(179,'Obstetrics and Gynecology','02'),
(180,'Obstetrics and Gynecology, Gynecologic Oncology','02'),
(181,'Obstetrics and Gynecology, Gynecologic Reproductive Endocrinology and Infertility','02'),
(182,'Obstetrics and Gynecology, Maternal','02'),
(183,'Occupational Medicine','02'),
(184,'Occupational Medicine, Community Medicine','02'),
(185,'Ophthalmology','02'),
(186,'Orthopedic Surgery','02'),
(187,'Orthopedic Surgery, Pain Medicine','02'),
(188,'Otolaryngology','02'),
(189,'Pain Medicine, Anesthesiology','02'),
(190,'Pain Medicine, Physical Medicine and Rehabilitation','02'),
(191,'Palliative Medicine','02'),
(192,'Palliative Medicine, Pediatrics','02'),
(193,'Palliative Medicine, Radiation Oncology','02'),
(194,'Pediatric Cardiology, Pediatrics','02'),
(195,'Pediatric Emergency Medicine, Emergency Medicine','02'),
(196,'Pediatric Emergency Medicine, Pediatrics','02'),
(197,'Pediatric Hematology/Oncology, Pediatrics','02'),
(198,'Pediatric Surgery, General Surgery','02'),
(199,'Pediatrics','02'),
(200,'Pediatrics, Adolescent Medicine','02'),
(201,'Pediatrics, Cardiology','02'),
(202,'Pediatrics, Clinical Immunology and Allergy','02'),
(203,'Pediatrics, Community Medicine','02'),
(204,'Pediatrics, Critical Care Medicine','02'),
(205,'Pediatrics, Critical Care Medicine, Anesthesiology','02'),
(206,'Pediatrics, Critical Care Medicine, Infectious Diseases','02'),
(207,'Pediatrics, Dermatology','02'),
(208,'Pediatrics, Developmental Pediatrics','02'),
(209,'Pediatrics, Endocrinology and Metabolism','02'),
(210,'Pediatrics, Gastroenterology','02'),
(211,'Pediatrics, Hematology','02'),
(212,'Pediatrics, Infectious Diseases','02'),
(213,'Pediatrics, Infectious Diseases, Medical Microbiology','02'),
(214,'Pediatrics, Medical Genetics','02'),
(215,'Pediatrics, Medical Microbiology','02'),
(216,'Pediatrics, Medical Oncology, Hematology','02'),
(217,'Pediatrics, Neonatal','02'),
(218,'Pediatrics, Nephrology','02'),
(219,'Pediatrics, Neurology','02'),
(220,'Pediatrics, Orthopedic Surgery','02'),
(221,'Pediatrics, Otolaryngology','02'),
(222,'Pediatrics, Pediatric Cardiology','02'),
(223,'Pediatrics, Pediatric Emergency Medicine','02'),
(224,'Pediatrics, Pediatric Hematology/Oncology','02'),
(225,'Pediatrics, Respirology','02'),
(226,'Pediatrics, Rheumatology','02'),
(227,'Physical Medicine and Rehabilitation','02'),
(228,'Physical Medicine and Rehabilitation, Internal Medicine','02'),
(229,'Physical Medicine and Rehabilitation, Pain Medicine','02'),
(230,'Plastic Surgery','02'),
(231,'Psychiatry','02'),
(232,'Psychiatry, Child and Adolescent Psychiatry','02'),
(233,'Psychiatry, Community Medicine','02'),
(234,'Psychiatry, Forensic Psychiatry','02'),
(235,'Psychiatry, Forensic Psychiatry, Child and Adolescent Psychiatry','02'),
(236,'Psychiatry, Geriatric Psychiatry','02'),
(237,'Psychiatry, Internal Medicine','02'),
(238,'Psychiatry, Neurology','02'),
(239,'Psychiatry, Nuclear Medicine','02'),
(240,'Psychiatry, Pain Medicine','02'),
(241,'Public Health and Preventive Medicine','02'),
(242,'Public Health and Preventive Medicine, Community Medicine','02'),
(243,'Radiation Oncology','02'),
(244,'Respirology, Critical Care Medicine, Internal Medicine','02'),
(245,'Respirology, Internal Medicine','02'),
(246,'Respirology, Pediatrics','02'),
(247,'Rheumatology','02'),
(248,'Rheumatology, Clinician Investigator Program, Internal Medicine','02'),
(249,'Rheumatology, Internal Medicine','02'),
(250,'Rheumatology, Pediatrics','02'),
(251,'Thoracic Surgery, Cardiac Surgery','02'),
(252,'Thoracic Surgery, Critical Care Medicine, General Surgery','02'),
(253,'Thoracic Surgery, General Surgery','02'),
(254,'Thoracic Surgery, General Surgery, Cardiac Surgery','02'),
(255,'Urology','02'),
(256,'Vascular Surgery','02'),
(257,'Vascular Surgery, General Surgery','02');
SET @carlos_repair_on_services = (
    (SELECT COUNT(*) FROM consultationServices) = 257
    AND (SELECT COUNT(*) FROM consultationServices c
         JOIN carlos_on_service_seed_repair seed ON c.serviceId = seed.serviceId
         WHERE BINARY c.serviceDesc = BINARY seed.serviceDesc AND c.active = '02') = 257
    AND NOT EXISTS (SELECT 1 FROM demographic
                    WHERE last_name IS NULL OR first_name IS NULL
                       OR last_name NOT LIKE 'FAKE-%' OR first_name NOT LIKE 'FAKE-%')
);
UPDATE consultationServices SET active = '1' WHERE @carlos_repair_on_services = 1;
DROP TEMPORARY TABLE carlos_on_service_seed_repair;
SET @carlos_repair_on_services = NULL;
