# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 CARLOS Contributors
# Package-owned MariaDB default. Operator carlos.properties takes precedence.
# An explicit URL option or driver connection property also retains precedence.
# Keep Hibernate metadata enabled; use Connector/J's SHOW-based metadata instead
# of its MySQL-only INFORMATION_SCHEMA.KEYWORDS.RESERVED query.
db_default_use_information_schema=false
