package DiabetesHCHDL;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.util.MeasurementDSHelper;

rule "HCHDL 1"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() >= 4.0 )
        eval( m.getDataAsDouble() < 5.0 )
    then
        m.log("HCHDL 1 RULES IS GETTING RUN");
        m.setIndicationColor("HIGH");
end

rule "HCHDL 2"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() >= 5.0 )
    then
        m.log("HCHDL 2 RULES IS GETTING RUN");
        m.setIndicationColor("HIGH 1");
end
