package DiabetesA1C;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.util.MeasurementDSHelper;

rule "A1C"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() >= 7 )
    then
        m.log("A1C RULES IS GETTING RUN");
        m.setIndicationColor("HIGH");
end

rule "A1C2"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() <= 2 )
        eval( m.getDataAsDouble() >= 0.07 )
    then
        m.log("A1C RULES IS GETTING RUN");
        m.setIndicationColor("HIGH");
end
