package DiabetesBMI;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.util.MeasurementDSHelper;

rule "BMI 1"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() >= 25.0 )
        eval( m.getDataAsDouble() < 30 )
    then
        m.log("BMI RULES IS GETTING RUN");
        m.setIndicationColor("HIGH");
end

rule "BMI 2"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() > 30 )
    then
        m.log("BMI RULES IS GETTING RUN");
        m.setIndicationColor("HIGH 1");
end

rule "BMI 3"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() < 18.5 )
    then
        m.log("BMI RULES IS GETTING RUN");
        m.setIndicationColor("LOW");
end
