package DiabetesACR;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.util.MeasurementDSHelper;

rule "ACR 1"
    when
        m : MeasurementDSHelper()
        eval( m.isMale() == true )
        eval( m.getDataAsDouble() >= 2.0 )
    then
        m.log("ACR RULES IS GETTING RUN");
        m.setIndicationColor("HIGH");
end

rule "ACR 2"
    when
        m : MeasurementDSHelper()
        eval( m.isFemale() == true )
        eval( m.getDataAsDouble() >= 2.0 )
    then
        m.log("ACR RULES IS GETTING RUN");
        m.setIndicationColor("HIGH");
end
