package DiabetesLDL;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.util.MeasurementDSHelper;

rule "LDL 1"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() >= 2.0 )
        eval( m.getDataAsDouble() < 3.5 )
    then
        m.log("LDL 1 RULES IS GETTING RUN");
        m.setIndicationColor("HIGH");
end

rule "LDL 2"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() >= 3.5 )
    then
        m.log("LDL 2 RULES IS GETTING RUN");
        m.setIndicationColor("HIGH 1");
end
