package INR;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.util.MeasurementDSHelper;

rule "INR 1"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() < 2 )
    then
        m.log("INR RULES IS GETTING RUN");
        m.setIndicationColor("LOW");
end

rule "INR 2"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() >= 4 )
        eval( m.getDataAsDouble() < 5 )
    then
        m.log("INR RULES IS GETTING RUN");
        m.setIndicationColor("HIGH");
end

rule "INR 3"
    when
        m : MeasurementDSHelper()
        eval( m.getDataAsDouble() >= 5 )
    then
        m.log("INR RULES IS GETTING RUN");
        m.setIndicationColor("HIGH 1");
end
