package ReportA1C;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.util.MeasurementDSHelper;

rule "BPo130"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("BP") == true )
        eval( m.getNumberFromSplit("/",0) > 130 )
        eval( m.getNumberFromSplit("/",1) > 80 )
    then
        m.log("BPo130 RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(true);
end
