package oscar.oscarEncounter.oscarMeasurements.flowsheets.decisionSupport;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.util.MeasurementDSHelper;

//  Copyright (c) 2026 CARLOS Contributors. All Rights Reserved.
//
//  This software is published under the GPL GNU General Public License.
//  This program is free software; you can redistribute it and/or
//  modify it under the terms of the GNU General Public License
//  as published by the Free Software Foundation; either version 2
//  of the License, or (at your option) any later version.
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details. You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//
//  Maintained by the CARLOS EMR Project.
//  https://github.com/carlos-emr/carlos
//
//  Modifications by CARLOS Contributors, 2026.

rule "CD4"
    when
        m : MeasurementDSHelper()
        eval(m.setMeasurement("CD4") == true)
        eval(m.getDataAsDouble() < 200)
    then
        m.log("CD4 RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(true);
end
