package ReportCD4;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.util.MeasurementDSHelper;

rule "CD4"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("CD4") == true )
        eval( m.getDataAsDouble() >= 200 )
        eval( m.getDataAsDouble() <= 350 )
    then
        m.log("CD4 RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(true);
end
