package ReportA1C;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.util.MeasurementDSHelper;

rule "LDL"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("LDL") == true )
        eval( m.getDataAsDouble() < 2.0 )
    then
        m.log("LDL RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(true);
end

rule "LDL_1"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("LDL") == false )
    then
        m.log("LDL_1 RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(false);
end

rule "BP_3"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("BP") == false )
    then
        m.log("NO BP records");
        m.setInRange(false);
end

rule "BP"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("BP") == true )
        eval( m.getNumberFromSplit("/",0) < 131 )
        eval( m.isInRange() == true )
    then
        m.log("BP RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(true);
end

rule "BP_2"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("BP") == true )
        eval( m.getNumberFromSplit("/",0) >= 131 )
    then
        m.log("BP2 RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(false);
end

rule "A1C_3"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("A1C") == false )
    then
        m.log("No A1C Records");
        m.setInRange(false);
end

rule "A1C_1"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("A1C") == true )
        eval( m.getDataAsDouble() < 7.0 )
        eval( m.getDataAsDouble() >= 2.0 )
        eval( m.isInRange() == true )
    then
        m.log("A1C RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(true);
end

rule "A1C_1_2"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("A1C") == true )
        eval( m.getDataAsDouble() >= 7.0 )
    then
        m.log("A1C_1_2 RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(false);
end

rule "A1C_2"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("A1C") == true )
        eval( m.getDataAsDouble() < 0.07 )
        eval( m.isInRange() == true )
    then
        m.log("A1C RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(true);
end

rule "A1C_2_2"
    when
        m : MeasurementDSHelper()
        eval( m.setMeasurement("A1C") == true )
        eval( m.getDataAsDouble() >= 0.07 )
        eval( m.getDataAsDouble() <= 2.0 )
    then
        m.log("A1C RULES IS GETTING RUN"+m.getDataAsDouble());
        m.setInRange(false);
end
