/**
 * Copyright (c) 2026. CARLOS EMR Project. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
package io.github.carlos_emr.carlos.fax.connector;

import java.util.Date;

/**
 * Mutable Data Transfer Object (DTO) representing an incoming fax discovered by polling a {@link FaxConnector}.
 *
 * This class serves as a container for fax metadata obtained during inbox polling operations. Fields are populated
 * by {@link FaxConnector} implementations during the polling cycle and subsequently consumed by {@link FaxImporter}
 * for fax download and persistent storage operations.
 *
 * Typical workflow:
 * <ol>
 *   <li>FaxConnector polls an external fax system and discovers an incoming fax</li>
 *   <li>Connector populates FaxInboundResult fields with discovered metadata (reference ID, filename, page count, etc.)</li>
 *   <li>FaxImporter receives the populated FaxInboundResult and uses it to download the fax content</li>
 *   <li>FaxImporter stores the fax in the CARLOS EMR database with metadata from this DTO</li>
 * </ol>
 *
 * @see FaxConnector for fax polling and metadata extraction
 * @see FaxImporter for fax download and storage
 * @since 2026-02-09
 */
public class FaxInboundResult {

    private String externalReference;
    private String fileName;
    private String callerNumber;
    private int pageCount;
    private Date receivedDate;
    private String statusMessage;
    private boolean hasError;

    /**
     * Retrieves the external reference identifier for this fax from the remote system.
     *
     * This identifier uniquely identifies the fax in the external fax system and is used by the FaxConnector
     * to retrieve the actual fax content during download operations.
     *
     * @return String the unique external reference ID provided by the fax service, or null if not yet set
     */
    public String getExternalReference() {
        return externalReference;
    }

    /**
     * Sets the external reference identifier for this fax.
     *
     * @param externalReference String the unique external reference ID from the remote fax system
     */
    public void setExternalReference(String externalReference) {
        this.externalReference = externalReference;
    }

    /**
     * Retrieves the filename to be assigned to this fax when downloaded and stored.
     *
     * This filename is typically generated by the FaxConnector based on the remote system's naming
     * conventions and may include extensions such as .pdf, .tif, or other imaging formats.
     *
     * @return String the filename for storage, or null if not yet assigned
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the filename for this fax.
     *
     * @param fileName String the filename to use when storing this fax in the CARLOS EMR system
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * Retrieves the caller's phone number that sent this fax.
     *
     * This is the originating phone number from the fax transmission and may be used for
     * audit tracking, sender identification, and routing purposes within CARLOS EMR.
     *
     * @return String the caller's phone number, or null if not available from the fax system
     */
    public String getCallerNumber() {
        return callerNumber;
    }

    /**
     * Sets the caller's phone number.
     *
     * @param callerNumber String the originating phone number of the fax transmission
     */
    public void setCallerNumber(String callerNumber) {
        this.callerNumber = callerNumber;
    }

    /**
     * Retrieves the number of pages contained in this fax.
     *
     * This count is reported by the external fax system and indicates the total page count
     * of the incoming transmission.
     *
     * @return int the total page count of this fax, typically a value >= 1 for valid faxes
     */
    public int getPageCount() {
        return pageCount;
    }

    /**
     * Sets the page count for this fax.
     *
     * @param pageCount int the total number of pages in this fax transmission
     */
    public void setPageCount(int pageCount) {
        this.pageCount = pageCount;
    }

    /**
     * Retrieves the timestamp when this fax was received by the external system.
     *
     * This date captures when the fax transmission was completed and is used for audit trails
     * and chronological sorting of incoming faxes within CARLOS EMR.
     *
     * @return Date the reception timestamp of the fax, or null if not yet set
     */
    public Date getReceivedDate() {
        return receivedDate != null ? new Date(receivedDate.getTime()) : null;
    }

    /**
     * Sets the fax reception timestamp.
     *
     * @param receivedDate Date the date and time when this fax was received by the external system
     */
    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate != null ? new Date(receivedDate.getTime()) : null;
    }

    /**
     * Retrieves status or error message details from the fax polling operation.
     *
     * This message provides diagnostic information about the fax processing and may contain
     * error details, transmission warnings, or other status information from the external fax system.
     *
     * @return String the status or error message, or null if no message is available
     */
    public String getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the status or error message for this fax result.
     *
     * @param statusMessage String diagnostic message from the fax system indicating status or errors
     */
    public void setStatusMessage(String statusMessage) {
        this.statusMessage = statusMessage;
    }

    /**
     * Checks whether this fax result indicates an error condition.
     *
     * When true, indicates that the fax polling or discovery encountered an error that may affect
     * processing. Consult {@link #getStatusMessage()} for error details.
     *
     * @return boolean true if an error occurred during fax polling or transmission, false otherwise
     */
    public boolean isHasError() {
        return hasError;
    }

    /**
     * Sets the error flag for this fax result.
     *
     * @param hasError boolean true to indicate an error condition, false otherwise
     */
    public void setHasError(boolean hasError) {
        this.hasError = hasError;
    }
}
