package RhFlowSheet;

import io.github.carlos_emr.carlos.workflow.WorkFlowInfo;

rule "No EDD 0"
    when
        w : WorkFlowInfo()
        eval( w.getGestationAge() == -1 )
    then
        w.setColour("red");
end

rule "No Appt 1"
    when
        w : WorkFlowInfo()
        eval( w.isCurrentState("1") )
        eval( w.getGestationAge() < 24 )
    then
        w.setColour("#ccccff");
end

rule "No Appt 2"
    when
        w : WorkFlowInfo()
        eval( w.isCurrentState("1") )
        eval( w.getGestationAge() >= 24 )
    then
        w.setColour("orange");
end

rule "No Appt 3"
    when
        w : WorkFlowInfo()
        eval( w.isCurrentState("1") )
        eval( w.getGestationAge() >= 27 )
    then
        w.setColour("red");
end

rule "Appt Booked 4"
    when
        w : WorkFlowInfo()
        eval( w.isCurrentState("2") )
        eval( w.getGestationAge() <= 28 )
    then
        w.setColour("#ccccff");
end

rule "Appt Booked 5"
    when
        w : WorkFlowInfo()
        eval( w.isCurrentState("2") )
        eval( w.getGestationAge() > 28 )
    then
        w.setColour("red");
end

rule "Injection 28 6"
    when
        w : WorkFlowInfo()
        eval( w.isCurrentState("3") )
        eval( w.getGestationAge() > 42 )
    then
        w.setColour("red");
end

rule "Requires Another Injection 7"
    when
        w : WorkFlowInfo()
        eval( w.isCurrentState("4") )
    then
        w.setColour("orange");
end

rule "Missed Appt 8"
    when
        w : WorkFlowInfo()
        eval( w.isCurrentState("5") )
    then
        w.setColour("orange");
end

rule "Follow up Appt Booked 9"
    when
        w : WorkFlowInfo()
        eval( w.isCurrentState("6") )
    then
        w.setColour("yellow");
end
