# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 CARLOS Contributors
"""Unit tests for carlos_ctl.replication — the pure parts (renderers, token,
validation, state, processlist parsing). No root, no MariaDB, no network.

Run:  debian/tests/run-unit-tests.sh   (python3 -m unittest; pytest also works)
"""

import datetime as dt
import ipaddress
import json
import os
import sys
import tempfile
import unittest
from unittest import mock

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "assets"))

from carlos_ctl import replication as R  # noqa: E402


class ParseIp(unittest.TestCase):
    def test_accepts_private_v4_and_v6(self):
        self.assertEqual(str(R.parse_ip("10.0.0.5")), "10.0.0.5")
        self.assertEqual(str(R.parse_ip(" 192.168.1.20 ")), "192.168.1.20")
        self.assertEqual(str(R.parse_ip("fd00::5")), "fd00::5")

    def test_rejects_wildcard_loopback_hostname(self):
        for bad in ("0.0.0.0", "::", "127.0.0.1", "::1", "db.example.ca", "", "224.0.0.1",
                    "169.254.1.1"):
            with self.subTest(bad=bad), self.assertRaises(SystemExit):
                R.parse_ip(bad)

    def test_is_public(self):
        self.assertFalse(R.is_public(ipaddress.ip_address("10.0.0.5")))
        self.assertTrue(R.is_public(ipaddress.ip_address("203.0.113.9")) is R.is_public(
            ipaddress.ip_address("203.0.113.9")))  # deterministic
        self.assertTrue(R.is_public(ipaddress.ip_address("8.8.8.8")))


class LocalAddresses(unittest.TestCase):
    IP_J = json.dumps([
        {"ifname": "lo", "addr_info": [{"local": "127.0.0.1"}, {"local": "::1"}]},
        {"ifname": "wg0", "addr_info": [{"local": "10.0.0.5"}]},
        {"ifname": "eth0", "addr_info": []},
    ])

    def test_parses_ip_json(self):
        self.assertEqual(R.local_addresses(self.IP_J), ["127.0.0.1", "::1", "10.0.0.5"])

    def test_garbage_is_empty_not_a_crash(self):
        self.assertEqual(R.local_addresses("not json"), [])
        self.assertEqual(R.local_addresses(""), [])
        self.assertEqual(R.local_addresses("[{\"addr_info\": 5}]"), [])


class Renderers(unittest.TestCase):
    def test_account_name_folds_separators(self):
        self.assertEqual(R.account_name("10.0.0.6"), "repl_10_0_0_6")
        self.assertEqual(R.account_name("fd00::6"), "repl_fd00__6")
        self.assertLessEqual(len(R.account_name("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff")), 80)

    def test_primary_dropin_is_exact(self):
        text = R.render_primary_dropin("10.0.0.5")
        self.assertIn("[mariadbd]\n", text)
        self.assertIn("bind-address        = 127.0.0.1,10.0.0.5\n", text)
        self.assertIn("gtid_strict_mode    = ON\n", text)
        self.assertIn("ssl_cert            = /etc/mysql/carlos-emr-tls/server.pem\n", text)
        self.assertIn("ssl_key             = /etc/mysql/carlos-emr-tls/server.key\n", text)
        active = [ln for ln in text.splitlines() if ln and not ln.startswith("#")]
        self.assertFalse(any(ln.startswith("require_secure_transport") for ln in active))
        self.assertFalse(any(ln.startswith("read_only") for ln in active))
        self.assertTrue(text.startswith("# Generated by carlos-ctl replica add"))

    def test_sysctl_picks_family(self):
        self.assertIn("net.ipv4.ip_nonlocal_bind = 1\n", R.render_sysctl("10.0.0.5"))
        self.assertIn("net.ipv6.ip_nonlocal_bind = 1\n", R.render_sysctl("fd00::5"))
        self.assertNotIn("ipv6", R.render_sysctl("10.0.0.5"))

    def test_account_sql_shape(self):
        sql = R.account_sql("repl_10_0_0_6", "10.0.0.6", "p'w\\x", ["carlos", "drugref2"])
        lines = sql.strip().split("\n")
        self.assertEqual(lines[0], "SET SESSION sql_log_bin = 0;")
        self.assertIn("CREATE USER IF NOT EXISTS 'repl_10_0_0_6'@'10.0.0.6' IDENTIFIED BY 'p\\'w\\\\x' REQUIRE SSL;", lines)
        self.assertIn("ALTER USER 'repl_10_0_0_6'@'10.0.0.6' IDENTIFIED BY 'p\\'w\\\\x' REQUIRE SSL;", lines)
        self.assertIn("GRANT SELECT, SHOW VIEW, TRIGGER, EVENT ON `carlos`.* TO 'repl_10_0_0_6'@'10.0.0.6';", lines)
        self.assertIn("GRANT SELECT, SHOW VIEW, TRIGGER, EVENT ON `drugref2`.* TO 'repl_10_0_0_6'@'10.0.0.6';", lines)
        self.assertIn("GRANT RELOAD, REPLICATION CLIENT, REPLICATION SLAVE ON *.* TO 'repl_10_0_0_6'@'10.0.0.6';", lines)
        self.assertEqual(lines[-1], "FLUSH PRIVILEGES;")
        # never PROCESS, never SUPER, never ALL
        self.assertNotIn("PROCESS", sql)
        self.assertNotIn("SUPER", sql)
        self.assertNotIn("ALL PRIVILEGES", sql)

    def test_drop_account_sql_is_out_of_binlog(self):
        sql = R.drop_account_sql("repl_10_0_0_6", "10.0.0.6")
        self.assertTrue(sql.startswith("SET SESSION sql_log_bin = 0;"))
        self.assertIn("DROP USER IF EXISTS 'repl_10_0_0_6'@'10.0.0.6';", sql)

    def test_firewall_hint_names_both_addresses(self):
        text = R.firewall_hint("10.0.0.5", ["10.0.0.6", "10.0.0.7"])
        self.assertIn("ip saddr 10.0.0.6 ip daddr 10.0.0.5 tcp dport 3306 accept", text)
        self.assertIn("ufw allow from 10.0.0.7 to 10.0.0.5 port 3306 proto tcp", text)
        self.assertIn("ip6 saddr", R.firewall_hint("fd00::5", ["fd00::6"]))

    def test_norm_bind_list(self):
        self.assertEqual(R.norm_bind_list("10.0.0.5, 127.0.0.1"), ["10.0.0.5", "127.0.0.1"])
        self.assertEqual(R.norm_bind_list("127.0.0.1,10.0.0.5"), R.norm_bind_list("10.0.0.5,127.0.0.1"))
        self.assertEqual(R.norm_bind_list(""), [])
        self.assertEqual(R.norm_bind_list(None), [])


class Token(unittest.TestCase):
    def _tok(self, now=None):
        return R.build_token(
            primary_host="10.0.0.5", port=3306, mariadb_version="11.4.5-MariaDB",
            ca_pem="-----BEGIN CERTIFICATE-----\nAAA\n-----END CERTIFICATE-----\n",
            repl_user="repl_10_0_0_6", repl_password="s3cret", accounts={
                "carlos": "apw", "drugref": "dpw", "backup": "bpw"},
            app_hosts=["10.0.0.5"], db_name="carlos", province="on",
            schemas=["carlos", "drugref2"], size_bytes=1234, tz="America/Toronto",
            server_name="emr.example.ca", generation=1, now=now)

    def test_round_trips_through_json(self):
        now = dt.datetime(2026, 9, 12, 12, 0, tzinfo=dt.timezone.utc)
        tok = self._tok(now)
        back = json.loads(json.dumps(tok))
        self.assertEqual(back["schema"], R.TOKEN_SCHEMA)
        self.assertEqual(back["issued_at"], "2026-09-12T12:00:00+00:00")
        self.assertEqual(back["expires_at"], "2026-09-13T12:00:00+00:00")
        self.assertEqual(back["repl"]["user"], "repl_10_0_0_6")
        self.assertEqual(back["accounts"]["app_hosts"], ["10.0.0.5"])
        self.assertEqual(back["db"]["schemas"], ["carlos", "drugref2"])
        self.assertEqual(back["db"]["size_bytes"], 1234)
        self.assertEqual(back["primary"]["tz"], "America/Toronto")
        self.assertEqual(back["accounts"]["generation"], 1)

    def test_expiry(self):
        now = dt.datetime(2026, 9, 12, 12, 0, tzinfo=dt.timezone.utc)
        tok = self._tok(now)
        self.assertFalse(R.token_expired(tok, now + dt.timedelta(hours=23)))
        self.assertTrue(R.token_expired(tok, now + dt.timedelta(hours=24)))
        self.assertTrue(R.token_expired({}))
        self.assertTrue(R.token_expired({"expires_at": "garbage"}))


class State(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.base = os.path.join(self.tmp.name, "replicas")
        os.makedirs(self.base)
        self._p = mock.patch.object(R, "REPLICAS_DIR", self.base)
        self._p.start()

    def tearDown(self):
        self._p.stop()
        self.tmp.cleanup()

    def test_state_round_trip_and_listing(self):
        R._write_state("10.0.0.6", {"ip": "10.0.0.6", "account": "repl_10_0_0_6", "generation": 1})
        os.makedirs(os.path.join(self.base, "10.0.0.7"))
        with open(os.path.join(self.base, "10.0.0.7", "state.json"), "w") as fh:
            fh.write("{not json")
        got = R.list_replicas(self.base)
        self.assertEqual([r["ip"] for r in got], ["10.0.0.6", "10.0.0.7"])
        self.assertEqual(got[0]["generation"], 1)
        self.assertTrue(got[1]["damaged"])
        self.assertEqual(oct(os.stat(os.path.join(self.base, "10.0.0.6")).st_mode & 0o777), "0o700")
        self.assertEqual(oct(os.stat(os.path.join(self.base, "10.0.0.6", "state.json")).st_mode & 0o777), "0o600")
        self.assertEqual(R._read_state("10.0.0.6")["account"], "repl_10_0_0_6")
        self.assertIsNone(R._read_state("10.0.0.9"))

    def test_missing_base_lists_nothing(self):
        self.assertEqual(R.list_replicas(os.path.join(self.tmp.name, "nope")), [])

    def test_mark_consumed_is_sticky(self):
        st = {"ip": "10.0.0.6", "account": "x", "generation": 1}
        R._write_state("10.0.0.6", st)
        R._mark_consumed(st, "10.0.0.6")
        first = R._read_state("10.0.0.6")["consumed_at"]
        R._mark_consumed(st, "10.0.0.6")
        self.assertEqual(R._read_state("10.0.0.6")["consumed_at"], first)


class Processlist(unittest.TestCase):
    def test_binlog_dump_rows_only(self):
        rows = "\n".join([
            "carlos\t127.0.0.1:41234\tSleep",
            "repl_10_0_0_6\t10.0.0.6:51000\tBinlog Dump",
            "repl_fd00__7\t[fd00::7]:51001\tBinlog Dump GTID",
            "root\tlocalhost\tQuery",
        ])
        live = R.connected_replica_users(rows)
        self.assertEqual(live, {"repl_10_0_0_6": "10.0.0.6", "repl_fd00__7": "[fd00::7]"})
        self.assertEqual(R.connected_replica_users(""), {})


class ReplEnv(unittest.TestCase):
    def test_write_creates_from_skeleton_and_preserves_operator_keys(self):
        with tempfile.TemporaryDirectory() as d:
            p = os.path.join(d, "replication.env")
            R.write_repl_env("primary", "10.0.0.5", path=p)
            self.assertEqual(oct(os.stat(p).st_mode & 0o777), "0o644")
            with open(p) as fh:
                text = fh.read()
            self.assertIn("CARLOS_DB_ROLE=primary\n", text)
            self.assertIn("CARLOS_DB_REPL_LISTEN_IP=10.0.0.5\n", text)
            # operator edit survives a later write
            with open(p, "a") as fh:
                fh.write("CARLOS_DB_REPL_ALERT_WEBHOOK=https://hooks.example/x\n")
            R.write_repl_env("standalone", "", path=p)
            rs = R.ReplSettings(p)
            self.assertEqual(rs.role, "standalone")
            self.assertEqual(rs.listen_ip, "")
            self.assertEqual(rs.alert_webhook, "https://hooks.example/x")

    def test_settings_absent_file_is_standalone(self):
        rs = R.ReplSettings("/nonexistent/replication.env")
        self.assertEqual(rs.role, "standalone")
        self.assertEqual(rs.max_lag, 300)

    def test_settings_refuse_primary_without_listen(self):
        with tempfile.TemporaryDirectory() as d:
            p = os.path.join(d, "replication.env")
            with open(p, "w") as fh:
                fh.write("CARLOS_DB_ROLE=primary\nCARLOS_DB_REPL_LISTEN_IP=\n")
            with self.assertRaises(SystemExit):
                R.ReplSettings(p)

    def test_settings_refuse_bad_role_and_lag(self):
        with tempfile.TemporaryDirectory() as d:
            p = os.path.join(d, "replication.env")
            with open(p, "w") as fh:
                fh.write("CARLOS_DB_ROLE=galera\n")
            with self.assertRaises(SystemExit):
                R.ReplSettings(p)
            with open(p, "w") as fh:
                fh.write("CARLOS_DB_ROLE=standalone\nCARLOS_DB_REPL_MAX_LAG_SECONDS=soon\n")
            with self.assertRaises(SystemExit):
                R.ReplSettings(p)

    def test_shipped_skeleton_matches_builtin(self):
        skel = os.path.join(HERE, "..", "..", "assets", "skel", "replication.env")
        with open(skel) as fh:
            self.assertEqual(fh.read(), R._SKEL_REPL_ENV)


class AddArgParsing(unittest.TestCase):
    def test_parse_add(self):
        o = R._parse_add(["10.0.0.6", "--listen", "10.0.0.5", "--app-host", "10.0.0.9",
                          "--reissue", "--allow-public", "--no-restart"])
        self.assertEqual(o["ip"], "10.0.0.6")
        self.assertEqual(o["listen"], "10.0.0.5")
        self.assertEqual(o["app_hosts"], ["10.0.0.9"])
        self.assertTrue(o["reissue"] and o["allow_public"] and o["no_restart"])

    def test_parse_add_rejects_junk(self):
        for argv in ([], ["--listen"], ["10.0.0.6", "--bogus"], ["10.0.0.6", "10.0.0.7"]):
            with self.subTest(argv=argv), self.assertRaises(SystemExit):
                R._parse_add(argv)


class CliWiring(unittest.TestCase):
    def test_cli_has_replica_verb_and_usage(self):
        from carlos_ctl import cli
        self.assertIn("replica", cli._VERBS)
        self.assertIn("carlos-ctl replica add", cli._USAGE)

    def test_join_and_promote_point_at_phase_two(self):
        with self.assertRaises(SystemExit):
            R.cmd_replica(["join", "token"])
        with self.assertRaises(SystemExit):
            R.cmd_replica(["promote"])
        self.assertEqual(R.cmd_replica(["--help"]), 0)


if __name__ == "__main__":
    unittest.main()
