package oscar.oscarEncounter.oscarMeasurements.flowsheets;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.MeasurementInfo;

//  Copyright (c) 2026 CARLOS Contributors. All Rights Reserved.
//
//  This software is published under the GPL GNU General Public License.
//  This program is free software; you can redistribute it and/or
//  modify it under the terms of the GNU General Public License
//  as published by the Free Software Foundation; either version 2
//  of the License, or (at your option) any later version.
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details. You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//
//  Maintained by the CARLOS EMR Project.
//  https://github.com/carlos-emr/carlos
//
//  Modifications by CARLOS Contributors, 2026.

// 3 month recommendations / 6 month warnings
//     measurement_type="REBG"
//     measurement_type="A1C"
//     measurement_type="DMED"
//     measurement_type="BP"
//     measurement_type="BMED"
//     measurement_type="BMI"
//     measurement_type="DIER"
//     measurement_type="NOSK"
// Annually 10 month recommendation / 12 month warning
//     measurement_type="LDL"
//     measurement_type="TCHD"
//     measurement_type="TG"
//     measurement_type="LMED"
//     measurement_type="FGLC"
//     measurement_type="EYEE"
//     measurement_type="ACR"
//     measurement_type="EGFR"
//     measurement_type="FTE"
//     measurement_type="FTLS"
//     measurement_type="PANE"
//     measurement_type="EDGI"
//     measurement_type="DMME"
//     prevention_type="Flu"
// Once warn if not found
//  prevention_type="Pneumovax"

rule "REBG 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("REBG") >= 3)
        eval(m.getLastDateRecordedInMonths("REBG") < 6)
    then
        m.log("REBG 1 getting called");
        m.addRecommendation("REBG","Blood Glucose hasn't been reviewed in "+m.getLastDateRecordedInMonths("REBG")+" months");
end

rule "REBG 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("REBG") >= 6)
    then
        m.log("REBG 2 getting called");
        m.addWarning("REBG","Blood Glucose hasn't been reviewed in "+m.getLastDateRecordedInMonths("REBG")+" months");
end

rule "REBG 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("REBG") == -1)
    then
        m.log("REBG 3 getting called");
        m.addWarning("REBG","Blood Glucose hasn't been reviewed");
end

// A1C

rule "A1C 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("A1C") >= 3)
        eval(m.getLastDateRecordedInMonths("A1C") < 6)
    then
        m.log("A1C 1 getting called");
        m.addRecommendation("A1C","An A1C hasn't been recorded in "+m.getLastDateRecordedInMonths("A1C")+" months");
end

rule "A1C 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("A1C") >= 6)
    then
        m.log("A1C 2 getting called");
        m.addWarning("A1C","An A1C hasn't been recorded in "+m.getLastDateRecordedInMonths("A1C")+" months");
end

rule "A1C 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("A1C") == -1)
    then
        m.log("A1C 3 getting called");
        m.addWarning("A1C","no A1C values has been recorded");
end

// DMED

rule "DMED 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DMED") >= 3)
        eval(m.getLastDateRecordedInMonths("DMED") < 6)
    then
        m.log("DMED 1 getting called");
        m.addRecommendation("DMED","DM Med changes haven't been recorded in "+m.getLastDateRecordedInMonths("DMED")+" months");
end

rule "DMED 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DMED") >= 6)
    then
        m.log("DMED 2 getting called");
        m.addWarning("DMED","DM Med changes haven't been recorded in "+m.getLastDateRecordedInMonths("DMED")+" months");
end

rule "DMED 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DMED") == -1)
    then
        m.log("DMED 3 getting called");
        m.addWarning("DMED","no DM Med changes have been recorded");
end

// BP

rule "BP 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BP") >= 3)
        eval(m.getLastDateRecordedInMonths("BP") < 6)
    then
        m.log("BP 1 getting called");
        m.addRecommendation("BP","BP hasn't been recorded in "+m.getLastDateRecordedInMonths("BP")+" months");
end

rule "BP 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BP") >= 6)
    then
        m.log("BP 2 getting called");
        m.addWarning("BP","BP hasn't been recorded in "+m.getLastDateRecordedInMonths("BP")+" months");
end

rule "BP 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BP") == -1)
    then
        m.log("BP 3 getting called");
        m.addWarning("BP","no BP has been recorded");
end

// BMED

rule "BMED 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BMED") >= 3)
        eval(m.getLastDateRecordedInMonths("BMED") < 6)
    then
        m.log("BMED 1 getting called");
        m.addRecommendation("BMED","BP Meds hasn't been recorded in "+m.getLastDateRecordedInMonths("BMED")+" months");
end

rule "BMED 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BMED") >= 6)
    then
        m.log("BMED 2 getting called");
        m.addWarning("BMED","BP Meds hasn't been recorded in "+m.getLastDateRecordedInMonths("BMED")+" months");
end

rule "BMED 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BMED") == -1)
    then
        m.log("BMED 3 getting called");
        m.addWarning("BMED","no BP Meds changes have been recorded");
end

// BMI

rule "BMI 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BMI") >= 3)
        eval(m.getLastDateRecordedInMonths("BMI") < 6)
    then
        m.log("BMI 1 getting called");
        m.addRecommendation("BMI","BMI hasn't been recorded in "+m.getLastDateRecordedInMonths("BMI")+" months");
end

rule "BMI 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BMI") >= 6)
    then
        m.log("BMI 2 getting called");
        m.addWarning("BMI","BMI hasn't been recorded in "+m.getLastDateRecordedInMonths("BMI")+" months");
end

rule "BMI 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BMI") == -1)
    then
        m.log("BMI 3 getting called");
        m.addWarning("BMI","no BMI has been recorded");
end

// DIER

rule "DIER 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DIER") >= 3)
        eval(m.getLastDateRecordedInMonths("DIER") < 6)
    then
        m.log("DIER 1 getting called");
        m.addRecommendation("DIER","Diet/Exercise hasn't been recorded in "+m.getLastDateRecordedInMonths("DIER")+" months");
end

rule "DIER 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DIER") >= 6)
    then
        m.log("DIER 2 getting called");
        m.addWarning("DIER","Diet/ Exercise hasn't been recorded in "+m.getLastDateRecordedInMonths("DIER")+" months");
end

rule "DIER 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DIER") == -1)
    then
        m.log("DIER 3 getting called");
        m.addWarning("DIER","Diet/Excercise has not been recorded");
end

// NOSK

rule "NOSK 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("NOSK") >= 3)
        eval(m.getLastDateRecordedInMonths("NOSK") < 6)
        eval(m.getLastValueAsInt("NOSK") != 0)
    then
        m.log("NOSK 1 getting called");
        m.addRecommendation("NOSK","Number of Cigarettes hasn't been recorded in "+m.getLastDateRecordedInMonths("NOSK")+" months");
end

rule "NOSK 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("NOSK") >= 6)
        eval(m.getLastValueAsInt("NOSK") != 0)
    then
        m.log("NOSK 2 getting called");
        m.addWarning("NOSK","Number of Cigarettes hasn't been recorded in "+m.getLastDateRecordedInMonths("NOSK")+" months");
end

rule "NOSK 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("NOSK") == -1)
    then
        m.log("NOSK 3 getting called");
        m.addWarning("NOSK","Number of Cigarrettes has never been recorded, if non smoker enter zero");
end

// LDL

rule "LDL 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LDL") >= 10)
        eval(m.getLastDateRecordedInMonths("LDL") < 12)
    then
        m.log("LDL 1 getting called");
        m.addRecommendation("LDL","LDL hasn't been recorded in "+m.getLastDateRecordedInMonths("LDL")+" months");
end

rule "LDL 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LDL") >= 12)
    then
        m.log("LDL 2 getting called");
        m.addWarning("LDL","LDL hasn't been recorded in "+m.getLastDateRecordedInMonths("LDL")+" months");
end

rule "LDL 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LDL") == -1)
    then
        m.log("LDL 3 getting called");
        m.addWarning("LDL","LDL has not been recorded");
end

// TCHD

rule "TCHD 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TCHD") >= 10)
        eval(m.getLastDateRecordedInMonths("TCHD") < 12)
    then
        m.log("TCHD 1 getting called");
        m.addRecommendation("TCHD","TC/HDL hasn't been recorded in "+m.getLastDateRecordedInMonths("TCHD")+" months");
end

rule "TCHD 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TCHD") >= 12)
    then
        m.log("TCHD 2 getting called");
        m.addWarning("TCHD","TC/HDL hasn't been recorded in "+m.getLastDateRecordedInMonths("TCHD")+" months");
end

rule "TCHD 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TCHD") == -1)
    then
        m.log("TCHD 3 getting called");
        m.addWarning("TCHD","TC/HDL has not been recorded");
end

// TG

rule "TG 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TG") >= 10)
        eval(m.getLastDateRecordedInMonths("TG") < 12)
    then
        m.log("TG 1 getting called");
        m.addRecommendation("TG","Triglycerides hasn't been recorded in "+m.getLastDateRecordedInMonths("TG")+" months");
end

rule "TG 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TG") >= 12)
    then
        m.log("TG 2 getting called");
        m.addWarning("TG","Triglycerides hasn't been recorded in "+m.getLastDateRecordedInMonths("TG")+" months");
end

rule "TG 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TG") == -1)
    then
        m.log("TG 3 getting called");
        m.addWarning("TG","Triglycerides has not been recorded");
end

// LMED

rule "LMED 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LMED") >= 10)
        eval(m.getLastDateRecordedInMonths("LMED") < 12)
    then
        m.log("LMED 1 getting called");
        m.addRecommendation("LMED","Lipid Lowering Meds hasn't been recorded in  "+m.getLastDateRecordedInMonths("LMED")+" months");
end

rule "LMED 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LMED") >= 12)
    then
        m.log("LMED 2 getting called");
        m.addWarning("LMED","Lipid Lowering Meds hasn't been recorded in "+m.getLastDateRecordedInMonths("LMED")+" months");
end

rule "LMED 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LMED") == -1)
    then
        m.log("LMED 3 getting called");
        m.addWarning("LMED","Lipid Lowering Meds has not been recorded");
end

// FGLC

rule "FGLC 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("FGLC") >= 10)
        eval(m.getLastDateRecordedInMonths("FGLC") < 12)
    then
        m.log("FGLC 1 getting called");
        m.addRecommendation("FGLC","Fasting glucose meter/lab comparison hasn't been recorded in  "+m.getLastDateRecordedInMonths("FGLC")+" months");
end

rule "FGLC 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("FGLC") >= 12)
    then
        m.log("FGLC 2 getting called");
        m.addWarning("FGLC","Fasting glucose meter/lab comparison hasn't been recorded in  "+m.getLastDateRecordedInMonths("FGLC")+" months");
end

rule "FGLC 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("FGLC") == -1)
    then
        m.log("FGLC 3 getting called");
        m.addWarning("FGLC","Fasting glucose meter/lab comparison has not been recorded");
end

// EYEE

rule "EYEE 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EYEE") >= 10)
        eval(m.getLastDateRecordedInMonths("EYEE") < 12)
    then
        m.log("EYEE 1 getting called");
        m.addRecommendation("EYEE","An Opthalmologist/ Optometrist exam hasn't been recorded in  "+m.getLastDateRecordedInMonths("EYEE")+" months");
end

rule "EYEE 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EYEE") >= 12)
    then
        m.log("EYEE 2 getting called");
        m.addWarning("EYEE","An Opthalmologist/ Optometrist exam hasn't been recorded in  "+m.getLastDateRecordedInMonths("EYEE")+" months");
end

rule "EYEE 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EYEE") == -1)
    then
        m.log("EYEE 3 getting called");
        m.addWarning("EYEE","An Opthalmologist/ Optometrist exam has not been recorded");
end

// ACR

rule "ACR 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("ACR") >= 10)
        eval(m.getLastDateRecordedInMonths("ACR") < 12)
    then
        m.log("ACR 1 getting called");
        m.addRecommendation("ACR","An Alb: creat ratio value hasn't been recorded in "+m.getLastDateRecordedInMonths("ACR")+" months");
end

rule "ACR 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("ACR") >= 12)
    then
        m.log("ACR 2 getting called");
        m.addWarning("ACR","An Alb: creat ratio value hasn't been recorded in "+m.getLastDateRecordedInMonths("ACR")+" months");
end

rule "ACR 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("ACR") == -1)
    then
        m.log("ACR 3 getting called");
        m.addWarning("ACR","An Alb: creat ratio value has not been recorded");
end

// EGFR

rule "EGFR 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EGFR") >= 10)
        eval(m.getLastDateRecordedInMonths("EGFR") < 12)
    then
        m.log("EGFR 1 getting called");
        m.addRecommendation("EGFR","An eGFR value hasn't been recorded in "+m.getLastDateRecordedInMonths("EGFR")+" months");
end

rule "EGFR 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EGFR") >= 12)
    then
        m.log("EGFR 2 getting called");
        m.addWarning("EGFR","An eGFR value hasn't been recorded in "+m.getLastDateRecordedInMonths("EGFR")+" months");
end

rule "EGFR 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EGFR") == -1)
    then
        m.log("EGFR 3 getting called");
        m.addWarning("EGFR","An eGFR value has not been recorded");
end

// FTE

rule "FTE 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("FTE") >= 10)
        eval(m.getLastDateRecordedInMonths("FTE") < 12)
    then
        m.log("FTE 1 getting called");
        m.addRecommendation("FTE","A Lower Extremity Exam hasn't been recorded in "+m.getLastDateRecordedInMonths("FTE")+" months");
end

rule "FTE 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("FTE") >= 12)
    then
        m.log("FTE 2 getting called");
        m.addWarning("FTE","A Lower Extremity Exam hasn't been recorded in "+m.getLastDateRecordedInMonths("FTE")+" months");
end

rule "FTE 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("FTE") == -1)
    then
        m.log("FTE 3 getting called");
        m.addWarning("FTE","A Lower Extremity Exam has not been recorded");
end

// FTLS

rule "FTLS 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("FTLS") >= 10)
        eval(m.getLastDateRecordedInMonths("FTLS") < 12)
    then
        m.log("FTLS 1 getting called");
        m.addRecommendation("FTLS","A loss of sensation test hasn't been recorded in "+m.getLastDateRecordedInMonths("FTLS")+" months");
end

rule "FTLS 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("FTLS") >= 12)
    then
        m.log("FTLS 2 getting called");
        m.addWarning("FTLS","A loss of sensation test hasn't been recorded in "+m.getLastDateRecordedInMonths("FTLS")+" months");
end

rule "FTLS 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("FTLS") == -1)
    then
        m.log("FTLS 3 getting called");
        m.addWarning("FTLS","A loss of sensation test has not been recorded");
end

// PANE

rule "PANE 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("PANE") >= 10)
        eval(m.getLastDateRecordedInMonths("PANE") < 12)
    then
        m.log("PANE 1 getting called");
        m.addRecommendation("PANE","A value for Painful Neuropathy hasn't been recorded in "+m.getLastDateRecordedInMonths("PANE")+" months");
end

rule "PANE 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("PANE") >= 12)
    then
        m.log("PANE 2 getting called");
        m.addWarning("PANE","A value for Painful Neuropathy hasn't been recorded in "+m.getLastDateRecordedInMonths("PANE")+" months");
end

rule "PANE 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("PANE") == -1)
    then
        m.log("PANE 3 getting called");
        m.addWarning("PANE","A value for Painful Neuropathy has not been recorded");
end

// EDGI

rule "EDGI 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EDGI") >= 10)
        eval(m.getLastDateRecordedInMonths("EDGI") < 12)
    then
        m.log("EDGI 1 getting called");
        m.addRecommendation("EDGI","A value for Autonomic Neuropathy hasn't been recorded in "+m.getLastDateRecordedInMonths("EDGI")+" months");
end

rule "EDGI 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EDGI") >= 12)
    then
        m.log("EDGI 2 getting called");
        m.addWarning("EDGI","A value for Autonomic Neuropathy hasn't been recorded in  "+m.getLastDateRecordedInMonths("EDGI")+" months");
end

rule "EDGI 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EDGI") == -1)
    then
        m.log("EDGI 3 getting called");
        m.addWarning("EDGI","A value for Autonomic Neuropathy has not been recorded");
end

// DMME

rule "DMME 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DMME") >= 10)
        eval(m.getLastDateRecordedInMonths("DMME") < 12)
    then
        m.log("DMME 1 getting called");
        m.addRecommendation("DMME","A value for Diabetes Education hasn't been recorded in "+m.getLastDateRecordedInMonths("DMME")+" months");
end

rule "DMME 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DMME") >= 12)
    then
        m.log("DMME 2 getting called");
        m.addWarning("DMME","A value for Diabetes Education hasn't been recorded in "+m.getLastDateRecordedInMonths("DMME")+" months");
end

rule "DMME 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DMME") == -1)
    then
        m.log("DMME 3 getting called");
        m.addWarning("DMME","A value for Diabetes Education has not been recorded");
end
