package oscar.oscarEncounter.oscarMeasurements.flowsheets;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.MeasurementInfo;

//  Copyright (c) 2001-2002. Department of Family Medicine, McMaster University. All Rights Reserved.
//  Copyright (c) 2026 CARLOS Contributors. All Rights Reserved.
//
//  This software is published under the GPL GNU General Public License.
//  This program is free software; you can redistribute it and/or
//  modify it under the terms of the GNU General Public License
//  as published by the Free Software Foundation; either version 2
//  of the License, or (at your option) any later version.
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details. You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//
//  Originally written for the Department of Family Medicine, McMaster University.
//  Now maintained by the CARLOS EMR Project.
//  https://github.com/carlos-emr/carlos
//
//  Document   : ckdFlowsheet.xml
//  Created on : March 26, 2013, 3:28 PM
//  Author     : John Wilson
//  Description:
//        Define ckd flowsheet
//
//  Modifications by CARLOS Contributors, 2026.

rule "ACR 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("ACR") >= 10)
        eval(m.getLastDateRecordedInMonths("ACR") < 12)
    then
        m.log("ACR 1 getting called");
        m.addRecommendation("ACR","An Alb: creat ratio value hasn't been recorded in "+m.getLastDateRecordedInMonths("ACR")+" months");
end

rule "ACR 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("ACR") >= 12)
    then
        m.log("ACR 2 getting called");
        m.addWarning("ACR","An Alb: creat ratio value hasn't been recorded in "+m.getLastDateRecordedInMonths("ACR")+" months");
end

rule "ACR 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("ACR") == -1)
    then
        m.log("ACR 3 getting called");
        m.addWarning("ACR","An Alb: creat ratio value has not been recorded");
end

rule "EGFR 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EGFR") >= 10)
        eval(m.getLastDateRecordedInMonths("EGFR") < 12)
    then
        m.log("EGFR 1 getting called");
        m.addRecommendation("EGFR","An eGFR value hasn't been recorded in "+m.getLastDateRecordedInMonths("EGFR")+" months");
end

rule "EGFR 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EGFR") >= 12)
    then
        m.log("EGFR 2 getting called");
        m.addWarning("EGFR","An eGFR value hasn't been recorded in "+m.getLastDateRecordedInMonths("EGFR")+" months");
end

rule "EGFR 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EGFR") == -1)
    then
        m.log("EGFR 3 getting called");
        m.addWarning("EGFR","An eGFR value has not been recorded");
end
