package ckdFlowSheet;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.MeasurementInfo;

rule "ACR 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("ACR") >= 10 )
        eval( m.getLastDateRecordedInMonths("ACR") < 12 )
    then
        m.log("ACR 1 getting called");
        m.addRecommendation("ACR","An Alb: creat ratio value hasn't been recorded in "+m.getLastDateRecordedInMonths("ACR")+" months");
end

rule "ACR 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("ACR") >= 12 )
    then
        m.log("ACR 2 getting called");
        m.addWarning("ACR","An Alb: creat ratio value hasn't been recorded in "+m.getLastDateRecordedInMonths("ACR")+" months");
end

rule "ACR 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("ACR") ==  -1 )
    then
        m.log("ACR 3 getting called");
        m.addWarning("ACR","An Alb: creat ratio value has not been recorded");
end

rule "EGFR 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("EGFR") >= 10 )
        eval( m.getLastDateRecordedInMonths("EGFR") < 12 )
    then
        m.log("EGFR 1 getting called");
        m.addRecommendation("EGFR","An eGFR value hasn't been recorded in "+m.getLastDateRecordedInMonths("EGFR")+" months");
end

rule "EGFR 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("EGFR") >= 12 )
    then
        m.log("EGFR 2 getting called");
        m.addWarning("EGFR","An eGFR value hasn't been recorded in "+m.getLastDateRecordedInMonths("EGFR")+" months");
end

rule "EGFR 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("EGFR") ==  -1 )
    then
        m.log("EGFR 3 getting called");
        m.addWarning("EGFR","An eGFR value has not been recorded");
end
