package HIVFlowSheet;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.MeasurementInfo;

rule "CD4 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CD4") >= 3 )
        eval( m.getLastDateRecordedInMonths("CD4") < 6 )
    then
        m.log("CD4 1 getting called");
        m.addRecommendation("CD4","CD4 hasn't been reviewed in "+m.getLastDateRecordedInMonths("CD4")+" months");
end

rule "CD4 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CD4") >= 6 )
    then
        m.log("CD4 2 getting called");
        m.addWarning("CD4","CD4 hasn't been reviewed in "+m.getLastDateRecordedInMonths("CD4")+" months");
end

rule "CD4 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CD4") ==  -1 )
    then
        m.log("CD4 3 getting called");
        m.addWarning("CD4","CD4 hasn't been reviewed");
end

rule "VLOA 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("VLOA") >= 3 )
        eval( m.getLastDateRecordedInMonths("VLOA") < 6 )
    then
        m.log("VLOA 1 getting called");
        m.addRecommendation("VLOA","A Viral Load hasn't been recorded in "+m.getLastDateRecordedInMonths("VLOA")+" months");
end

rule "VLOA 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("VLOA") >= 6 )
    then
        m.log("VLOA 2 getting called");
        m.addWarning("VLOA","A Viral Load hasn't been recorded in "+m.getLastDateRecordedInMonths("VLOA")+" months");
end

rule "VLOA 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("VLOA") ==  -1 )
    then
        m.log("VLOA 3 getting called");
        m.addWarning("VLOA","no Viral Load values has been recorded");
end

rule "Hb 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Hb") >= 3 )
        eval( m.getLastDateRecordedInMonths("Hb") < 6 )
    then
        m.log("Hb 1 getting called");
        m.addRecommendation("Hb","Hb changes haven't been recorded in "+m.getLastDateRecordedInMonths("Hb")+" months");
end

rule "Hb 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Hb") >= 6 )
    then
        m.log("Hb 2 getting called");
        m.addWarning("Hb","Hb changes haven't been recorded in "+m.getLastDateRecordedInMonths("Hb")+" months");
end

rule "Hb 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Hb") ==  -1 )
    then
        m.log("Hb 3 getting called");
        m.addWarning("Hb","no Hb changes have been recorded");
end

rule "ALT 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("ALT") >= 3 )
        eval( m.getLastDateRecordedInMonths("ALT") < 6 )
    then
        m.log("ALT 1 getting called");
        m.addRecommendation("ALT","ALT hasn't been recorded in "+m.getLastDateRecordedInMonths("ALT")+" months");
end

rule "ALT 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("ALT") >= 6 )
    then
        m.log("ALT 2 getting called");
        m.addWarning("ALT","ALT hasn't been recorded in "+m.getLastDateRecordedInMonths("ALT")+" months");
end

rule "ALT 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("ALT") ==  -1 )
    then
        m.log("ALT 3 getting called");
        m.addWarning("ALT","no ALT has been recorded");
end

rule "FBS 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("FBS") >= 6 )
        eval( m.getLastDateRecordedInMonths("FBS") < 9 )
    then
        m.log("FBS 1 getting called");
        m.addRecommendation("FBS","FBS hasn't been recorded in "+m.getLastDateRecordedInMonths("FBS")+" months");
end

rule "FBS 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("FBS") >= 9 )
    then
        m.log("FBS 2 getting called");
        m.addWarning("FBS","FBS hasn't been recorded in "+m.getLastDateRecordedInMonths("FBS")+" months");
end

rule "FBS 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("FBS") ==  -1 )
    then
        m.log("FBS 3 getting called");
        m.addWarning("FBS","no FBS has been recorded");
end

rule "TCHL 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("TCHL") >= 6 )
        eval( m.getLastDateRecordedInMonths("TCHL") < 9 )
    then
        m.log("TCHL 1 getting called");
        m.addRecommendation("TCHL","Total Cholesterol hasn't been recorded in "+m.getLastDateRecordedInMonths("TCHL")+" months");
end

rule "TCHL 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("TCHL") >= 9 )
    then
        m.log("TCHL 2 getting called");
        m.addWarning("TCHL","Total Cholesterol hasn't been recorded in "+m.getLastDateRecordedInMonths("TCHL")+" months");
end

rule "TCHL 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("TCHL") ==  -1 )
    then
        m.log("TCHL 3 getting called");
        m.addWarning("TCHL","no Total Cholesterol has been recorded");
end

rule "LDL 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("LDL") >= 6 )
        eval( m.getLastDateRecordedInMonths("LDL") < 9 )
    then
        m.log("LDL 1 getting called");
        m.addRecommendation("LDL","LDL hasn't been recorded in "+m.getLastDateRecordedInMonths("LDL")+" months");
end

rule "LDL 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("LDL") >= 9 )
    then
        m.log("LDL 2 getting called");
        m.addWarning("LDL","LDL hasn't been recorded in "+m.getLastDateRecordedInMonths("LDL")+" months");
end

rule "LDL 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("LDL") ==  -1 )
    then
        m.log("LDL 3 getting called");
        m.addWarning("LDL","no LDL has been recorded");
end

rule "HDL 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HDL") >= 6 )
        eval( m.getLastDateRecordedInMonths("HDL") < 9 )
    then
        m.log("HDL 1 getting called");
        m.addRecommendation("HDL","HDL hasn't been recorded in "+m.getLastDateRecordedInMonths("HDL")+" months");
end

rule "HDL 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HDL") >= 9 )
    then
        m.log("HDL 2 getting called");
        m.addWarning("HDL","HDL hasn't been recorded in "+m.getLastDateRecordedInMonths("HDL")+" months");
end

rule "HDL 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HDL") ==  -1 )
    then
        m.log("HDL 3 getting called");
        m.addWarning("HDL","no HDL has been recorded");
end

rule "TG 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("TG") >= 6 )
        eval( m.getLastDateRecordedInMonths("TG") < 9 )
    then
        m.log("TG 1 getting called");
        m.addRecommendation("TG","triglyceride hasn't been recorded in "+m.getLastDateRecordedInMonths("TG")+" months");
end

rule "TG 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("TG") >= 9 )
    then
        m.log("TG 2 getting called");
        m.addWarning("TG","triglyceride hasn't been recorded in "+m.getLastDateRecordedInMonths("TG")+" months");
end

rule "TG 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("TG") ==  -1 )
    then
        m.log("TG 3 getting called");
        m.addWarning("TG","no triglyceride has been recorded");
end

rule "URBH 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("URBH") >= 6 )
        eval( m.getLastDateRecordedInMonths("URBH") < 9 )
    then
        m.log("URBH 1 getting called");
        m.addRecommendation("URBH","URBH hasn't been recorded in "+m.getLastDateRecordedInMonths("URBH")+" months");
end

rule "URBH 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("URBH") >= 9 )
    then
        m.log("URBH 2 getting called");
        m.addWarning("URBH","URBH hasn't been recorded in "+m.getLastDateRecordedInMonths("URBH")+" months");
end

rule "URBH 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("URBH") ==  -1 )
    then
        m.log("URBH 3 getting called");
        m.addWarning("URBH","no URBH has been recorded");
end

rule "USSH 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("USSH") >= 6 )
        eval( m.getLastDateRecordedInMonths("USSH") < 9 )
    then
        m.log("USSH 1 getting called");
        m.addRecommendation("USSH","USSH hasn't been recorded in "+m.getLastDateRecordedInMonths("USSH")+" months");
end

rule "USSH 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("USSH") >= 9 )
    then
        m.log("USSH 2 getting called");
        m.addWarning("USSH","USSH hasn't been recorded in "+m.getLastDateRecordedInMonths("USSH")+" months");
end

rule "USSH 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("USSH") ==  -1 )
    then
        m.log("USSH 3 getting called");
        m.addWarning("USSH","no USSH has been recorded");
end

rule "UDUS 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("UDUS") >= 6 )
        eval( m.getLastDateRecordedInMonths("UDUS") < 9 )
    then
        m.log("UDUS 1 getting called");
        m.addRecommendation("UDUS","UDUS hasn't been recorded in "+m.getLastDateRecordedInMonths("UDUS")+" months");
end

rule "UDUS 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("UDUS") >= 9 )
    then
        m.log("UDUS 2 getting called");
        m.addWarning("UDUS","UDUS hasn't been recorded in "+m.getLastDateRecordedInMonths("UDUS")+" months");
end

rule "UDUS 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("UDUS") ==  -1 )
    then
        m.log("UDUS 3 getting called");
        m.addWarning("UDUS","no UDUS has been recorded");
end

rule "UAIP 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("UAIP") >= 6 )
        eval( m.getLastDateRecordedInMonths("UAIP") < 9 )
    then
        m.log("UAIP 1 getting called");
        m.addRecommendation("UAIP","UAIP hasn't been recorded in "+m.getLastDateRecordedInMonths("UAIP")+" months");
end

rule "UAIP 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("UAIP") >= 9 )
    then
        m.log("UAIP 2 getting called");
        m.addWarning("UAIP","UAIP hasn't been recorded in "+m.getLastDateRecordedInMonths("UAIP")+" months");
end

rule "UAIP 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("UAIP") ==  -1 )
    then
        m.log("UAIP 3 getting called");
        m.addWarning("UAIP","no UAIP has been recorded");
end

rule "UHTP 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("UHTP") >= 6 )
        eval( m.getLastDateRecordedInMonths("UHTP") < 9 )
    then
        m.log("UHTP 1 getting called");
        m.addRecommendation("UHTP","UHTP hasn't been recorded in "+m.getLastDateRecordedInMonths("UHTP")+" months");
end

rule "UHTP 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("UHTP") >= 9 )
    then
        m.log("UHTP 2 getting called");
        m.addWarning("UHTP","UHTP hasn't been recorded in "+m.getLastDateRecordedInMonths("UHTP")+" months");
end

rule "UHTP 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("UHTP") ==  -1 )
    then
        m.log("UHTP 3 getting called");
        m.addWarning("UHTP","no UHTP has been recorded");
end

rule "VB12 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("VB12") >= 12 )
        eval( m.getLastDateRecordedInMonths("VB12") < 18 )
    then
        m.log("VB12 1 getting called");
        m.addRecommendation("VB12","Vit B12 hasn't been recorded in "+m.getLastDateRecordedInMonths("VB12")+" months");
end

rule "VB12 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("VB12") >= 18 )
    then
        m.log("VB12 2 getting called");
        m.addWarning("VB12","Vit B12 hasn't been recorded in "+m.getLastDateRecordedInMonths("VB12")+" months");
end

rule "VB12 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("VB12") ==  -1 )
    then
        m.log("VB12 3 getting called");
        m.addWarning("VB12","no Vit B12 has been recorded");
end

rule "FTST 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("FTST") >= 12 )
        eval( m.getLastDateRecordedInMonths("FTST") < 18 )
    then
        m.log("FTST 1 getting called");
        m.addRecommendation("FTST","Free Testost hasn't been recorded in "+m.getLastDateRecordedInMonths("FTST")+" months");
end

rule "FTST 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("FTST") >= 18 )
    then
        m.log("FTST 2 getting called");
        m.addWarning("FTST","Free Testost hasn't been recorded in "+m.getLastDateRecordedInMonths("FTST")+" months");
end

rule "FTST 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("FTST") ==  -1 )
    then
        m.log("FTST 3 getting called");
        m.addWarning("FTST","no Free Testost has been recorded");
end

rule "VDRL 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("VDRL") >= 12 )
        eval( m.getLastDateRecordedInMonths("VDRL") < 18 )
    then
        m.log("VDRL 1 getting called");
        m.addRecommendation("VDRL","VDRL hasn't been recorded in "+m.getLastDateRecordedInMonths("VDRL")+" months");
end

rule "VDRL 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("VDRL") >= 18 )
    then
        m.log("VDRL 2 getting called");
        m.addWarning("VDRL","VDRL hasn't been recorded in "+m.getLastDateRecordedInMonths("VDRL")+" months");
end

rule "VDRL 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("VDRL") ==  -1 )
    then
        m.log("VDRL 3 getting called");
        m.addWarning("VDRL","no VDRL has been recorded");
end

rule "TOXP 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("TOXP") >= 12 )
        eval( m.getLastDateRecordedInMonths("TOXP") < 18 )
    then
        m.log("TOXP 1 getting called");
        m.addRecommendation("TOXP","Toxoplasma lgG hasn't been recorded in "+m.getLastDateRecordedInMonths("TOXP")+" months");
end

rule "TOXP 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("TOXP") >= 18 )
    then
        m.log("TOXP 2 getting called");
        m.addWarning("TOXP","Toxoplasma lgG hasn't been recorded in "+m.getLastDateRecordedInMonths("TOXP")+" months");
end

rule "TOXP 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("TOXP") ==  -1 )
    then
        m.log("TOXP 3 getting called");
        m.addWarning("TOXP","no Toxoplasma lgG has been recorded");
end

rule "HpAI 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpAI") >= 12 )
        eval( m.getLastDateRecordedInMonths("HpAI") < 18 )
    then
        m.log("HpAI 1 getting called");
        m.addRecommendation("HpAI","Hep A lgG hasn't been recorded in "+m.getLastDateRecordedInMonths("HpAI")+" months");
end

rule "HpAI 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpAI") >= 18 )
    then
        m.log("HpAI 2 getting called");
        m.addWarning("HpAI","Hep A lgG hasn't been recorded in "+m.getLastDateRecordedInMonths("HpAI")+" months");
end

rule "HpAI 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpAI") ==  -1 )
    then
        m.log("HpAI 3 getting called");
        m.addWarning("HpAI","no Hep A lgG has been recorded");
end

rule "HpBS 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpBS") >= 12 )
        eval( m.getLastDateRecordedInMonths("HpBS") < 18 )
    then
        m.log("HpBS 1 getting called");
        m.addRecommendation("HpBS","Hep BS Ag hasn't been recorded in "+m.getLastDateRecordedInMonths("HpBS")+" months");
end

rule "HpBS 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpBS") >= 18 )
    then
        m.log("HpBS 2 getting called");
        m.addWarning("HpBS","Hep BS Ag hasn't been recorded in "+m.getLastDateRecordedInMonths("HpBS")+" months");
end

rule "HpBS 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpBS") ==  -1 )
    then
        m.log("HpBS 3 getting called");
        m.addWarning("HpBS","no Hep BS Ag has been recorded");
end

rule "HpBA 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpBA") >= 12 )
        eval( m.getLastDateRecordedInMonths("HpBA") < 18 )
    then
        m.log("HpBA 1 getting called");
        m.addRecommendation("HpBA","Hep BS Ab hasn't been recorded in "+m.getLastDateRecordedInMonths("HpBA")+" months");
end

rule "HpBA 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpBA") >= 18 )
    then
        m.log("HpBA 2 getting called");
        m.addWarning("HpBA","Hep BS Ab hasn't been recorded in "+m.getLastDateRecordedInMonths("HpBA")+" months");
end

rule "HpBA 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpBA") ==  -1 )
    then
        m.log("HpBA 3 getting called");
        m.addWarning("HpBA","no Hep BS Ab has been recorded");
end

rule "HpCA 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpCA") >= 12 )
        eval( m.getLastDateRecordedInMonths("HpCA") < 18 )
    then
        m.log("HpCA 1 getting called");
        m.addRecommendation("HpCA","Hep C Ab hasn't been recorded in "+m.getLastDateRecordedInMonths("HpCA")+" months");
end

rule "HpCA 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpCA") >= 18 )
    then
        m.log("HpCA 2 getting called");
        m.addWarning("HpCA","Hep C Ab hasn't been recorded in "+m.getLastDateRecordedInMonths("HpCA")+" months");
end

rule "HpCA 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HpCA") ==  -1 )
    then
        m.log("HpCA 3 getting called");
        m.addWarning("HpCA","no Hep C Ab has been recorded");
end

rule "CMVI 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CMVI") >= 12 )
        eval( m.getLastDateRecordedInMonths("CMVI") < 18 )
    then
        m.log("CMVI 1 getting called");
        m.addRecommendation("CMVI","CMV lgG hasn't been recorded in "+m.getLastDateRecordedInMonths("CMVI")+" months");
end

rule "CMVI 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CMVI") >= 18 )
    then
        m.log("CMVI 2 getting called");
        m.addWarning("CMVI","CMV lgG hasn't been recorded in "+m.getLastDateRecordedInMonths("CMVI")+" months");
end

rule "CMVI 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CMVI") ==  -1 )
    then
        m.log("CMVI 3 getting called");
        m.addWarning("CMVI","no CMV lgG has been recorded");
end

rule "G6PD 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("G6PD") >= 12 )
        eval( m.getLastDateRecordedInMonths("G6PD") < 18 )
    then
        m.log("G6PD 1 getting called");
        m.addRecommendation("G6PD","G6PD hasn't been recorded in "+m.getLastDateRecordedInMonths("G6PD")+" months");
end

rule "G6PD 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("G6PD") >= 18 )
    then
        m.log("G6PD 2 getting called");
        m.addWarning("G6PD","G6PD hasn't been recorded in "+m.getLastDateRecordedInMonths("G6PD")+" months");
end

rule "G6PD 3"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("G6PD") ==  -1 )
    then
        m.log("G6PD 3 getting called");
        m.addWarning("G6PD","no G6PD has been recorded");
end
