package HousingFlowsheet;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.MeasurementInfo;

rule "Hass 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Hass") >= 12 )
    then
        m.addWarning("Hass","Question not answered in "+m.getLastDateRecordedInMonths("Hass")+" months");
end

rule "Hass 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Hass") == -1 )
    then
        m.addWarning("Hass","Question not answered");
end

rule "CnAp 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CnAp") >= 12 )
    then
        m.addWarning("CnAp","Question not answered in "+m.getLastDateRecordedInMonths("CnAp")+" months");
end

rule "CnAp 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CnAp") == -1 )
    then
        m.addWarning("CnAp","Question not answered");
end

rule "HAP 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HAP") >= 12 )
    then
        m.addWarning("HAP","Question not answered in "+m.getLastDateRecordedInMonths("HAP")+" months");
end

rule "HAP 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HAP") == -1 )
    then
        m.addWarning("HAP","Question not answered");
end

rule "CCAC 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CCAC") >= 12 )
    then
        m.addWarning("CCAC","Question not answered in "+m.getLastDateRecordedInMonths("CCAC")+" months");
end

rule "CCAC 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CCAC") == -1 )
    then
        m.addWarning("CCAC","Question not answered");
end

rule "CMSP 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CMSP") >= 12 )
    then
        m.addWarning("CMSP","Question not answered in "+m.getLastDateRecordedInMonths("CMSP")+" months");
end

rule "CMSP 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CMSP") == -1 )
    then
        m.addWarning("CMSP","Question not answered");
end

rule "HVIS 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HVIS") >= 12 )
    then
        m.addWarning("HVIS","Question not answered in "+m.getLastDateRecordedInMonths("HVIS")+" months");
end

rule "HVIS 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("HVIS") == -1 )
    then
        m.addWarning("HVIS","Question not answered");
end

rule "Hsup 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Hsup") >= 12 )
    then
        m.addWarning("Hsup","Question not answered in "+m.getLastDateRecordedInMonths("Hsup")+" months");
end

rule "Hsup 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Hsup") == -1 )
    then
        m.addWarning("Hsup","Question not answered");
end
