package oscar.oscarEncounter.oscarMeasurements.flowsheets;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.MeasurementInfo;

//  Copyright (c) 2001-2002. Department of Family Medicine, McMaster University. All Rights Reserved.
//  Copyright (c) 2026 CARLOS Contributors. All Rights Reserved.
//
//  This software is published under the GPL GNU General Public License.
//  This program is free software; you can redistribute it and/or
//  modify it under the terms of the GNU General Public License
//  as published by the Free Software Foundation; either version 2
//  of the License, or (at your option) any later version.
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details. You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//
//  Originally written for the Department of Family Medicine, McMaster University.
//  Now maintained by the CARLOS EMR Project.
//  https://github.com/carlos-emr/carlos
//
//  Document   : hypertensionFlowsheet.xml
//  Created on : April 23, 2006, 12:47 PM
//  Author     : Jay Gallagher
//  Description:
//        Define hypertension flowsheet
//
//  Modifications by CARLOS Contributors, 2026.

rule "BP 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BP") >= 3)
        eval(m.getLastDateRecordedInMonths("BP") < 6)
    then
        m.log("BP 1 getting called");
        m.addRecommendation("BP","BP hasn't been reviewed in "+m.getLastDateRecordedInMonths("BP")+" months");
end

rule "BP 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BP") >= 6)
    then
        m.log("BP 2 getting called");
        m.addWarning("BP","BP hasn't been reviewed in "+m.getLastDateRecordedInMonths("BP")+" months");
end

rule "BP 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BP") == -1)
    then
        m.log("BP 3 getting called");
        m.addWarning("BP","BP hasn't been reviewed");
end

// NOSK

rule "NOSK 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("NOSK") >= 3)
        eval(m.getLastDateRecordedInMonths("NOSK") < 6)
        eval(m.getLastValueAsInt("NOSK") != 0)
    then
        m.log("NOSK 1 getting called");
        m.addRecommendation("NOSK","Number of Cigarettes hasn't been recorded in "+m.getLastDateRecordedInMonths("NOSK")+" months");
end

rule "NOSK 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("NOSK") >= 6)
        eval(m.getLastValueAsInt("NOSK") != 0)
    then
        m.log("NOSK 2 getting called");
        m.addWarning("NOSK","Number of Cigarettes hasn't been recorded in "+m.getLastDateRecordedInMonths("NOSK")+" months");
end

rule "NOSK 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("NOSK") == -1)
    then
        m.log("NOSK 3 getting called");
        m.addWarning("NOSK","Number of Cigarrettes has never been recorded, if non smoker enter zero");
end

rule "DIER 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DIER") >= 3)
        eval(m.getLastDateRecordedInMonths("DIER") < 6)
    then
        m.log("DIER 1 getting called");
        m.addRecommendation("DIER","Diet/Exercise hasn't been recorded in "+m.getLastDateRecordedInMonths("DIER")+" months");
end

rule "DIER 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DIER") >= 6)
    then
        m.log("DIER 2 getting called");
        m.addWarning("DIER","Diet/ Exercise hasn't been recorded in "+m.getLastDateRecordedInMonths("DIER")+" months");
end

rule "DIER 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DIER") == -1)
    then
        m.log("DIER 3 getting called");
        m.addWarning("DIER","Diet/Excercise has not been recorded");
end

// SODI

rule "SODI 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("SODI") >= 3)
        eval(m.getLastDateRecordedInMonths("SODI") < 6)
    then
        m.log("SODI 1 getting called");
        m.addRecommendation("SODI","Salt Intake hasn't been reviewed in "+m.getLastDateRecordedInMonths("SODI")+" months");
end

rule "SODI 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("SODI") >= 6)
    then
        m.log("SODI 2 getting called");
        m.addWarning("SODI","Salt Intake hasn't been reviewed in "+m.getLastDateRecordedInMonths("SODI")+" months");
end

rule "SODI 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("SODI") == -1)
    then
        m.log("SODI 3 getting called");
        m.addWarning("SODI","Salt Intake hasn't been reviewed");
end

// Drinks per Week

rule "DRPW 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DRPW") >= 3)
        eval(m.getLastDateRecordedInMonths("DRPW") < 6)
    then
        m.log("DRPW 1 getting called");
        m.addRecommendation("DRPW","The Number of Drinks per week hasn't been reviewed in "+m.getLastDateRecordedInMonths("DRPW")+" months");
end

rule "DRPW 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DRPW") >= 6)
    then
        m.log("DRPW 2 getting called");
        m.addWarning("DRPW","The Number of Drinks per week hasn't been reviewed in "+m.getLastDateRecordedInMonths("DRPW")+" months");
end

rule "DRPW 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("DRPW") == -1)
    then
        m.log("DRPW 3 getting called");
        m.addWarning("DRPW","The Number of Drinks per week hasn't been reviewed");
end

rule "WT 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("WT") >= 3)
        eval(m.getLastDateRecordedInMonths("WT") < 6)
    then
        m.log("WT 1 getting called");
        m.addRecommendation("WT","Weight hasn't been reviewed in "+m.getLastDateRecordedInMonths("WT")+" months");
end

rule "WT 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("WT") >= 6)
    then
        m.log("WT 2 getting called");
        m.addWarning("WT","Weight hasn't been reviewed in "+m.getLastDateRecordedInMonths("WT")+" months");
end

rule "WT 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("WT") == -1)
    then
        m.log("WT 3 getting called");
        m.addWarning("WT","Weight hasn't been reviewed");
end

// annual items

// BMI

rule "BMI 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BMI") >= 10)
        eval(m.getLastDateRecordedInMonths("BMI") < 12)
    then
        m.log("BMI 1 getting called");
        m.addRecommendation("BMI","BMI hasn't been recorded in "+m.getLastDateRecordedInMonths("BMI")+" months");
end

rule "BMI 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BMI") >= 12)
    then
        m.log("BMI 2 getting called");
        m.addWarning("BMI","BMI hasn't been recorded in "+m.getLastDateRecordedInMonths("BMI")+" months");
end

rule "BMI 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("BMI") == -1)
    then
        m.log("BMI 3 getting called");
        m.addWarning("BMI","no BMI has been recorded");
end

rule "ACR 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("ACR") >= 10)
        eval(m.getLastDateRecordedInMonths("ACR") < 12)
    then
        m.log("ACR 1 getting called");
        m.addRecommendation("ACR","An Alb: creat ratio value hasn't been recorded in "+m.getLastDateRecordedInMonths("ACR")+" months");
end

rule "ACR 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("ACR") >= 12)
    then
        m.log("ACR 2 getting called");
        m.addWarning("ACR","An Alb: creat ratio value hasn't been recorded in "+m.getLastDateRecordedInMonths("ACR")+" months");
end

rule "ACR 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("ACR") == -1)
    then
        m.log("ACR 3 getting called");
        m.addWarning("ACR","An Alb: creat ratio value has not been recorded");
end

rule "TCHD 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TCHD") >= 10)
        eval(m.getLastDateRecordedInMonths("TCHD") < 12)
    then
        m.log("TCHD 1 getting called");
        m.addRecommendation("TCHD","TC/HDL hasn't been recorded in "+m.getLastDateRecordedInMonths("TCHD")+" months");
end

rule "TCHD 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TCHD") >= 12)
    then
        m.log("TCHD 2 getting called");
        m.addWarning("TCHD","TC/HDL hasn't been recorded in "+m.getLastDateRecordedInMonths("TCHD")+" months");
end

rule "TCHD 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TCHD") == -1)
    then
        m.log("TCHD 3 getting called");
        m.addWarning("TCHD","TC/HDL has not been recorded");
end

rule "LDL 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LDL") >= 10)
        eval(m.getLastDateRecordedInMonths("LDL") < 12)
    then
        m.log("LDL 1 getting called");
        m.addRecommendation("LDL","LDL hasn't been recorded in "+m.getLastDateRecordedInMonths("LDL")+" months");
end

rule "LDL 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LDL") >= 12)
    then
        m.log("LDL 2 getting called");
        m.addWarning("LDL","LDL hasn't been recorded in "+m.getLastDateRecordedInMonths("LDL")+" months");
end

rule "LDL 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LDL") == -1)
    then
        m.log("LDL 3 getting called");
        m.addWarning("LDL","LDL has not been recorded");
end

rule "TG 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TG") >= 10)
        eval(m.getLastDateRecordedInMonths("TG") < 12)
    then
        m.log("TG 1 getting called");
        m.addRecommendation("TG","Triglycerides hasn't been recorded in "+m.getLastDateRecordedInMonths("TG")+" months");
end

rule "TG 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TG") >= 12)
    then
        m.log("TG 2 getting called");
        m.addWarning("TG","Triglycerides hasn't been recorded in "+m.getLastDateRecordedInMonths("TG")+" months");
end

rule "TG 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("TG") == -1)
    then
        m.log("TG 3 getting called");
        m.addWarning("TG","Triglycerides has not been recorded");
end

rule "EGFR 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EGFR") >= 10)
        eval(m.getLastDateRecordedInMonths("EGFR") < 12)
    then
        m.log("EGFR 1 getting called");
        m.addRecommendation("EGFR","An eGFR value hasn't been recorded in "+m.getLastDateRecordedInMonths("EGFR")+" months");
end

rule "EGFR 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EGFR") >= 12)
    then
        m.log("EGFR 2 getting called");
        m.addWarning("EGFR","An eGFR value hasn't been recorded in "+m.getLastDateRecordedInMonths("EGFR")+" months");
end

rule "EGFR 3"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EGFR") == -1)
    then
        m.log("EGFR 3 getting called");
        m.addWarning("EGFR","An eGFR value has not been recorded");
end
