package IdentificationFlowsheet;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.MeasurementInfo;

rule "OHIP 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("OHIP") >= 12 )
    then
        m.addWarning("OHIP","Question not answered in "+m.getLastDateRecordedInMonths("OHIP")+" months");
end

rule "OHIP 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("OHIP") == -1 )
    then
        m.addWarning("OHIP","Question not answered");
end

rule "SIN 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("SIN") >= 12 )
    then
        m.addWarning("SIN","Question not answered in "+m.getLastDateRecordedInMonths("SIN")+" months");
end

rule "SIN 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("SIN") == -1 )
    then
        m.addWarning("SIN","Question not answered");
end

rule "BCRT 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("BCRT") >= 12 )
    then
        m.addWarning("BCRT","Question not answered in "+m.getLastDateRecordedInMonths("BCRT")+" months");
end

rule "BCRT 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("BCRT") == -1 )
    then
        m.addWarning("BCRT","Question not answered");
end

rule "LAND 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("LAND") >= 12 )
    then
        m.addWarning("LAND","Question not answered in "+m.getLastDateRecordedInMonths("LAND")+" months");
end

rule "LAND 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("LAND") == -1 )
    then
        m.addWarning("LAND","Question not answered");
end

rule "Citz 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Citz") >= 12 )
    then
        m.addWarning("LAND","Question not answered in "+m.getLastDateRecordedInMonths("Citz")+" months");
end

rule "Citz 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Citz") == -1 )
    then
        m.addWarning("Citz","Question not answered");
end

rule "Othi 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Othi") >= 12 )
    then
        m.addWarning("LAND","Question not answered in "+m.getLastDateRecordedInMonths("Othi")+" months");
end

rule "Othi 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Othi") == -1 )
    then
        m.addWarning("Othi","Question not answered");
end

rule "Isup 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Isup") >= 12 )
    then
        m.addWarning("LAND","Question not answered in "+m.getLastDateRecordedInMonths("Isup")+" months");
end

rule "Isup 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Isup") == -1 )
    then
        m.addWarning("Isup","Question not answered");
end
