package inrFlowsheet;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.MeasurementInfo;

rule "COUM 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("COUM") >= 3 )
    then
        m.log("COUM 1 getting called");
        m.addRecommendation("COUM","LAST WEEKLY WARFARIN DOSE MEASUREMENT WAS : "+m.getLastDateRecordedInMonths("COUM")+" months");
end

rule "INR 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("INR") >= 3 )
    then
        m.log("INR 1 getting called");
        m.addWarning("INR","INR hasn't been reviewed in "+m.getLastDateRecordedInMonths("INR")+" months");
end
