package FinancesFlowsheet;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.MeasurementInfo;

rule "Regn 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Regn") >= 12 )
    then
        m.addWarning("Regn","Question not answered in "+m.getLastDateRecordedInMonths("Regn")+" months");
end

rule "Regn 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Regn") == -1 )
    then
        m.addWarning("Regn","Question not answered");
end

rule "Quat 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Quat") >= 12 )
    then
        m.addWarning("Quat","Question not answered in "+m.getLastDateRecordedInMonths("Quat")+" months");
end

rule "Quat 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Quat") == -1 )
    then
        m.addWarning("Quat","Question not answered");
end

rule "CPP 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CPP") >= 12 )
    then
        m.addWarning("CPP","Question not answered in "+m.getLastDateRecordedInMonths("CPP")+" months");
end

rule "CAIS 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("CAIS") == -1 )
    then
        m.addWarning("CAIS","Question not answered");
end

rule "info 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("info") >= 12 )
    then
        m.addWarning("info","Question not answered in "+m.getLastDateRecordedInMonths("info")+" months");
end

rule "info 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("info") == -1 )
    then
        m.addWarning("info","Question not answered");
end

rule "pink 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("pink") >= 12 )
    then
        m.addWarning("pink","Question not answered in "+m.getLastDateRecordedInMonths("pink")+" months");
end

rule "pink 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("pink") == -1 )
    then
        m.addWarning("pink","Question not answered");
end

rule "ROI 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("ROI") >= 12 )
    then
        m.addWarning("ROI","Question not answered in "+m.getLastDateRecordedInMonths("ROI")+" months");
end

rule "ROI 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("ROI") == -1 )
    then
        m.addWarning("ROI","Question not answered");
end

rule "Cons 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Cons") >= 12 )
    then
        m.addWarning("Cons","Question not answered in "+m.getLastDateRecordedInMonths("Cons")+" months");
end

rule "Cons 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Cons") == -1 )
    then
        m.addWarning("Cons","Question not answered");
end

rule "Ornt 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Ornt") >= 12 )
    then
        m.addWarning("Ornt","Question not answered in "+m.getLastDateRecordedInMonths("Ornt")+" months");
end

rule "Ornt 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Ornt") == -1 )
    then
        m.addWarning("Ornt","Question not answered");
end

rule "Insp 1"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Insp") >= 12 )
    then
        m.addWarning("Insp","Question not answered in "+m.getLastDateRecordedInMonths("Insp")+" months");
end

rule "Insp 2"
    when
        m : MeasurementInfo()
        eval( m.getLastDateRecordedInMonths("Insp") == -1 )
    then
        m.addWarning("Insp","Question not answered");
end
