package oscar.oscarEncounter.oscarMeasurements.flowsheets;

import io.github.carlos_emr.carlos.encounter.oscarMeasurements.MeasurementInfo;

//  Copyright (c) 2026 CARLOS Contributors. All Rights Reserved.
//
//  This software is published under the GPL GNU General Public License.
//  This program is free software; you can redistribute it and/or
//  modify it under the terms of the GNU General Public License
//  as published by the Free Software Foundation; either version 2
//  of the License, or (at your option) any later version.
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details. You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
//
//  Maintained by the CARLOS EMR Project.
//  https://github.com/carlos-emr/carlos
//
//  Modifications by CARLOS Contributors, 2026.

rule "HltA 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("HltA") >= 12)
    then
        m.addWarning("HltA","Question not answered in "+m.getLastDateRecordedInMonths("HltA")+" months");
end

rule "HltA 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("HltA") == -1)
    then
        m.addWarning("HltA","Question not answered");
end

rule "MHA 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("MHA") >= 12)
    then
        m.addWarning("MHA","Question not answered in "+m.getLastDateRecordedInMonths("MHA")+" months");
end

rule "MHA 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("MHA") == -1)
    then
        m.addWarning("MHA","Question not answered");
end

rule "SUA 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("SUA") >= 12)
    then
        m.addWarning("SUA","Question not answered in "+m.getLastDateRecordedInMonths("SUA")+" months");
end

rule "SUA 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("SUA") == -1)
    then
        m.addWarning("SUA","Question not answered");
end

rule "Lwil 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("Lwil") >= 12)
    then
        m.addWarning("Lwil","Question not answered in "+m.getLastDateRecordedInMonths("Lwil")+" months");
end

rule "Lwil 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("Lwil") == -1)
    then
        m.addWarning("Lwil","Question not answered");
end

rule "SoCm 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("SoCm") >= 12)
    then
        m.addWarning("Lwil","Question not answered in "+m.getLastDateRecordedInMonths("SoCm")+" months");
end

rule "SoCm 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("SoCm") == -1)
    then
        m.addWarning("SoCm","Question not answered");
end

rule "EdTr 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EdTr") >= 12)
    then
        m.addWarning("EdTr","Question not answered in "+m.getLastDateRecordedInMonths("EdTr")+" months");
end

rule "EdTr 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EdTr") == -1)
    then
        m.addWarning("EdTr","Question not answered");
end

rule "EmpA 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EmpA") >= 12)
    then
        m.addWarning("EmpA","Question not answered in "+m.getLastDateRecordedInMonths("EmpA")+" months");
end

rule "EmpA 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("EmpA") == -1)
    then
        m.addWarning("EmpA","Question not answered");
end

rule "LegA 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LegA") >= 12)
    then
        m.addWarning("LegA","Question not answered in "+m.getLastDateRecordedInMonths("LegA")+" months");
end

rule "LegA 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("LegA") == -1)
    then
        m.addWarning("LegA","Question not answered");
end

rule "Osup 1"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("Osup") >= 12)
    then
        m.addWarning("Osup","Question not answered in "+m.getLastDateRecordedInMonths("Osup")+" months");
end

rule "Osup 2"
    when
        m : MeasurementInfo()
        eval(m.getLastDateRecordedInMonths("Osup") == -1)
    then
        m.addWarning("Osup","Question not answered");
end
