package Prevention;

import io.github.carlos_emr.carlos.prevention.Prevention;

rule "DTaP-IPV 1"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 2 )
        eval( prev.getAgeInMonths() < 72 )
        eval( prev.getNumberOfPreventionType("DTaP-IPV") == 0 )
        eval( prev.getNumberOfPreventionType("DTaP-IPV-Hib") == 0 )
        eval( !prev.isPreventionNever("DTaP-IPV") )
    then
        prev.log("DTaP-IPV 1");
        prev.addWarning("DTaP-IPV", "Needs First DTaP-IPV /HIB");
end

rule "DTaP-IPV 2"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 4 )
        eval( prev.getAgeInMonths() <= 72 )
        eval( prev.getNumberOfPreventionType("DTaP-IPV") == 1 )
        eval( prev.getHowManyMonthsSinceLast("DTaP-IPV") >= 2 )
        eval( !prev.isPreventionNever("DTaP-IPV") )
        eval( prev.isNextDateSet("DTaP-IPV") )
    then
        prev.log("DTaP-IPV 2");
        prev.addWarning("DTaP-IPV", "Needs Second DTaP-IPV /HIB");
end

rule "DTaP-IPV 2.1"
    when
        prev : Prevention()
        eval( prev.isPassedNextDate("DTaP-IPV") )
        eval( prev.getNumberOfPreventionType("DTaP-IPV") == 1 )
        eval( prev.getHowManyMonthsSinceLast("DTaP-IPV") >= 2 )
        eval( !prev.isPreventionNever("DTaP-IPV") )
    then
        prev.log("DTaP-IPV 2");
        prev.addWarning("DTaP-IPV", "Needs Second DTaP-IPV /HIB");
end

rule "DTaP-IPV 3"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 6 )
        eval( prev.getAgeInMonths() < 72 )
        eval( prev.getNumberOfPreventionType("DTaP-IPV") == 2 )
        eval( prev.getHowManyMonthsSinceLast("DTaP-IPV") >= 2 )
        eval( !prev.isPreventionNever("DTaP-IPV") )
    then
        prev.log("DTaP-IPV 3");
        prev.addWarning("DTaP-IPV", "Needs Third DTaP-IPV /HIB");
end

rule "DTaP-IPV 3.1"
    when
        prev : Prevention()
        eval( prev.isPassedNextDate("DTaP-IPV") )
        eval( prev.getNumberOfPreventionType("DTaP-IPV") == 2 )
        eval( prev.getHowManyMonthsSinceLast("DTaP-IPV") >= 2 )
        eval( !prev.isPreventionNever("DTaP-IPV") )
    then
        prev.log("DTaP-IPV 2.1");
        prev.addWarning("DTaP-IPV", "Needs Third DTaP-IPV /HIB");
end

rule "DTaP-IPV 4"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 18 )
        eval( prev.getAgeInMonths() < 72 )
        eval( prev.getNumberOfPreventionType("DTaP-IPV") == 3 )
        eval( prev.getHowManyMonthsSinceLast("DTaP-IPV") >= 12 )
        eval( !prev.isPreventionNever("DTaP-IPV") )
    then
        prev.log("DTaP-IPV 4");
        prev.addWarning("DTaP-IPV", "Needs Fourth DTaP-IPV /HIB");
end

rule "DTaP-IPV 4.1"
    when
        prev : Prevention()
        eval( prev.isPassedNextDate("DTaP-IPV") )
        eval( prev.getNumberOfPreventionType("DTaP-IPV") == 2 )
        eval( prev.getHowManyMonthsSinceLast("DTaP-IPV") >= 2 )
        eval( !prev.isPreventionNever("DTaP-IPV") )
    then
        prev.log("DTaP-IPV 2.1");
        prev.addWarning("DTaP-IPV", "Needs Third DTaP-IPV /HIB");
end

rule "DTaP-IPV 5"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 48 )
        eval( prev.getAgeInMonths() < 72 )
        eval( prev.getNumberOfPreventionType("DTaP-IPV") == 4 )
        eval( prev.getHowManyMonthsSinceLast("DTaP-IPV") >= 1 )
        eval( prev.getAgeInMonthsLastPreventionTypeGiven("DTaP-IPV") <= 48 )
        eval( !prev.isPreventionNever("DTaP-IPV") )
    then
        prev.log("DTaP-IPV 3");
        prev.addWarning("DTaP-IPV", "Needs Third DTaP-IPV /HIB");
end

rule "DTaP-IPV 6"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 168 )
        eval( prev.getAgeInMonths() < 192 )
        eval( prev.getNumberOfPreventionType("DTaP-IPV") == 4 )
        eval( prev.getHowManyMonthsSinceLast("DTaP-IPV") >= 1 )
        eval( prev.getAgeInMonthsLastPreventionTypeGiven("DTaP-IPV") <= 48 )
        eval( !prev.isPreventionNever("DTaP-IPV") )
    then
        prev.log("DTaP-IPV 3");
        prev.addWarning("DTaP-IPV", "Needs Third DTaP-IPV /HIB");
end

rule "Tdap-IPV 1"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 48 )
        eval( prev.getAgeInMonths() <= 72 )
        eval( prev.getNumberOfPreventionType("Tdap-IPV") == 0 )
        eval( !prev.isPreventionNever("Tdap-IPV") )
    then
        prev.log("Tdap-IPV 1");
        prev.addWarning("Tdap-IPV", "Needs Tdap-IPV vaccine");
end

rule "Rot 1"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 2 )
        eval( prev.getAgeInMonths() < 5 )
        eval( prev.getNumberOfPreventionType("Rot") == 0 )
        eval( !prev.isPreventionNever("Rot") )
    then
        System.out.println("Rot 1");
        prev.addWarning("Rot", "Needs First Rot-1 vaccine");
end

rule "Rot 2"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 4 )
        eval( prev.getAgeInMonths() <= 6 )
        eval( prev.getNumberOfPreventionType("Rot") == 1 )
        eval( prev.getHowManyMonthsSinceLast("Rot") >= 1 )
        eval( !prev.isPreventionNever("Rot") )
        eval( prev.isNextDateSet("Rot") )
    then
        System.out.println("Rot 2");
        prev.addWarning("Rot", "Needs Second Rot-1 vaccine");
end

rule "Hib 1"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 2 )
        eval( prev.getAgeInMonths() < 12 )
        eval( prev.getNumberOfPreventionType("Hib") == 0 )
        eval( prev.getNumberOfPreventionType("DTaP-IPV-Hib") == 0 )
    then
        prev.log("Hib 1");
        prev.addWarning("Hib", "Needs first Hib");
end

rule "Hib 2"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 4 )
        eval( prev.getAgeInMonths() < 12 )
        eval( prev.getNumberOfPreventionType("Hib") == 1 )
        eval( prev.getHowManyMonthsSinceLast("Hib") >= 2 )
    then
        prev.log("Hib 2");
        prev.addWarning("Hib", "Needs second Hib");
end

rule "Hib 3"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 6 )
        eval( prev.getAgeInMonths() < 12 )
        eval( prev.getNumberOfPreventionType("Hib") == 2 )
        eval( prev.getHowManyMonthsSinceLast("Hib") >= 2 )
    then
        prev.log("Hib 3");
        prev.addWarning("Hib", "Needs third Hib");
end

rule "Hib 4"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 12 )
        eval( prev.getAgeInMonths() < 24 )
        eval( prev.getNumberOfPreventionType("Hib") == 0 )
        eval( prev.getNumberOfPreventionType("DTaP-IPV-Hib") == 0 )
    then
        prev.log("Hib 4");
        prev.addWarning("Hib", "Needs first Hib");
end

rule "Hib 5"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 12 )
        eval( prev.getAgeInMonths() < 24 )
        eval( prev.getNumberOfPreventionType("Hib") == 1 )
        eval( prev.getHowManyMonthsSinceLast("Hib") >= 2 )
    then
        prev.log("Hib 5");
        prev.addWarning("Hib", "Needs second Hib");
end

rule "Hib 6"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 24 )
        eval( prev.getAgeInMonths() < 60 )
        eval( prev.getNumberOfPreventionType("Hib") == 0 )
    then
        prev.log("Hib 6");
        prev.addWarning("Hib", "Needs second Hib");
end

rule "Pneu-C 1"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 2 )
        eval( prev.getAgeInMonths() < 12 )
        eval( prev.getNumberOfPreventionType("Pneu-C") == 0 )
    then
        prev.log("Pneu-C 1");
        prev.addWarning("Pneu-C", "Needs First Pneu-C");
end

rule "Pneu-C 2"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 4 )
        eval( prev.getAgeInMonths() < 12 )
        eval( prev.getNumberOfPreventionType("Pneu-C") == 1 )
        eval( prev.getHowManyMonthsSinceLast("Pneu-C") >= 2 )
    then
        prev.log("Pneu-C 2");
        prev.addWarning("Pneu-C", "Needs Second Pneu-C");
end

rule "Pneu-C 3"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 6 )
        eval( prev.getAgeInMonths() < 12 )
        eval( prev.getNumberOfPreventionType("Pneu-C") == 2 )
        eval( prev.getHowManyMonthsSinceLast("Pneu-C") >= 2 )
    then
        prev.log("Pneu-C 3");
        prev.addWarning("Pneu-C", "Needs Third Pneu-C");
end

rule "Pneu-C 4"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 15 )
        eval( prev.getAgeInMonths() < 24 )
        eval( prev.getNumberOfPreventionType("Pneu-C") == 3 )
        eval( prev.getHowManyMonthsSinceLast("Pneu-C") >= 6 )
    then
        prev.log("Pneu-C 4");
        prev.addWarning("Pneu-C", "Needs Fourth Pneu-C");
end

rule "Pneu-C 5"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 12 )
        eval( prev.getAgeInMonths() < 24 )
        eval( prev.getNumberOfPreventionType("Pneu-C") == 0 )
    then
        prev.log("Pneu-C 5");
        prev.addWarning("Pneu-C", "Needs First Pneu-C");
end

rule "Pneu-C 6"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 14 )
        eval( prev.getAgeInMonths() < 24 )
        eval( prev.getNumberOfPreventionType("Pneu-C") == 1 )
        eval( prev.getHowManyMonthsSinceLast("Pneu-C") >= 2 )
    then
        prev.log("Pneu-C 6");
        prev.addWarning("Pneu-C", "Needs Second Pneu-C");
end

rule "MMR 1"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 12 )
        eval( prev.getAgeInYears() < 10 )
        eval( prev.getNumberOfPreventionType("MMR") == 0 )
        eval( prev.getNumberOfPreventionType("MMRV") == 0 )
    then
        prev.log("MMR 1");
        prev.addWarning("MMR", "Needs First MMR or MMRV");
end

rule "MMR 2"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 48 )
        eval( prev.getAgeInYears() < 10 )
        eval( prev.getNumberOfPreventionType("MMR") == 1 )
    then
        prev.log("MMR 2");
        prev.addWarning("MMR", "Needs Second MMR or MMRV");
end

rule "MMRV 1"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 48 )
        eval( prev.getAgeInYears() < 10 )
        eval( prev.getNumberOfPreventionType("MMRV") == 1 )
    then
        prev.log("MMRV 1");
        prev.addWarning("MMRV", "Needs Second MMR or MMRV");
end

rule "MenC-C 1"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 12 )
        eval( prev.getAgeInYears() < 24 )
        eval( prev.getNumberOfPreventionType("MenC-C") == 0 )
    then
        prev.log("Pneu-C 4");
        prev.addWarning("MenC-C", "Needs MenC-C");
end

rule "MenC-C 2"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 12 )
        eval( prev.getAgeInYears() < 13 )
        eval( prev.getNumberOfPreventionType("MenC-C") == 0 )
    then
        prev.log("MenC-C 2");
        prev.addWarning("MenC-C", "Needs MenC-C");
end

rule "HPV 1"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 12 )
        eval( prev.getAgeInYears() < 19 )
        eval( prev.getNumberOfPreventionType("[HPV-9] Human Papillomavirus") + prev.getNumberOfPreventionType("[HPV-4] Human Papillomavirus")  + prev.getNumberOfPreventionType("HPV Vaccine") == 0 )
    then
        prev.log("HPV 1");
        prev.addWarning("HPV", "Needs HPV");
end

rule "MenC-C 3"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 15 )
        eval( prev.getAgeInYears() <= 19 )
        eval( prev.getNumberOfPreventionType("MenC-C") == 0 )
    then
        prev.log("MenC-C 3");
        prev.addWarning("MenC-C", "Needs MenC-C");
end

rule "VZ 1"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 15 )
        eval( prev.getAgeInMonths() <= 24 )
        eval( prev.getNumberOfPreventionType("VZ") == 0 )
        eval( prev.getHowManyDaysSinceLast("MMR") >= 28 )
    then
        prev.log("VZ 1");
        prev.addWarning("VZ", "Needs VZ");
end

rule "VZ 2"
    when
        prev : Prevention()
        eval( prev.getAgeInMonths() >= 15 )
        eval( prev.getAgeInMonths() <= 24 )
        eval( prev.getNumberOfPreventionType("VZ") == 0 )
        eval( prev.getHowManyDaysSinceLast("MMR") == 0 )
    then
        prev.log("VZ 2");
        prev.addWarning("VZ", "Needs VZ");
end

rule "VZ 3"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 4 )
        eval( prev.getAgeInYears() <= 6 )
        eval( prev.getNumberOfPreventionType("VZ") == 0 )
        eval( prev.getHowManyDaysSinceLast("MMR") >= 28 )
    then
        prev.log("VZ 3");
        prev.addWarning("VZ", "Needs VZ");
end

rule "VZ 4"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 4 )
        eval( prev.getAgeInYears() <= 6 )
        eval( prev.getNumberOfPreventionType("VZ") == 0 )
        eval( prev.getHowManyDaysSinceLast("MMR") == 0 )
    then
        prev.log("VZ 4");
        prev.addWarning("VZ", "Needs VZ");
end

rule "dTap 1"
    when
        prev : Prevention()
        eval( prev.getNumberOfPreventionType("dTap") == 0 )
        eval( prev.getHowManyMonthsSinceLast("DTaP-IPV") >= 120 )
    then
        prev.log("dTap 1");
        prev.addWarning("dTap", "Needs dTap");
end

rule "Td 1"
    when
        prev : Prevention()
        eval( prev.getNumberOfPreventionType("Td") == 0 )
        eval( prev.getHowManyMonthsSinceLast("dTaP") >= 120 )
    then
        prev.log("Td 1");
        prev.addWarning("Td", "Needs Td");
end

rule "Td 2"
    when
        prev : Prevention()
        eval( prev.getNumberOfPreventionType("Td") >= 1 )
        eval( prev.getHowManyMonthsSinceLast("Td") >= 120 )
        eval( prev.getHowManyMonthsSinceLast("dTaP") >= 120 )
        eval( prev.getHowManyMonthsSinceLast("Td-IPV") >= 120 )
        eval( prev.getHowManyMonthsSinceLast("TdP-IPV-Hib") >= 120 )
        eval( prev.getHowManyMonthsSinceLast("Tdap-IPV") >= 120 )
    then
        prev.log("Td 2");
        prev.addWarning("Td", "Needs repeat Td");
end

rule "Flu 1"
    when
        prev : Prevention()
        eval( prev.isTodayinDateRange("2005-10-01","2006-01-29") )
        eval( !prev.isLastPreventionWithinRange("Flu","2005-10-01","2006-01-29") )
    then
        prev.log("Flu 1");
        prev.addWarning("Flu", "Needs Flu Shot ");
end

rule "Flu 2"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >=65 )
        eval( prev.getHowManyMonthsSinceLast("Flu") >= 12 )
    then
        prev.log("Flu 2");
        prev.addWarning("Flu", "Needs Flu Shot ");
end

rule "Flu 3"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >=65 )
        eval( prev.getHowManyMonthsSinceLast("Flu") == -1 )
    then
        prev.log("Flu 3");
        prev.addWarning("Flu", "Needs Flu Shot ");
end

rule "Flu Set Date"
    when
        prev : Prevention()
        eval( prev.isNextDateSet("Flu") )
        eval( prev.isPassedNextDate("Flu") )
    then
        prev.log("Flu 1");
        prev.addWarning("Flu", "Needs Flu Shot ");
end

rule "HPV-CERVIX 1"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 25 )
        eval( prev.getAgeInYears() < 75 )
        eval( prev.isFemale() )
        eval( prev.getHowManyMonthsSinceLast("HPV-CERVIX") >= 58 )
        eval( prev.getHowManyMonthsSinceLast("HPV-CERVIX") <= 60 )
        eval( !prev.isPreventionNever("HPV-CERVIX") )
        eval( !prev.isNextDateSet("HPV-CERVIX") )
        eval( !prev.isInelligible("HPV-CERVIX") )
    then
        prev.log("HPV-CERVIX 1");
        prev.addReminder("HPV-CERVIX repeat is coming due for this patient");
end

rule "HPV-CERVIX 2"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 25 )
        eval( prev.getAgeInYears() < 70 )
        eval( prev.isFemale() )
        eval( prev.getHowManyMonthsSinceLast("HPV-CERVIX") > 60 )
        eval( !prev.isPreventionNever("HPV-CERVIX") )
        eval( !prev.isNextDateSet("HPV-CERVIX") )
        eval( !prev.isInelligible("HPV-CERVIX") )
    then
        prev.log("HPV-CERVIX 2");
        prev.addWarning("HPV-CERVIX", "HPV-CERVIX is overdue for this patient");
end

rule "HPV-CERVIX 3"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 25 )
        eval( prev.getAgeInYears() < 70 )
        eval( prev.isFemale() )
        eval( prev.getHowManyMonthsSinceLast("PAP") == -1 )
        eval( !prev.isInelligible("PAP") )
        eval( prev.getHowManyMonthsSinceLast("HPV-CERVIX") == -1 )
        eval( !prev.isInelligible("HPV-CERVIX") )
    then
        prev.log("HPV-CERVIX 3");
        prev.addWarning("HPV-CERVIX", "Neighter HPV-CERVIX nor PAP records can be found for this patient");
end

rule "PAP 1"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 25 )
        eval( prev.getAgeInYears() < 70 )
        eval( prev.isFemale() )
        eval( prev.isPreventionNever("HPV-CERVIX") )
        eval( prev.getHowManyMonthsSinceLast("PAP") >= 34 )
        eval( prev.getHowManyMonthsSinceLast("PAP") <= 36 )
        eval( !prev.isPreventionNever("PAP") )
        eval( !prev.isNextDateSet("PAP") )
        eval( !prev.isInelligible("PAP") )
    then
        prev.log("PAP 1");
        prev.addReminder("PAP is coming due for this patient");
end

rule "PAP 2"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 25 )
        eval( prev.getAgeInYears() < 70 )
        eval( prev.isFemale() )
        eval( prev.getHowManyMonthsSinceLast("PAP") > 36 )
        eval( !prev.isPreventionNever("PAP") )
        eval( !prev.isNextDateSet("PAP") )
        eval( !prev.isInelligible("PAP") )
        eval( prev.getHowManyMonthsSinceLast("HPV-CERVIX") == -1 )
    then
        prev.log("PAP 2");
        prev.addWarning("PAP", "PAP is overdue for this patient");
end

rule "PAP 4"
    when
        prev : Prevention()
        eval( prev.isFemale() )
        eval( prev.isNextDateSet("PAP") )
        eval( prev.isPassedNextDate("PAP") )
        eval( !prev.isInelligible("PAP") )
    then
        prev.log("PAP 4");
        prev.addWarning("PAP", "PAP is overdue for this patient");
end

rule "PAP debug"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 25 )
        eval( prev.getAgeInYears() < 70 )
        eval( prev.isFemale() )
        eval( prev.getHowManyMonthsSinceLast("PAP") != -1 )
        eval( prev.getHowManyMonthsSinceLast("HPV-CERVIX") != -1 )
        eval( !prev.isInelligible("HPV-CERVIX") )
        eval( !prev.isInelligible("PAP") )
    then
        prev.log("PAP debug");
        prev.addReminder("Last PAP was done "+prev.getHowManyMonthsSinceLast("PAP")+" month(s) ago");
end

rule "MAM 1"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 50 )
        eval( prev.getAgeInYears() < 70 )
        eval( prev.isFemale() )
        eval( prev.getHowManyMonthsSinceLast("MAM") >= 22 )
        eval( prev.getHowManyMonthsSinceLast("MAM") <= 24 )
        eval( !prev.isPreventionNever("MAM") )
        eval( !prev.isNextDateSet("MAM") )
        eval( !prev.isInelligible("MAM") )
    then
        prev.log("MAM 1");
        prev.addReminder("Mammogram is coming due for this patient");
end

rule "MAM 2"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 50 )
        eval( prev.getAgeInYears() < 70 )
        eval( prev.isFemale() )
        eval( prev.getHowManyMonthsSinceLast("MAM") > 24 )
        eval( !prev.isPreventionNever("MAM") )
        eval( !prev.isNextDateSet("MAM") )
        eval( !prev.isInelligible("MAM") )
    then
        prev.log("MAM 2");
        prev.addWarning("MAM", "Mammogram is overdue for this patient");
end

rule "MAM 3"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 50 )
        eval( prev.getAgeInYears() < 70 )
        eval( prev.isFemale() )
        eval( prev.getHowManyMonthsSinceLast("MAM") == -1 )
        eval( !prev.isInelligible("MAM") )
    then
        prev.log("MAM 3");
        prev.addWarning("MAM", "No Mammogram records can be found for this patient");
end

rule "MAM 4"
    when
        prev : Prevention()
        eval( prev.isFemale() )
        eval( prev.isNextDateSet("MAM") )
        eval( prev.isPassedNextDate("MAM") )
        eval( !prev.isInelligible("MAM") )
    then
        prev.log("MAM 4");
        prev.addWarning("MAM", "MAM is overdue for this patient");
end

rule "MAM debug"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 18 )
        eval( prev.getAgeInYears() < 70 )
        eval( prev.isFemale() )
        eval( prev.getHowManyMonthsSinceLast("MAM") != -1 )
        eval( !prev.isInelligible("MAM") )
    then
        prev.log("MAM debug");
        prev.addReminder("Last Mammogram was done "+prev.getHowManyMonthsSinceLast("MAM")+" month(s) ago");
end

rule "FOBT 1"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 50 )
        eval( prev.getAgeInYears() <= 74 )
        eval( prev.getHowManyMonthsSinceLast("COLONOSCOPY") == -1 )
        eval( prev.getHowManyMonthsSinceLast("FOBT") >= 24 )
    then
        prev.log("FOBT 1 debug");
        prev.addWarning("FOBT", "FIT is overdue for this patient");
end

rule "FOBT 2"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 50 )
        eval( prev.getAgeInYears() <= 74 )
        eval( prev.getHowManyMonthsSinceLast("COLONOSCOPY") == -1 )
        eval( prev.getHowManyMonthsSinceLast("FOBT") == -1 )
    then
        prev.log("FOBT 2 debug");
        prev.addWarning("FOBT", "FIT is overdue for this patient");
end

rule "FOBT 3"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 50 )
        eval( prev.getAgeInYears() <= 74 )
        eval( prev.getHowManyMonthsSinceLast("COLONOSCOPY") >= 120 )
    then
        prev.log("FOBT 3 debug");
        prev.addWarning("FOBT", "Colonoscopy is over 10 years old");
end

rule "FOBT Inelligible"
    when
        prev : Prevention()
        eval( prev.getHowManyMonthsSinceLast("COLONOSCOPY") != -1 )
    then
        prev.log("FOBT Inelligible debug");
        prev.addReminder("Colonoscopy makes FIT Ineligible");
end

rule "Smoking"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 13 )
        eval( prev.getHowManyMonthsSinceLast("Smoking") == -1 )
    then
        prev.log("Smoking debug");
        prev.addReminder("Need to ask about Smoking");
end

rule "Bone Mineral Density"
    when
        prev : Prevention()
        eval( prev.getAgeInYears() >= 65 )
        eval( prev.getHowManyMonthsSinceLast("BMD") == -1 )
    then
        prev.log("BMD debug");
        prev.addReminder("Need Bone Mineral Density Test");
end

rule "PHV"
    when
        prev : Prevention()
        eval( prev.getHowManyMonthsSinceLast("PHV") == -1 )
    then
        prev.log("PHV debug");
        prev.addWarning("PHV", "Periodic Health Visit has never been reviewed");
end

rule "PHV 2"
    when
        prev : Prevention()
        eval( prev.getHowManyMonthsSinceLast("PHV") > 11 )
    then
        prev.log("PHV debug");
        prev.addWarning("PHV", "Periodic Health Visit has not occurred in over a year");
end

rule "Annual Physical"
    when
        prev : Prevention()
        eval( prev.getHowManyMonthsSinceLast("Annual Physical") == -1 )
    then
        prev.log("Annual Physical debug");
        prev.addWarning("Annual Physical", "Annual Physical has never been reviewed");
end

rule "Annual Physical 2"
    when
        prev : Prevention()
        eval( prev.getHowManyMonthsSinceLast("Annual Physical") > 11 )
    then
        prev.log("Annual Physical 2 debug");
        prev.addWarning("Annual Physical", "Annual Physical has not occurred in over 12 months");
end

rule "Obesity"
    when
        prev : Prevention()
        eval( prev.getHowManyMonthsSinceLast("Obesity") == -1 )
    then
        prev.log("Obesity debug");
        prev.addWarning("Obesity", "Obesity has never been reviewed");
end

rule "Obesity 2"
    when
        prev : Prevention()
        eval( prev.getHowManyMonthsSinceLast("Obesity") > 11 )
    then
        prev.log("Obesity 2 debug");
        prev.addWarning("Obesity", "Obesity check has not occurred in over 12 months");
end
