#!/usr/bin/env python3
# Copyright (c) 2026 CARLOS Contributors. Licensed under GPL-2.0-or-later.
"""Build the development-only NHS seed from checksum-pinned, downloaded CSV files."""

import argparse
import csv
from datetime import datetime
import hashlib
import json
from pathlib import Path
import uuid

REVISION = "368a5bd2a55090a0bae3436f2823d606c5077158"
DATASET = "https://huggingface.co/datasets/NHSEDataScience/synthetic_clinical_notes"
CHECKSUMS = {
    "patients.csv": "881daa1907b150545f96f3c0d6af1ae8363b0a81a56e14a80b55c49dcdb89853",
    "admissions.csv": "dbd6744ee99cddbcf67593939b10b405d8984a049a2ceeb5fd7b8250e62ad3fb",
    "synthetic_clinical_notes.csv": "2b33c63308c3dcdb6542d23b926acc570c235215eacc6975ac8b5879fca43299",
}
PATIENTS = (
    ("28570119-9cdc-4120-98c0-4edb76cf36a3", "NHSSYN001", 19),
    ("5cfa1b7e-c60e-4bae-b31f-b6be2c09adcb", "NHSSYN002", 20),
    ("29ea304f-821d-474e-81a1-394ca3945e02", "NHSSYN003", 17),
    ("51f15281-8840-4fd0-92de-89188ab8d736", "NHSSYN004", 32),
    ("136c7916-4f9b-4e5c-bf01-77e9d2c681a2", "NHSSYN005", 37),
    ("58b8aad6-7327-4450-956f-b775be0f4984", "NHSSYN006", 11),
    ("c332ce87-7afd-4a74-9896-3fef50179bd0", "NHSSYN007", 29),
    ("a9827c1c-fb54-4e5b-8bc6-d3099869e671", "NHSSYN008", 35),
    ("9d8fd25d-c4fe-4343-8ff5-5da5dad4e740", "NHSSYN009", 26),
    ("420df33b-0072-4124-b1c6-0589daef3677", "NHSSYN010", 25),
    ("d362867a-d350-4aca-82d0-a63b7e0a14c7", "NHSSYN011", 27),
    ("31f9612b-5a6b-48ea-887b-895772a83b99", "NHSSYN012", 46),
    ("37b5ce4d-dcfd-4bb7-bee4-d597eb114703", "NHSSYN013", 52),
    ("ef943dfb-1368-44e0-a946-a0be360e1d54", "NHSSYN014", 20),
    ("ff8c4724-b7de-4189-bccf-cffddd4d6d44", "NHSSYN015", 66),
    ("f44d4a08-4c76-4000-ad61-d1d81032e643", "NHSSYN016", 24),
    ("69bf7e25-abb2-4dde-857f-f1138d4d0d8a", "NHSSYN017", 70),
    ("04df53ea-55c1-48d9-84a1-1f15c133b29b", "NHSSYN018", 66),
    ("c50e236f-6b3d-41c8-9e16-7ec343cac820", "NHSSYN019", 60),
    ("b70c7ff6-c2af-4df6-bd88-889bf767a168", "NHSSYN020", 50),
    ("8448b3fa-1f5e-45b5-bda5-eb0b7921b8cc", "NHSSYN021", 44),
    ("359014a1-10e6-4bd8-9ba7-513d021c971e", "NHSSYN022", 68),
    ("61699d6d-904a-4ece-9026-cd61b3fd9a50", "NHSSYN023", 44),
    ("0c04d9fb-d8d0-4ee0-8fc9-0c3f7f148bdf", "NHSSYN024", 38),
    ("c6c45c39-cd73-49dd-818d-0a7865fe8a7f", "NHSSYN025", 90),
    ("1705dd0f-011a-492c-b006-b27e03f2f4ed", "NHSSYN026", 28),
    ("137b8481-4f1d-4b7f-babd-20f7117023ad", "NHSSYN027", 72),
    ("42149ae1-6a3c-471e-a002-cb7263e8bb8c", "NHSSYN028", 50),
    ("05192757-942f-460d-b4ff-004ec39cc5ee", "NHSSYN029", 46),
    ("5e434d78-b2f6-4d88-b327-fff6ee50b901", "NHSSYN030", 54),
    ("ce0046dc-0ad3-4710-8147-549793c58b44", "NHSSYN031", 21),
    ("f1538231-21af-4cfa-8b40-3303aa0d0c96", "NHSSYN032", 15),
    ("1dbe23dc-0d1e-431b-81eb-497282b46a14", "NHSSYN033", 17),
    ("028998ee-babc-4096-9b28-001bc2f9a84e", "NHSSYN034", 15),
    ("e8885d7c-b863-4c41-997e-588416d655ae", "NHSSYN035", 19),
    ("94264e23-ea67-496e-b027-5dd0cc334f1e", "NHSSYN036", 18),
    ("a8629d2e-7fd8-449a-9149-e0f5045a04c4", "NHSSYN037", 12),
    ("68258b8d-7d36-4d32-9093-6170a32bf087", "NHSSYN038", 18),
    ("973ee9d2-7c23-4e1d-afb2-86f679b55964", "NHSSYN039", 17),
    ("c51243b8-e3d9-4cf7-ab29-0315048f91dc", "NHSSYN040", 17),
    ("96766f3f-aa50-4bcb-abbf-884328049ea9", "NHSSYN041", 11),
    ("900efb9a-fb57-4f25-b2a3-0a8c6f55b2d6", "NHSSYN042", 15),
    ("c87e610e-ac2a-48cf-ac32-054f3e595498", "NHSSYN043", 10),
    ("6e93f9d9-213d-4f2c-a1f0-f475dacef554", "NHSSYN044", 35),
    ("c54a9649-495a-4f89-a8ca-fbb14ba70ca6", "NHSSYN045", 14),
    ("fc6268ab-ad15-4613-9d8d-12c045e2fd46", "NHSSYN046", 16),
    ("0f438665-d430-4adb-8acc-c3beed9e4942", "NHSSYN047", 15),
    ("f97ee974-67f3-4d72-9ed4-f17025da3749", "NHSSYN048", 13),
    ("ebb1ca4c-f42f-41d8-adbc-1b08949036d1", "NHSSYN049", 22),
    ("b8085350-6748-47a5-a12f-6acd07c40a82", "NHSSYN050", 16),
)


def literal(value):
    # Hex literals preserve UTF-8 and note line breaks independently of sql_mode.
    return "CONVERT(0x" + value.encode("utf-8").hex() + " USING utf8mb4)" if value else "''"


def read_source(directory, name):
    data = (directory / name).read_bytes()
    if hashlib.sha256(data).hexdigest() != CHECKSUMS[name]:
        raise ValueError("Source checksum mismatch: " + name)
    with (directory / name).open(encoding="utf-8-sig", newline="") as stream:
        return list(csv.DictReader(stream))


def timestamp(value):
    return datetime.strptime(value, "%d/%m/%Y %H:%M").strftime("%Y-%m-%d %H:%M:%S")


def build(directory, manifest=None):
    patients = read_source(directory, "patients.csv")
    admissions = read_source(directory, "admissions.csv")
    notes = read_source(directory, "synthetic_clinical_notes.csv")
    sql = [
        "-- GENERATED by build_nhs_synthetic_seed.py; do not hand-edit.",
        "-- DEVELOPMENT ONLY. " + str(len(PATIENTS)) + " invented NHS patient" + ("" if len(PATIENTS) == 1 else "s")
        + ", " + str(sum(count for _person, _chart, count in PATIENTS)) + " synthetic notes. No clinical use.",
        "-- Source: " + DATASET + " at " + REVISION,
        "-- Source data: MIT; Copyright (c) 2026 Crown Copyright NHS England.",
        "-- Preserve accompanying nhs-synthetic/LICENSE.txt and README.md.",
        "SET NAMES utf8mb4 COLLATE utf8mb4_general_ci;",
        "CREATE TEMPORARY TABLE nhs_seed_guard (reason VARCHAR(100), ok INT NOT NULL CHECK (ok = 1));",
        "INSERT INTO nhs_seed_guard VALUES ('exclusive seed lock', COALESCE(GET_LOCK('carlos.nhs_synthetic_dev_seed', 10), 0));",
        "START TRANSACTION;",
        "INSERT INTO nhs_seed_guard SELECT 'development database and provider context', IF("
        "DATABASE() = 'carlos' AND EXISTS (SELECT 1 FROM security WHERE user_name='carlosdoc' AND provider_no='999998') "
        "AND EXISTS (SELECT 1 FROM program_provider WHERE provider_no='999998' AND program_id=10034 AND role_id=2) "
        "AND EXISTS (SELECT 1 FROM program WHERE id=10034 AND name='OSCAR') "
        "AND (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() "
        "AND table_name IN ('demographic','casemgmt_note') AND engine='InnoDB')=2, 1, 0);",
    ]
    seen_note_ids = set()
    for person_id, chart_no, expected_count in PATIENTS:
        matching = [row for row in patients if row["person_id"] == person_id]
        matching_admissions = [row for row in admissions if row["patient_id"] == person_id]
        # The source repeats a patient row for each admission; one person is one chart holding every stay.
        if not matching or len(matching) != len(matching_admissions):
            raise ValueError("Expected one patient row per admission for the selected identity")
        if (len({(row["full_name"], row["date_of_birth"], row["gender_identity"]) for row in matching}) != 1
                or len({row["surname"] for row in matching_admissions}) != 1):
            raise ValueError("Expected a consistent identity across admissions")
        patient, admission = matching[0], matching_admissions[0]
        admission_ids = {row["admission_id"] for row in matching_admissions}
        patient_notes = sorted((row for row in notes if row["person_id"] == person_id),
                               key=lambda row: (timestamp(row["creation_timestamp"]), row["clinical_note_id"]))
        if len(patient_notes) != expected_count:
            raise ValueError("Unexpected source note count")
        first_name = patient["full_name"].rsplit(" ", 1)[0]
        last_name = "FAKE-NHS " + admission["surname"]
        if len(first_name) > 30 or len(last_name) > 30:
            raise ValueError("Selected name exceeds CARLOS field length")
        dob = datetime.strptime(patient["date_of_birth"], "%d/%m/%Y")
        marker = "NHS synthetic " + person_id
        chart, alias = literal(chart_no), literal(marker)
        fixture = {"chart_no": chart_no, "alias": marker,
                   "label": last_name + ", " + first_name, "notes": []}
        if manifest is not None:
            manifest.append(fixture)
        sql += [
            "-- " + chart_no + ": " + patient["full_name"] + " (" + str(expected_count) + " source notes)",
            "INSERT INTO nhs_seed_guard SELECT 'chart marker collision', IF("
            "(SELECT COUNT(*) FROM demographic WHERE chart_no=" + chart + ") <= 1 "
            "AND NOT EXISTS (SELECT 1 FROM demographic WHERE chart_no=" + chart
            + " AND NOT (alias <=> " + alias + ")), 1, 0);",
            "INSERT INTO demographic (first_name,last_name,year_of_birth,month_of_birth,date_of_birth,"
            "sex,patient_status,chart_no,provider_no,alias,lastUpdateUser,lastUpdateDate) SELECT "
            + ",".join(literal(value) for value in (
                first_name, last_name, dob.strftime("%Y"), dob.strftime("%m"), dob.strftime("%d"),
                "", "AC", chart_no, "999998", marker, "999998"))
            + ",NOW() WHERE NOT EXISTS (SELECT 1 FROM demographic WHERE chart_no=" + chart + ");",
            "SET @nhs_demographic_no = (SELECT demographic_no FROM demographic WHERE chart_no=" + chart + ");",
        ]
        for note in patient_notes:
            source_id = note["clinical_note_id"]
            uuid.UUID(source_id)
            if source_id in seen_note_ids or note["admission_id"] not in admission_ids:
                raise ValueError("Duplicate note identity or cross-admission source")
            seen_note_ids.add(source_id)
            note_uuid = str(uuid.uuid5(uuid.NAMESPACE_URL, DATASET + "/" + REVISION + "/" + source_id))
            body = (
                "SYNTHETIC NHS TEST PATIENT - NOT FOR CLINICAL USE\n"
                "Imported development fixture. The CARLOS signed flag enables demo display only; "
                "it is not a clinician signature or validation.\n"
                "Source: " + DATASET + "\nRevision: " + REVISION + "\n"
                "Source patient ID: " + person_id + "\nSource note ID: " + source_id + "\n"
                "Source admission ID: " + note["admission_id"] + "\n"
                "Recorded gender identity: " + patient["gender_identity"] + "\n"
                "Subject: " + note["note_subject"] + "\nType: " + note["note_type"] + "\n"
                "Silver data: generated notes have not been individually clinician-reviewed.\n"
                "Source text below is preserved verbatim, including encoding and clinical inconsistencies.\n\n"
                + note["clean_note_text"]
            )
            uid = literal(note_uuid)
            fixture["notes"].append({"sha256": hashlib.sha256(body.encode("utf-8")).hexdigest(),
                                     "date": timestamp(note["creation_timestamp"])[:10]})
            sql += [
                "-- Source note " + source_id,
                "INSERT INTO nhs_seed_guard SELECT 'note UUID belongs to another chart', IF(NOT EXISTS "
                "(SELECT 1 FROM casemgmt_note WHERE uuid=" + uid
                + " AND demographic_no<>@nhs_demographic_no), 1, 0);",
                "INSERT INTO casemgmt_note (demographic_no,provider_no,note,observation_date,update_date,"
                "signed,signing_provider_no,program_no,reporter_caisi_role,history,locked,archived,appointmentNo,uuid) "
                "SELECT @nhs_demographic_no,'999998'," + literal(body) + ","
                + literal(timestamp(note["creation_timestamp"])) + "," + literal(timestamp(note["updt_dt_tm"]))
                + ",1,'999998','10034','2','',0,0,0," + uid
                + " WHERE NOT EXISTS (SELECT 1 FROM casemgmt_note WHERE uuid=" + uid + ");",
            ]
    sql += [
        "COMMIT;",
        "DROP TEMPORARY TABLE nhs_seed_guard;",
        "DO RELEASE_LOCK('carlos.nhs_synthetic_dev_seed');",
        "SELECT demographic_no,chart_no,first_name,last_name FROM demographic "
        "WHERE chart_no IN (" + ",".join("'" + chart_no + "'" for _person, chart_no, _count in PATIENTS)
        + ") ORDER BY chart_no;",
    ]
    return "\n".join(sql) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--manifest-output", type=Path)
    args = parser.parse_args()
    manifest = []
    result = build(args.source_dir, manifest)
    args.output.write_text(result, encoding="utf-8")
    if args.manifest_output:
        args.manifest_output.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
