#!/usr/bin/env python3
# Copyright (c) 2026 CARLOS Contributors. Licensed under GPL-2.0-or-later.
"""Build the development-only NHS seed from checksum-pinned, downloaded CSV files."""

import argparse
import csv
from datetime import datetime
import hashlib
from pathlib import Path
import uuid

REVISION = "368a5bd2a55090a0bae3436f2823d606c5077158"
DATASET = "https://huggingface.co/datasets/NHSEDataScience/synthetic_clinical_notes"
CHECKSUMS = {
    "patients.csv": "881daa1907b150545f96f3c0d6af1ae8363b0a81a56e14a80b55c49dcdb89853",
    "admissions.csv": "dbd6744ee99cddbcf67593939b10b405d8984a049a2ceeb5fd7b8250e62ad3fb",
    "synthetic_clinical_notes.csv": "2b33c63308c3dcdb6542d23b926acc570c235215eacc6975ac8b5879fca43299",
}
PATIENTS = (
    ("28570119-9cdc-4120-98c0-4edb76cf36a3", "NHSSYN001", 19),
    ("5cfa1b7e-c60e-4bae-b31f-b6be2c09adcb", "NHSSYN002", 20),
    ("29ea304f-821d-474e-81a1-394ca3945e02", "NHSSYN003", 17),
)


def literal(value):
    # Hex literals preserve UTF-8 and note line breaks independently of sql_mode.
    return "CONVERT(0x" + value.encode("utf-8").hex() + " USING utf8mb4)" if value else "''"


def read_source(directory, name):
    data = (directory / name).read_bytes()
    if hashlib.sha256(data).hexdigest() != CHECKSUMS[name]:
        raise ValueError("Source checksum mismatch: " + name)
    with (directory / name).open(encoding="utf-8-sig", newline="") as stream:
        return list(csv.DictReader(stream))


def timestamp(value):
    return datetime.strptime(value, "%d/%m/%Y %H:%M").strftime("%Y-%m-%d %H:%M:%S")


def build(directory):
    patients = read_source(directory, "patients.csv")
    admissions = read_source(directory, "admissions.csv")
    notes = read_source(directory, "synthetic_clinical_notes.csv")
    sql = [
        "-- GENERATED by build_nhs_synthetic_seed.py; do not hand-edit.",
        "-- DEVELOPMENT ONLY. Three invented NHS patients, 56 synthetic notes. No clinical use.",
        "-- Source: " + DATASET + " at " + REVISION,
        "-- Source data: MIT; Copyright (c) 2026 Crown Copyright NHS England.",
        "-- Preserve accompanying nhs-synthetic/LICENSE.txt and README.md.",
        "SET NAMES utf8mb4 COLLATE utf8mb4_general_ci;",
        "CREATE TEMPORARY TABLE nhs_seed_guard (reason VARCHAR(100), ok INT NOT NULL CHECK (ok = 1));",
        "INSERT INTO nhs_seed_guard VALUES ('exclusive seed lock', COALESCE(GET_LOCK('carlos.nhs_synthetic_dev_seed', 10), 0));",
        "START TRANSACTION;",
        "INSERT INTO nhs_seed_guard SELECT 'development database and provider context', IF("
        "DATABASE() = 'oscar' AND EXISTS (SELECT 1 FROM security WHERE user_name='carlosdoc' AND provider_no='999998') "
        "AND EXISTS (SELECT 1 FROM program_provider WHERE provider_no='999998' AND program_id=10034 AND role_id=2) "
        "AND EXISTS (SELECT 1 FROM program WHERE id=10034 AND name='OSCAR') "
        "AND (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() "
        "AND table_name IN ('demographic','casemgmt_note') AND engine='InnoDB')=2, 1, 0);",
    ]
    seen_note_ids = set()
    for person_id, chart_no, expected_count in PATIENTS:
        matching = [row for row in patients if row["person_id"] == person_id]
        matching_admissions = [row for row in admissions if row["patient_id"] == person_id]
        if len(matching) != 1 or len(matching_admissions) != 1:
            raise ValueError("Expected one patient and admission per selected identity")
        patient, admission = matching[0], matching_admissions[0]
        patient_notes = sorted((row for row in notes if row["person_id"] == person_id),
                               key=lambda row: (timestamp(row["creation_timestamp"]), row["clinical_note_id"]))
        if len(patient_notes) != expected_count:
            raise ValueError("Unexpected source note count")
        first_name = patient["full_name"].rsplit(" ", 1)[0]
        last_name = "FAKE-NHS " + admission["surname"]
        if len(first_name) > 30 or len(last_name) > 30:
            raise ValueError("Selected name exceeds CARLOS field length")
        dob = datetime.strptime(patient["date_of_birth"], "%d/%m/%Y")
        marker = "NHS synthetic " + person_id
        chart, alias = literal(chart_no), literal(marker)
        sql += [
            "-- " + chart_no + ": " + patient["full_name"] + " (" + str(expected_count) + " source notes)",
            "INSERT INTO nhs_seed_guard SELECT 'chart marker collision', IF("
            "(SELECT COUNT(*) FROM demographic WHERE chart_no=" + chart + ") <= 1 "
            "AND NOT EXISTS (SELECT 1 FROM demographic WHERE chart_no=" + chart
            + " AND NOT (alias <=> " + alias + ")), 1, 0);",
            "INSERT INTO demographic (first_name,last_name,year_of_birth,month_of_birth,date_of_birth,"
            "sex,patient_status,chart_no,provider_no,alias,lastUpdateUser,lastUpdateDate) SELECT "
            + ",".join(literal(value) for value in (
                first_name, last_name, dob.strftime("%Y"), dob.strftime("%m"), dob.strftime("%d"),
                "", "AC", chart_no, "999998", marker, "999998"))
            + ",NOW() WHERE NOT EXISTS (SELECT 1 FROM demographic WHERE chart_no=" + chart + ");",
            "SET @nhs_demographic_no = (SELECT demographic_no FROM demographic WHERE chart_no=" + chart + ");",
        ]
        for note in patient_notes:
            source_id = note["clinical_note_id"]
            uuid.UUID(source_id)
            if source_id in seen_note_ids or note["admission_id"] != admission["admission_id"]:
                raise ValueError("Duplicate note identity or cross-admission source")
            seen_note_ids.add(source_id)
            note_uuid = str(uuid.uuid5(uuid.NAMESPACE_URL, DATASET + "/" + REVISION + "/" + source_id))
            body = (
                "SYNTHETIC NHS TEST PATIENT - NOT FOR CLINICAL USE\n"
                "Imported development fixture. The CARLOS signed flag enables demo display only; "
                "it is not a clinician signature or validation.\n"
                "Source: " + DATASET + "\nRevision: " + REVISION + "\n"
                "Source patient ID: " + person_id + "\nSource note ID: " + source_id + "\n"
                "Source admission ID: " + admission["admission_id"] + "\n"
                "Recorded gender identity: " + patient["gender_identity"] + "\n"
                "Subject: " + note["note_subject"] + "\nType: " + note["note_type"] + "\n"
                "Silver data: generated notes have not been individually clinician-reviewed.\n"
                "Source text below is preserved verbatim, including encoding and clinical inconsistencies.\n\n"
                + note["clean_note_text"]
            )
            uid = literal(note_uuid)
            sql += [
                "-- Source note " + source_id,
                "INSERT INTO nhs_seed_guard SELECT 'note UUID belongs to another chart', IF(NOT EXISTS "
                "(SELECT 1 FROM casemgmt_note WHERE uuid=" + uid
                + " AND demographic_no<>@nhs_demographic_no), 1, 0);",
                "INSERT INTO casemgmt_note (demographic_no,provider_no,note,observation_date,update_date,"
                "signed,signing_provider_no,program_no,reporter_caisi_role,history,locked,archived,appointmentNo,uuid) "
                "SELECT @nhs_demographic_no,'999998'," + literal(body) + ","
                + literal(timestamp(note["creation_timestamp"])) + "," + literal(timestamp(note["updt_dt_tm"]))
                + ",1,'999998','10034','2','',0,0,0," + uid
                + " WHERE NOT EXISTS (SELECT 1 FROM casemgmt_note WHERE uuid=" + uid + ");",
            ]
    sql += [
        "COMMIT;",
        "DROP TEMPORARY TABLE nhs_seed_guard;",
        "DO RELEASE_LOCK('carlos.nhs_synthetic_dev_seed');",
        "SELECT demographic_no,chart_no,first_name,last_name FROM demographic "
        "WHERE chart_no IN ('NHSSYN001','NHSSYN002','NHSSYN003') ORDER BY chart_no;",
    ]
    return "\n".join(sql) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    result = build(args.source_dir)
    args.output.write_text(result, encoding="utf-8")
