#!/usr/bin/env bash
#
# build-baseline.sh — regenerate the CARLOS Flyway V1 baseline (complete: schema + reference data).
#
# WHY: fresh CARLOS installs should not replay 20 years of dated update-*.sql patches, nor carry the
# dead tables of removed modules. This tool captures the *authoritative* database — what the
# devcontainer build scripts produce — as a clean, checksummed, DEAD-CODE-PRUNED Flyway baseline,
# split the Flyway-native way into a shared location plus per-province locations:
#
#   migration/common/V1__baseline_schema.sql     province-neutral tables (structure)
#   migration/on/V1.0.1__on_schema.sql            Ontario-only tables (structure)
#   migration/on/V1.0.2__on_data.sql              Ontario reference data (rows)
#   migration/bc/V1.0.1__bc_schema.sql            British Columbia-only tables (structure)
#   migration/bc/V1.0.2__bc_data.sql              British Columbia reference data (rows)
#
# A database applies common + exactly one province (flyway.locations=common,on | common,bc). The V1
# baseline is COMPLETE (schema + required reference data) so a fresh `flyway migrate` yields a working
# database. Demo/patient data is NOT here (see the demo location / dev seed).
#
# PRUNING: migration/pruned-tables.txt lists tables with zero references in CARLOS src/ (removed/
# legacy modules). They are dropped before the dump so V1 reflects only live schema. Keep that list
# authoritative — db-schema-verify.yml drops the same set from the legacy build so the parity diff
# holds.
#
# It is a MAINTAINER tool. Run it in the devcontainer (which has MariaDB) whenever the baseline needs
# regenerating, then commit the regenerated files. It never runs during the normal build.
#
# Usage:
#   database/mysql/build-baseline.sh [--host HOST] [--user USER] [--password PW]
#   MYSQL_HOST / MYSQL_USER / MYSQL_ROOT_PASSWORD env vars are honoured as defaults.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

HOST="${MYSQL_HOST:-127.0.0.1}"
USER="${MYSQL_USER:-root}"
PASSWORD="${MYSQL_ROOT_PASSWORD:-password}"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --host) HOST="$2"; shift 2 ;;
    --user) USER="$2"; shift 2 ;;
    --password) PASSWORD="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

export MYSQL_PWD="$PASSWORD"
MYSQL="mysql -h $HOST -u $USER"
DUMP="mysqldump -h $HOST -u $USER"

# The devcontainer/CI engine is MariaDB 10.5, where explicit_defaults_for_timestamp defaults to OFF
# (a bare `timestamp` column becomes NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()).
# MariaDB 10.10+ flips that default to ON. Force OFF so the baseline matches the 10.5 build.
$MYSQL -e "SET GLOBAL explicit_defaults_for_timestamp=0;" 2>/dev/null || true

# Recent updates populate_db.sh replays on top of the init scripts. Keep in sync with populate_db.sh.
REQUIRED_UPDATES="
update-2025-01-29.sql
update-2025-02-27.sql
update-2025-05-27.sql
update-2025-08-14-study-removal.sql
update-2025-12-16-provider-module-singular.sql
update-2026-01-02-add-flowsheet-admin-privilege.sql
update-2026-01-26-tickler-indexes.sql
update-2026-02-10-fax-provider-type.sql
update-2026-02-14-facility-integrator-removal.sql
update-2026-03-25-security-mfa-default.sql
update-2026-04-30-sec-obj-missing-privileges.sql
"

# Dead tables pruned from the baseline (removed/legacy modules; zero src/ references).
PRUNE_LIST="$(grep -v '^#' migration/pruned-tables.txt | grep -v '^[[:space:]]*$')"

normalize() {
  sed -E \
    -e 's/ AUTO_INCREMENT=[0-9]+//g' \
    -e 's/DEFINER=`[^`]+`@`[^`]+` //g' \
    -e '/^\/\*M!999999/d' \
    -e '/^-- Dump completed/d' \
    -e '/^-- Server version/d'
}
hdr() { printf -- '-- CARLOS baseline (%s) — GENERATED by build-baseline.sh, do not edit by hand.\n\n' "$1"; }

# Build a demo-free, dead-pruned database for a province and print its live table list to stdout.
build_pruned_db() {
  province="$1"; icd="$2"; db="carlos_baseline_${province}"
  # createdatabase_generic.sh directly (bc wrapper caps at 3 args, can't pass suppressPwdGen).
  $MYSQL -e "DROP DATABASE IF EXISTS ${db};" >&2
  ./createdatabase_generic.sh "$USER" "$PASSWORD" "$db" "$province" "$icd" suppressPwdGen >/dev/null 2>&1
  for u in $REQUIRED_UPDATES; do [ -f "updates/$u" ] && $MYSQL "$db" < "updates/$u" 2>/dev/null; done
  # prune dead tables
  { echo "SET FOREIGN_KEY_CHECKS=0;"; while IFS= read -r t; do echo "DROP TABLE IF EXISTS \`$t\`;"; done <<< "$PRUNE_LIST"; echo "SET FOREIGN_KEY_CHECKS=1;"; } | $MYSQL "$db" 2>/dev/null
  $MYSQL -N -e "SELECT table_name FROM information_schema.tables WHERE table_schema='${db}' ORDER BY table_name" | LC_ALL=C sort
}

echo "== CARLOS V1 baseline generator (complete, pruned, province-split) =="
build_pruned_db on 9 > /tmp/bb_on.txt
build_pruned_db bc 9 > /tmp/bb_bc.txt
comm -12 /tmp/bb_on.txt /tmp/bb_bc.txt > /tmp/bb_common.txt   # shared tables
comm -23 /tmp/bb_on.txt /tmp/bb_bc.txt > /tmp/bb_ononly.txt   # Ontario-only
comm -13 /tmp/bb_on.txt /tmp/bb_bc.txt > /tmp/bb_bconly.txt   # BC-only
echo ">> live tables: common=$(wc -l </tmp/bb_common.txt) on_only=$(wc -l </tmp/bb_ononly.txt) bc_only=$(wc -l </tmp/bb_bconly.txt)"

# common schema (shared tables are identical across provinces; dump from ON)
{ hdr "common schema — province-neutral live tables"; $DUMP --no-data --skip-comments --skip-dump-date --single-transaction carlos_baseline_on $(cat /tmp/bb_common.txt) 2>/dev/null | normalize; } > migration/common/V1__baseline_schema.sql
{ hdr "Ontario-only schema"; $DUMP --no-data --skip-comments --skip-dump-date carlos_baseline_on $(cat /tmp/bb_ononly.txt) 2>/dev/null | normalize; } > migration/on/V1.0.1__on_schema.sql
{ hdr "British Columbia-only schema"; $DUMP --no-data --skip-comments --skip-dump-date carlos_baseline_bc $(cat /tmp/bb_bconly.txt) 2>/dev/null | normalize; } > migration/bc/V1.0.1__bc_schema.sql
# full reference data per province (includes common-table rows + province rows)
{ hdr "Ontario reference data"; $DUMP --no-create-info --skip-comments --skip-dump-date --hex-blob --single-transaction --skip-triggers carlos_baseline_on 2>/dev/null | normalize; } > migration/on/V1.0.2__on_data.sql
{ hdr "British Columbia reference data"; $DUMP --no-create-info --skip-comments --skip-dump-date --hex-blob --single-transaction --skip-triggers carlos_baseline_bc 2>/dev/null | normalize; } > migration/bc/V1.0.2__bc_data.sql

$MYSQL -e "DROP DATABASE IF EXISTS carlos_baseline_on; DROP DATABASE IF EXISTS carlos_baseline_bc;" 2>/dev/null || true
echo ">> wrote migration/{common,on,bc}/V1* baseline files."
echo ">> Verify (docs/database-schema-management.md): flyway migrate common+<prov> into a fresh DB and"
echo "   diff schema + row counts against the pruned legacy build — expect no diff."
