#!/usr/bin/env bash
#
# build-baseline.sh — regenerate the CARLOS Flyway schema baseline (V1) for each province.
#
# WHY: fresh CARLOS installs should not replay 20 years of dated update-*.sql patches. This tool
# captures the *authoritative schema* — what the devcontainer build scripts produce — as a clean,
# checksummed Flyway baseline:
#
#   migration/on/V1__baseline_schema.sql   Ontario schema (structure only)
#   migration/bc/V1__baseline_schema.sql   British Columbia schema (structure only)
#
# It captures STRUCTURE ONLY (mysqldump --no-data). Seed / reference / demo data is deliberately
# excluded (the authoritative "schema" is the table structure, not the default rows; demo data is
# dev-only and loaded separately). Seed/reference migrations, if adopted later, are added as
# separate V1.x files — see docs/database-schema-management.md.
#
# The baseline is province-complete (each province dir carries its full schema); migration/common/
# is reserved for genuinely shared FUTURE migrations. Because a given database only ever applies
# common + ONE province location, the two V1 files never collide.
#
# It is a MAINTAINER tool. Run it in the devcontainer (which has MariaDB) whenever the baseline
# needs regenerating, then commit the regenerated V1 files. It never runs during the normal build.
#
# Usage:
#   database/mysql/build-baseline.sh [--host HOST] [--user USER] [--password PW]
#   MYSQL_HOST / MYSQL_USER / MYSQL_ROOT_PASSWORD env vars are honoured as defaults.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

HOST="${MYSQL_HOST:-127.0.0.1}"
USER="${MYSQL_USER:-root}"
PASSWORD="${MYSQL_ROOT_PASSWORD:-password}"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --host) HOST="$2"; shift 2 ;;
    --user) USER="$2"; shift 2 ;;
    --password) PASSWORD="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

export MYSQL_PWD="$PASSWORD"

# The devcontainer/CI engine is MariaDB 10.5, where explicit_defaults_for_timestamp defaults to OFF
# (a bare `timestamp` column becomes NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()).
# MariaDB 10.10+ flips that default to ON (bare timestamp -> NULL DEFAULT NULL), which would capture a
# DIFFERENT schema. Force OFF so the baseline matches the 10.5 build regardless of the host engine.
mysql -h "$HOST" -u "$USER" -e "SET GLOBAL explicit_defaults_for_timestamp=0;" 2>/dev/null || true

# The recent updates populate_db.sh replays on top of the init scripts today. Keep this list in
# sync with .devcontainer/db/scripts/populate_db.sh until the cutover retires that block.
REQUIRED_UPDATES="
update-2025-01-29.sql
update-2025-02-27.sql
update-2025-05-27.sql
update-2025-08-14-study-removal.sql
update-2025-12-16-provider-module-singular.sql
update-2026-01-02-add-flowsheet-admin-privilege.sql
update-2026-01-26-tickler-indexes.sql
update-2026-02-10-fax-provider-type.sql
update-2026-02-14-facility-integrator-removal.sql
update-2026-03-25-security-mfa-default.sql
update-2026-04-30-sec-obj-missing-privileges.sql
"

# Normalize a mysqldump --no-data stream so the committed file is stable across runs/hosts:
# drop AUTO_INCREMENT counters, DEFINER clauses, the mariadb-dump sandbox-mode directive, and the
# dump-date / server-version lines.
normalize() {
  sed -E \
    -e 's/ AUTO_INCREMENT=[0-9]+//g' \
    -e 's/DEFINER=`[^`]+`@`[^`]+` //g' \
    -e '/^\/\*M!999999/d' \
    -e '/^-- Dump completed/d' \
    -e '/^-- Server version/d'
}

build_province() {
  province="$1"   # on | bc  (LOCATION qualifier for oscarinit_$LOCATION / oscardata_$LOCATION)
  icd="$2"        # 9 | 10   (icd$ICD.sql). Both provinces currently ship ICD-9.
  label="$3"      # human-readable name for the file header
  tmp_db="carlos_baseline_${province}"

  # Call createdatabase_generic.sh directly rather than the province wrappers: the bc wrapper caps
  # at 3 args and cannot pass suppressPwdGen. generic = (user password db LOCATION ICD suppress).
  echo ">> building throwaway ${tmp_db} (LOCATION=${province}, ICD=${icd}) + required updates"
  mysql -h "$HOST" -u "$USER" -e "DROP DATABASE IF EXISTS ${tmp_db};"
  ./createdatabase_generic.sh "$USER" "$PASSWORD" "$tmp_db" "$province" "$icd" suppressPwdGen >/dev/null

  for u in $REQUIRED_UPDATES; do
    [ -f "updates/$u" ] && mysql -h "$HOST" -u "$USER" "$tmp_db" < "updates/$u"
  done

  out="migration/${province}/V1__baseline_schema.sql"
  echo ">> writing ${out}"
  {
    printf -- '-- CARLOS consolidated schema baseline (%s) — GENERATED by build-baseline.sh, do not edit by hand.\n' "$label"
    printf -- '-- Structure only (no seed/demo data). Captured from the devcontainer script build:\n'
    printf -- '-- createdatabase_generic.sh %s %s + the required updates/*.sql. Regenerate with build-baseline.sh.\n\n' "$province" "$icd"
    mysqldump -h "$HOST" -u "$USER" --no-data --skip-comments --skip-dump-date \
      --single-transaction --routines --events "$tmp_db" | normalize
  } > "$out"

  mysql -h "$HOST" -u "$USER" -e "DROP DATABASE IF EXISTS ${tmp_db};"
}

echo "== CARLOS schema baseline generator =="
build_province on 9 "Ontario"
build_province bc 9 "British Columbia"
echo
echo ">> wrote migration/on/V1__baseline_schema.sql and migration/bc/V1__baseline_schema.sql"
echo ">> Verify (docs/database-schema-management.md): flyway migrate into a fresh DB and diff its"
echo "   schema (excluding flyway_schema_history) against the script-built DB — expect no diff."
